### ISSUE TITLE
Replace default asp.net icon with branded icon

### ISSUE THREAD

**Issue by ppptrevoro** [neo-project/neo.org#1]
## Update stock asp.net website icon to branded icon
When visiting https://www.antshares.org/ I noticed that the website icon is still using the default icon created with asp.net projects.  This is a small issue but should be updated to display the branded icon.

![image](https://user-images.githubusercontent.com/16230261/28495906-7084bbbe-6f1a-11e7-9f96-359b158ff683.png)

**Comment by erikzhang** [comment]
resolved
