### ISSUE TITLE
I want to go NEO DevCon! My email: nickazg@gmail.com

### ISSUE THREAD

**Issue by nickazg** [neo-project/neo.org#100]
My name is Nick Grobler and I'm a part-time NEO developer living in New Zealand, trying make the big switch from my day job! I have a keen entrepreneurial spirit and a passion for emerging technologies, which is why I'm so excited about NEO. In particular, its potential to foster innovation and new ideas through decentralised crowdfunding. Recently I submitted my dApp in the 1st CoZ competition (https://github.com/nickazg/neo-fund). Im currently expanding on this concept and contributing as I develop my skill-set and network. I also have experience in python and javascript.

I would love the opportunity to come to the conference, to make new connections and bring NEO technology to this side of the world. 

<img src="https://user-images.githubusercontent.com/19567737/34596840-cb6e647a-f247-11e7-8cf9-fa927aec500f.png" width="50" height="50"/>

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @nickazg
