### ISSUE TITLE
I want to go to NEO DevCon! My email: samsamskies@gmail.com

### ISSUE THREAD

**Issue by SamSamskies** [neo-project/neo.org#101]
My name is Steven Miyakawa and I'm a Senior Software Engineer at HERE Technologies. My strength is front-end web development and I particularly enjoy working with React and Redux.

I became interested in NEO after attending a panel last month in San Francisco featuring Da Hongfei, Jed McCalleb and others.

I'm still quite new to working with the blockchain, but I have deployed Ethereum smart contracts to the Ropsten Test Net.

Here's a Tic Tac Toe app I built at an Ethereum hackathon to learn how to hook up a smart contract to a React application:
https://github.com/SamSamskies/blockchain-tic-tac-toe
https://github.com/SamSamskies/blockchain-tic-tac-toe/blob/master/contract/index.sol
https://github.com/SamSamskies/blockchain-tic-tac-toe/blob/master/src/App.js

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @SamSamskies
