### ISSUE TITLE
I want to go to NEO DevCon! My email: fanghai44@gmail.com

### ISSUE THREAD

**Issue by qimingfang** [neo-project/neo.org#102]
Hello!

I'm a mobile developer based in SF Bay Area. I got into crypto pretty recently and have been experimenting with setting up my own geth node and brass Golem. My very first crypto related PR is a [1 character typo fix](https://github.com/ETHLend/Documentation/pull/8) for ETHLend 😅 

After a bit of digging, I found NEO and I'm excited to explore how NEO smart contracts work. The fact that languages like Java and Python are supported is already a huge plus. One of my goals of going to DevCon is to figure out what kind of interesting (open source) opportunities exist between NEO and mobile development.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @qimingfang
