### ISSUE TITLE
I want to go to NEO DevCon! My email: techgeekaj@gmail.com

### ISSUE THREAD

**Issue by adithyaj** [neo-project/neo.org#103]
Hello! I'm a junior UC Berkeley studying Electrical Engineering & Computer Science (EECS). I've been learning a lot about NEO's platform and vision along with how to develop dApps with the Blockchain at Berkeley curriculum. I think it would be great to attend NEO DevCon in order to better understand the deployment of smart contracts so I can develop on the platform!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @adithyaj
