### ISSUE TITLE
I want to go to NEO DevCon! My email: melvin0008@gmail.com

### ISSUE THREAD

**Issue by melvin0008** [neo-project/neo.org#104]
Hey,

I'm a developer at VMware, Palo Alto. I have contributed to open source projects on github and you can find them at https://github.com/melvin0008. Regarding Neo, I remember opening an issue for a broken link of the consensus paper https://github.com/neo-project/docs/issues/148 in September. 

I have developed an interest towards the NEO blockchain and would like to develop using Javascript/ Python/ Ruby. I also visited the NEO blockchain meetup in San Francisco and loved the partnership with Stellar and Elastos. At DevCon, I would like to figure out which are the open source projects that I can contribute to help the NEO community.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @melvin0008
