### ISSUE TITLE
I want to go to NEO DevCon! My email: gaurav.kg15@gmail.com

### ISSUE THREAD

**Issue by gauravkg15** [neo-project/neo.org#105]
Hi! I'm a Junior at San Diego State University studying computer science. I'm very interested in NEO and have been doing a lot of reasearch and am also an investor. My goal is to have a thorough understanding of the implementation of the NEO platform in order to develop DApps and regularly contribute. It would be a blast to attend this event!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @gauravkg15
