### ISSUE TITLE
I want to go to NEO DevCon! My email: venelin.stoykov@industria.tech

### ISSUE THREAD

**Issue by vstoykov** [neo-project/neo.org#106]
Hello I'm Senior Software Developer at INDUSTRIA (industria.tech). We are currently very interested in Blockchain technology. We have an idea of a blockchain application and are currently deciding between Etherium and NEO for technology of our choice.

NEO looks very promising and I want to participate in the DevCon to learn more about NEO.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @vstoykov
