### ISSUE TITLE
I want to go NEO DevCon! My email: craigmak1039@gmail.com

### ISSUE THREAD

**Issue by ghost** [neo-project/neo.org#107]
I am computer science major @ UofA and have currently been working on ios and Android versions of NEO tracker integrated wallet with auto gas claim via threshold set. 
Currently working java C C++ python

**Comment by Craigmak1039** [comment]
https://github.com/CityOfZion/neon-wallet-db

**Comment by Craigmak1039** [comment]
https://github.com/neo-project/neo-cli

**Comment by Craigmak1039** [comment]
Am also working on ledger blue application for neo currently.

**Comment by chenzhitong** [comment]
You just joined the GitHub yesterday? Do not fill in false information. @Craigmak1039

**Comment by Craigmak1039** [comment]
Absolutely not, i am just very security conscious and would not like to post public here so i created a separate account or alias. I choose not to connect my github to my personal life, i hope you understand

**Comment by chenzhitong** [comment]
But these projects are someone else's, and you can't apply for tickets with links to other people's projects. @Craigmak1039

**Comment by TheCoinJunkie** [comment]
Someone else's project to which i have made number contributions. Thank you
