### ISSUE TITLE
NEO DevCon giving out developer tickets to non devs

### ISSUE THREAD

**Issue by ghost** [neo-project/neo.org#108]
I was refused a press ticket due to not being a "developer who has contributed to the github" yet there are numerous others who have received a ticket. Some even admit in the issue that they have never even worked on a blockchain or cryptocurrency project in their life. 
This is totally not how this ticket should be dispersed. If the tickets are for devs only they should stick to the rules.

**Comment by 4math2379** [comment]
They give ticket for people who got repository here in github or who can provide some link about dev project. 
 I don’t understand your issue ?

**Comment by TheCoinJunkie** [comment]
No they did not. Many others received them with no repository at all and one even admitted never working on a single cryptocurrency project. Look at commit #62 and #83 as aj example

**Comment by 4math2379** [comment]
I m sorry both of this github user got several repo. 
Have yo ever use github ?

**Comment by chenzhitong** [comment]
你烦不烦 @TheCoinJunkie
