### ISSUE TITLE
I want to go to NEO DevCon! My email: igor.yuzovitskiy@gmail.com

### ISSUE THREAD

**Issue by ByteDown** [neo-project/neo.org#110]
I'm incredibly excited for the new smart economy and the role NEO will be playing in it. It's an amazing time to be a developer because we get to build the infrastructure that will power the next wave of dApps. I've been working on implementing blockchain tech at my previous company Workrails and currently have been experimenting with smart contracts on the Ethereum platform as well. Here's a link to some of my work - https://github.com/ByteDown/ICO.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ByteDown

**Comment by ByteDown** [comment]
Thanks @chenzhitong for the opportunity, can't wait to meet everyone!
