### ISSUE TITLE
I want to go to NEO DevCon! My email: russ.sherman@gmail.com

### ISSUE THREAD

**Issue by russellsherman** [neo-project/neo.org#111]
I am a security software engineer currently working in the financial technology industry, focusing on developing orchestration platforms for security incident response and intelligence aggregation. 

I am a co-founder and engineer of VISO Trust (https://www.visotrust.com), a web platform for exchanging validated corporate information security program information. I'm interested in leveraging blockchain for the purposes of efficiently performing security due diligence.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @russellsherman
