### ISSUE TITLE
I want to go to NEO DevCon! My email: nodar.janashia@gmail.com

### ISSUE THREAD

**Issue by nodar** [neo-project/neo.org#113]
Thank you NEO for coming to the U.S. for DevCon! I'm currently the CTO and Founder of CountUp.io - an online marketplace connecting licensed accountants with small businesses. We have over 300 registered CPAs working with thousands of their clients through our platform. One of the most crucial components of our platform is the security and confidentiality of sensitive financial information that our users share on the platform. I started exploring crypto assets a few months ago. Given my passion for accounting, I immediately thought of consensus mechanisms as the next step for the double-entry record keeping system. Currently, I'm exploring executing accounting engagement contracts between clients and accountants using NEO smart contracts. Unfortunately, I am based in Brooklyn, NY so any help with NEO Devcon admission would be greatly appreciated. https://www.countup.io/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @nodar

**Comment by nodar** [comment]
Thank you so much! This is incredible! Look forward to the conference.
