### ISSUE TITLE
I want to go to NEO DevCon! My email: tylors1@gmail.com 

### ISSUE THREAD

**Issue by tylors1** [neo-project/neo.org#114]
I have been closely following the development of Antshares/NEO since earlier last year and attended the meetup in November. I am a recent graduate from university and am looking for ways to get involved in blockchain development. I have dabbled in working with Ethereum and NEO smart contracts but as a younger developer it would be an incredible opportunity to have the chance to discuss with those who are more experienced and attend NEO DevCon to learn how to better educate myself in this space!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tylors1
