### ISSUE TITLE
I want to go NEO DevCon! My email: d_jurado391@hotmail.com

### ISSUE THREAD

**Issue by 0d4rujd** [neo-project/neo.org#115]
My name is Diego Jurado (@djurado9) and I belong to Red4Sec, the company that performed a Security Audit for NEO Smart Economy (https://twitter.com/neo_blockchain/status/942640352707653632?lang=en). More than 4 years of experience in CyberSecurity, and specialized in Ethical Hacking and Vulnerability Assessment I am know involved in blockchain and cryptocurrencies development.

I know the NEO project very closely, since I have been part of the security group at Slack and Discord during the last 4 months. However, Devcon will allow me to continue learning and knowing the technology.

It would be a great oportunity for me to enjoy this event (DevCon) and do some networking with speakers and assistants. I also would like to be able to attend the talk given by my partner Fernando Diaz Toledano (@Shargon).

Linkedin Profile: https://www.linkedin.com/in/djuradopallares/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @0d4rujd
