### ISSUE TITLE
I want to go to NEO DevCon! My email: alex.hint.ah@gmail.com

### ISSUE THREAD

**Issue by DeProdigy** [neo-project/neo.org#116]
Hi! My name is Alex and I am a full-stack developer. I currently work for a mid-size Fintech startup called Betterment. I am interested in the Blockchain development and have been learning Solidity. I am interested in attending NEO Devcon because I want to learn more about NEO and the community around it. Would love to see y'all in SF.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @DeProdigy

**Comment by DeProdigy** [comment]
Thank you!
