### ISSUE TITLE
I want to go to NEO DevCon! My email: danielrak@me.com

### ISSUE THREAD

**Issue by DanielRakh** [neo-project/neo.org#117]
As an iOS developer and Designer I'm incredibly excited to see what NEO has in store and the type of apps I can build on NEO to make it more mainstream. I'm currently a designer and developer at Mic - a pretty big media company here in the states and looking forward to see what products we can build on the platform. I would love to attend this conference if possible! 

Thank you!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @DanielRakh
