### ISSUE TITLE
I want to go NEO DevCon! My email: evgeny.boxer@gmail.com

### ISSUE THREAD

**Issue by evgenyboxer** [neo-project/neo.org#118]
I'm a core contributor to the Neon Wallet project, and currently working for NEX (NeonExchange)

https://github.com/CityOfZion/neon-wallet

**Comment by nodar** [comment]
Evgeny could you connect me with someone from your team @NEX? Really interested in getting involved and showing support!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @evgenyboxer
