### ISSUE TITLE
I want to go to NEO DevCon! My e-mail: elnivek@protonmail.com

### ISSUE THREAD

**Issue by elnivek** [neo-project/neo.org#119]
Almost everything I know about blockchain technology is because of Antshares/NEO, and have grown with the community since August. On my spare time after work at an IoT startup, I would work on projects such as these two basic projects:
- https://github.com/elnivek/neo-blockchain-explorer
- https://github.com/elnivek/neo-elixir-wallet

Additionally, I have practiced with very basic smart contracts with neo-python. Currently I am working on a NEO smart contract project, but there is no public code available yet.

Outside of NEO development, I have written some trading APIs:
- https://github.com/elnivek/bitFlyer-python-api

I took the chance to attend the San Francisco meetup and became involved with the translation/editing community of Elastos. I have also recently found work at a crypto-related startup.

I would consider then that my current career path in blockchain is a result of the tireless efforts of the NEO community, and I want to give more back to the community by attending this DevCon.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @elnivek
