### ISSUE TITLE
I want to go NEO DevCon! My email: belane@cityofzion.io

### ISSUE THREAD

**Issue by belane** [neo-project/neo.org#120]
Hi, I'm Belane and I belong to Red4Sec, who performed the Security Audit for NEO Smart Economy and now active member of Security Team on Neo and City of Zion.

I would like to attend to DevCon to do some networking, meet other Neo Team members, inprove my Neo perspective and attend the talk given by my partner Fernando Diaz (@shargon).

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @belane

**Comment by belane** [comment]
Thank you!, I'm looking forward to see you there.
