### ISSUE TITLE
I want to go to NEO DevCon! My email: marco@saldo.mx

### ISSUE THREAD

**Issue by marcomontesneri** [neo-project/neo.org#121]
I want to go to NEO DevCon Im involved in saldo.mx a cross border payment system , rainvow a smart contract platform for parametric insurance. And working in an enterprise solution for a big pharma to use smart contracts for traceability  of subsidies for specific medicines and asset creation

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @marcomontesneri

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @marcomontesneri

**Comment by marcomontesneri** [comment]
really appreciate it.

2018-01-07 20:58 GMT-06:00 陈志同 <notifications@github.com>:
