### ISSUE TITLE
I want to go to NEO DevCon! My email: jitendra@chittoda.com

### ISSUE THREAD

**Issue by jchittoda** [neo-project/neo.org#122]
I am Jitendra Chittoda,
I am currently a Blockchain Technical Advisor at https://ethlend.io
I do Ethereum Smart Contract development and also do the Security reviews of Smart Contracts.
My LinkedIn profile: https://www.linkedin.com/in/jchittoda/

### GitHub Repo:
https://github.com/jchittoda/ICO_SmartContract (ETHLend ICO Smart Contract repo)
https://github.com/jchittoda/gmr-token (Gimmer ICO Smart Contract repo)
Working on private repo of ETHLend Dapp

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jchittoda
