### ISSUE TITLE
I want to go to NEO DevCon! My email: eric.chen0121@gmail.com

### ISSUE THREAD

**Issue by ericchen0121** [neo-project/neo.org#123]
I'm a software engineer with startup, analytics and web development and fullstack experience with - js and js frameworks for mobile as well as desktop (ie. React Native) as well as SQL (postgresql), MongoDB and ruby and python. 

I've become a crypto enthusiast and starting some side-projects with other software engineering friends related to blockchain technologies. At the TechCrunch hackathon, we won the Accenture prize for a disaster relief app that used blockchain-like technology with the Swirlds sdk (http://www.swirlds.com/). 

https://github.com/CityOfZion/neon-wallet
https://github.com/CityOfZion/neo-scan
https://github.com/hyperledger/composer
https://github.com/citp/BlockSci

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ericchen0121
