### ISSUE TITLE
I want to go to NEO DevCon! My email: pavankat@gmail.com

### ISSUE THREAD

**Issue by pavankat** [neo-project/neo.org#124]
I'm a software engineer and data analytics and web development Instructor at UC Berkeley Extension. 

http://linkedin.com/in/pavankat

I've used Ruby, Python, Node.js, Java, PHP, as well as a wide array of front-end technologies like Knockout.js, React.js and am well versed in Javascript (ES5 and ES6) and jQuery.

I've also been trained by renowned core bitcoin developer: Jimmy Song.

I've been investing in crypto since 2013.

I'm working on the google finance of crypto right now. It's a closed source project, but will be ready for the Devcon!

I made this guide on how Big O works in computer science: https://github.com/pavankat/big-o-in-plain-english

This is the best guide on the internet on the topic. Everything else explains it like rocket science.

I made this machine learning web app: https://github.com/pavankat/flask-ml

The app takes in a user's information about their house and predicts the price of their house using a Gradient Boosting model with Huber loss and 1000 regression trees of depth 6.

I made fantasy football algorithms: https://github.com/pavankat/fantasy-football

It's a weighted mean of different rankings. For example, it looks for wide receivers on a team with a good offense but a bad defense, playing teams with a bad defense but a good offense. 

This is an example I made of a Many to Many and Polymorphic relationship in Ruby On Rails, I even did the front end where I created Multi Select Dropdowns that leveraged the Many to Many association and Polymorphic association.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @pavankat

**Comment by pavankat** [comment]
thank you!
