### ISSUE TITLE
I want to go to NEO DevCon! My email: imomin@gmail.com

### ISSUE THREAD

**Issue by imomin** [neo-project/neo.org#125]
I am a fullstack (MEAN) developer and currently operating a small SaaS startup in payment space. 
I am exploring different options for Blockchain development for my next project which _may_ change how user authentication is done.  I am leaning towards using NEO for my project, therefore, I am interested in attending NEO Devcon.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @imomin

**Comment by imomin** [comment]
Awesome! See you there.
