### ISSUE TITLE
I want to go to NEO DevCon! My email: machomannu@gmail.com

### ISSUE THREAD

**Issue by mannutech** [neo-project/neo.org#126]
I am Hitesh Goel from India currently working as a blockchain developer at an Indian cryptocurrency exchange responsible for automating the blockchain transaction cycle in and out of the platform for Bitcoin, Litecoin, Ripple and other coins using blend of Node.js and MSSQL/MySQL.
I have been aligning my skill sets with business level smart contracts using Tendermint and Truffle.js to accomplish intra company process managements. 
I have a special affinity to learn and build **regex** for string validations.
Github link: [A cryptocurrency rate ticker convertor ](https://github.com/mannutech/rate)
I want to leverage NEO to achieve interledger atomic swaps using lightweight SPV client.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mannutech
