### ISSUE TITLE
I want to go to NEO DevCon! My email: raullen@iotex.io

### ISSUE THREAD

**Issue by raullenchai** [neo-project/neo.org#129]
I am a crypto enthusiast and researcher. We have a fascinating team full time working on iotex.io, a decentralized network for Internet of Things (IoT).

NEO looks very promising and I want to participate in the DevCon to learn more about NEO.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @raullenchai
