### ISSUE TITLE
I want to go to NEO DevCon! My email: foxlee25@gmail.com

### ISSUE THREAD

**Issue by foxlee25** [neo-project/neo.org#131]
Hello NEO I'm Senior Software Developer and currently working on cryptocurrency wallet that supports most poplar coins.
I am planing towards using NEO for my project, therefore, I am interested in attending NEO Devcon.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @foxlee25
