### ISSUE TITLE
I want to go to NEO DevCon! My email: kristiqn.tachev@gmail.com

### ISSUE THREAD

**Issue by Stradivario** [neo-project/neo.org#132]
Hello there i am Kristiyan Tachev from Bulgaria and i am a Developer, Geophysicist using technologies like: 

- GraphQL
- Typescript
- Angular 5.1.3
- Ethereum Solidity
- Nodejs
- RabbitMQ
- Nginx
- Docker
- Kubernetes

Currently i am working on a blockchain project related with Ethereum platform which will be used to help people find their stolen things like pets, cars, etc. Totally different project than mytrackinfo.net and is not released yet.I have some contributions to the community library like [ngx-cache-layer](https://www.npmjs.com/package/ngx-cache-layer) it is a library for angular 4+ which is helping to get connected with your components without using component binding because it is not so clean.Also help us to create Observable stream for Cache Collection which you can use everywhere in your application.It is written inside library documentation how to use it.

So i want to be on that conference because i want to share my knowledge and to get knowledge because the world needs people which in the first place are willing to share information with others.

I have some ideas of creating application which will help human mankind to be more precise when exploring Minerals, Rocks, Petrol with help of blockchain network.

Thank you for your time reading this post!

Best Regards,
Kristiyan Tachev

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Stradivario

**Comment by Stradivario** [comment]
Thank you very much! And see you soon!
