### ISSUE TITLE
I want to go to NEO DevCon! My email: economou.vasilis7@gmail.com

### ISSUE THREAD

**Issue by oikobill** [neo-project/neo.org#133]
Hello!

My name is Vasilis and I am junior at UC Berkeley studying Computer Science and Statistics. I have long been interested in Cryptography and Artificial Intelligence and I have recently been involved with the blockchain education at Berkeley through [Blockchain at Berkeley](https://blockchain.berkeley.edu/) where I have had the chance to interact with more than 200 students interested in blockchain technologies. I hold NEO and I am actively trying to better understand the technology and contribute to the community by becoming a developer. I am very interested in talking to more experienced developers and sharing those insights with the Berkeley community. I am also currently working with a stealth startup in London, exploring ways of leveraging AI in the context of blockchain technologies.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @oikobill
