### ISSUE TITLE
I want to go to NEO DevCon! My email: gaigatech@gmail.com

### ISSUE THREAD

**Issue by appDevEnterpreneur** [neo-project/neo.org#134]
I'm a highly motivated application developer that is currently building my first DApp on the Ethereum platform. My career focus is to develop software that helps businesses perform more efficiently, and I see many applications for the blockchain and the development of DApps on top of Ethereum. The smart contracts is very powerful concept and I would love the opportunity to explore DApp development on the NEO platform, but I'm finding very limited resources at the moment and feel that NEO DevCon would be a great resource to learn this and about the possibilities.

My primary tech stack is Microsoft tech (.Net, ASP.NET, C#, Dynamics 365, Azure, Xamarin, etc.) used in building applications for businesses. Here is a link to my linkedin profile: https://www.linkedin.com/in/michaelgaiga/ I'm looking forward to having this amazing opportunity to explore NEO and start my first NEO based DApp.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @appDevEnterpreneur

**Comment by chenzhitong** [comment]
You have no contribution on the GitHub, I should not have given you free tickets. But I read your LinkedIn and your mailbox name. You're a real developer.
