### ISSUE TITLE
I want to go to NEO DevCon! My email: dmitriy@polyledger.com

### ISSUE THREAD

**Issue by DmitriyBe** [neo-project/neo.org#135]
Hi team NEO - Thank you for hosting this conference! I'm the Co-Founder of Polyledger (https://polyledger.com/), an early-stage startup that offers users a transparent, flexible, and simple way to invest in a diversified portfolio of cryptoassets catered to their risk tolerance. We're looking for additional assets to integrate into our platform and would love to learn about what NEO is planning for 2018 and beyond!

**Comment by chenzhitong** [comment]
Are you the developer of the Polyledger project? 
If you are a developer, I can give you free tickets. If you are the boss, you need to buy a ticket.

**Comment by chenzhitong** [comment]
Are you the developer of the Polyledger project?
If you are a developer, I can give you free tickets. If you are the boss, you need to buy a ticket. @DmitriyBe
