### ISSUE TITLE
I want to go to NEO DevCon! My email: leotextile@gmail.com

### ISSUE THREAD

**Issue by tianlizhou** [neo-project/neo.org#138]
您好，我是开发者+Neo社区关注者，参加17年5月上海科技节竞赛，项目名称为AntshareCosmos，目前更名为NeoCosmos，亦参加6月北京微软大厦发布会。参加了10月的区块链管理师和架构师培训.已经提交相关项目资料给西仔，希望能够参加Neo开发者大会。

Hi,I am a developer and always watching at Neo.I have join ShangHai Tech in may,2017 and join the Neo rebirth in Beijing.I want to join Neo DevCon@Silicon Valley .

**Comment by chenzhitong** [comment]
免费票的促销代码和使用说明已经发到你的邮箱中了，请注意查收。 @tianlizhou
