### ISSUE TITLE
I want to go to NEO DevCon! My email: tk@blockcollider.org

### ISSUE THREAD

**Issue by korczis** [neo-project/neo.org#139]
I am versatile folk with experience from low-level assembly, c/c++ to distributed systems and saas.

My career started as honeywell aerospace, then computer games to BI Saas.

At the moment I am core developer of multichain/metachain technology called Block Collider -   https://blockcollider.org/

 https://github.com/blockcollider

```
With over 12 years of development experience in low-level C/C++ and Assembly, Tomas is a veteran 
programmer specializing in large scale architecture and algorithmic optimization. Fluent in 6 
programming languages, Tomas has built everything from complex graphics engines used in games 
by Disney and Silent Hill to large scale data reporting tools and analyses tools for some of the 
world’s largest companies.
```

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @korczis

**Comment by korczis** [comment]
Thank you!
