### ISSUE TITLE
I want to go to NEO DevCon! My email: me@jonchurch.com

### ISSUE THREAD

**Issue by jonchurch** [neo-project/neo.org#140]
# Hello!

### I am a freelance Node JS developer who specializes in Chatbots.

I'm an active contributor to the [Botkit](www.github.com/howdyai/botkit) Framework for building bots, and have been teaching myself blockchain technologies, solidity smart contract development, and crypto investing. I am interested in getting more involved in the emerging open source blockchain world.

### I will conveniently be in San Francisco in time for the conference, right before I relocate to Southeast Asia Feb 5th.

If you are looking for extra hands during the conference, I would love to volunteer. I have previously volunteered at the first [Talkabot Chatbot Conference](https://talkabot.ai/) and helped facilitate a hands-on teaching workshop for building chatbots. Conferences are where I go to get inspired and find new collaborators on projects.

## Thank you for opening up free tickets to developers! Would love to see some of the team in San Francisco!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jonchurch
