### ISSUE TITLE
I want to go to NEO Devcon: danielrakh@gmail.com

### ISSUE THREAD

**Issue by danrak** [neo-project/neo.org#143]
Hi I'm currently a developer at www.countup.io where we are currently exploring how can we use blockchain technologies to revolutionize the accounting industry. I would love to learn more about how we can work with NEO as the foundation for our project. Thanks : )

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @danrak
