### ISSUE TITLE
I want to go to NEO Devcon: xxx

### ISSUE THREAD

**Issue by inje** [neo-project/neo.org#144]
Hello, I'm Inje, a software engineer for [{Set} Protocol](https://www.setprotocol.com) and [Bcoin](http://www.bcoin.io). I'm working on creating a protocol that allows users to create collateralized baskets of tokens using smart contracts on the Ethereum blockchain. My partner Felix mentioned this in his post, and I'd like to restate: As more people create tokens on top of NEO, I believe there will be a strong need for protocol-level token abstractions - which {Set} is ready to solve. We've started with Ethereum, and want to build into NEO as well.

Here is the Set Protocol link:
https://github.com/setprotocol

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @inje

**Comment by inje** [comment]
@chenzhitong Thank you
