### ISSUE TITLE
I want to go to NEO DevCon! My email: veronica.coulombe@gmail.com

### ISSUE THREAD

**Issue by veronzHub** [neo-project/neo.org#145]
Hi my name is Veronica and i'm a female developer in San Francisco. 

This is my linkedin:
https://www.linkedin.com/in/veronicacoulombe/

I'm currently working on a private repo helping people compare crypto market caps to one another. I am also the Co-Founder of INRTracker.com, a health management tool for patients taking the blood thinner, Warfarin. The website is built in Ruby on Rails. I was responsible for the front end of the application and the internationalization efforts into German, French and Spanish.

I have been investing in crypto since 2013. 

I'm the creator of an open source responsive email framework: https://github.com/veronzHub/Responsive-Email-Framework

Most recently, I was a teaching assistant for the Rutgers Coding Bootcamp. In the past, I worked as a Developer for Promise Financial (an innovative loan start up), Barnes and Nobles and Experian.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @veronzHub
