### ISSUE TITLE
I want to go to NEO DevCon! My email: michael@lelantos.com

### ISSUE THREAD

**Issue by metaperture** [neo-project/neo.org#149]
I've spent the last four years as a statistical researcher in quant finance, and worked in SIGINT before that, with an undergrad focused in information theory from UCSD and a masters in OR (ish) from Stanford. I'm a member of the Block Collider core team.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @metaperture
