### ISSUE TITLE
I want to go to NEO DevCon! My email: naveensslackemail@gmail.com

### ISSUE THREAD

**Issue by palanisn** [neo-project/neo.org#151]
I'm the lead developer for Claimly - https://claimly.io/ and we are building a decentralized insurance ecosystem on Ethereum. I'm also working on other projects where I'm attempting to assess multiple blockchain protocols to pick the most suited implementation and NEO has come across as a strong competitor in many cases. I'd like to liaise with like minded folks from the world of NEO and I think this devCon would be a great place to do that.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @palanisn

**Comment by palanisn** [comment]
Thanks mate @chenzhitong !
