### ISSUE TITLE
I want to go to NEO DevCon! My email: alexandrag2254@gmail.com

### ISSUE THREAD

**Issue by alexandrag2254** [neo-project/neo.org#152]
Hi Neo team! I'm a developer in the bay area and would be interested in integrating Neo into future projects. Most recently, I've developed online educational content featuring Hyperledger frameworks: Fabric, Sawtooth, and Iroha. I'd like to attend this conference to learn more about Neo's potential.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @alexandrag2254

**Comment by alexandrag2254** [comment]
Thanks @chenzhitong!
