### ISSUE TITLE
I want to go to NEO DevCon! My email: michael@ferristocrat.com

### ISSUE THREAD

**Issue by ferristocrat** [neo-project/neo.org#155]
I am a consultant/developer working on a (currently private) cryptocurrency portfolio management solution. My experience is mostly in user-facing applications involving data visualization. Our team is currently looking into blockchain projects to integrate with our application a bit further into our development road map.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ferristocrat
