### ISSUE TITLE
I want to go to NEO DevCon! My email: hello@hemmi.anyalias.com

### ISSUE THREAD

**Issue by nobutakahemmi** [neo-project/neo.org#159]
Live in San Francisco, and would love to meet NEO enthusiasts, business people, innovators, and developers! I am currently aiming to be more exposed to the technology and how I can use it.

**Comment by chenzhitong** [comment]
You've contributed too little to the GitHub, and I'm not sure you're a developer. @nobutakahemmi

**Comment by nobutakahemmi** [comment]
Self-taught, but totally understand if the level is not there. @chenzhitong
