### ISSUE TITLE
I want to go to NEO DevCon! My email: martin@hallwest.com

### ISSUE THREAD

**Issue by hallwest** [neo-project/neo.org#161]
Long time engineering leader and entrepreneur focusing on digital media & advertising.

**Comment by chenzhitong** [comment]
You've contributed too little on the GitHub, and I'm not sure you're a developer. If your code is hosted elsewhere you can give me a link or screenshot.

**Comment by hallwest** [comment]
@chenzhitong here ya go
https://itunes.apple.com/us/app/stocko-value-investment-app/id1116464108?ls=1&mt=8

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @hallwest
