### ISSUE TITLE
I want to go to NEO Dev Con! My email: csggene3@gmail.com

### ISSUE THREAD

**Issue by csggene3** [neo-project/neo.org#162]
My name is Gene Davis III. I'm trying to convert myself from a miner and enthusiast to the dev I should have been long ago. I've worked on a couple of arbitrage bots, trade bots, and am currently trying to take over development of MCRN, MacronCoin; admittedly a shit coin, but one without a developer currently attached, and with the wallet down, it's an interesting project to give myself and see if I can accomplish something it seems like no one else is even trying. Even if I'm not good enough at the moment, maybe by the end of January I will be. =) Thanks ahead of time for consideration. I'm stacking NEO and GAS like a mad man, or a genius, however one might see it. Currently selling my truck to buy more NEO. Absolutely love it. Hope to see you all in SF. Thanks again. github - csggene3

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @csggene3

**Comment by cnahiman** [comment]
My name is Callixte, Nahimana. I am currently a Sr. SW with background in system programming, back-end and front-end. I just started investing into blockchain technology Programming so not much exciting projects that i have already built but it is a matter of time. I am hoping to use this as an opportunity to sky-rocket my future development, and work within the blockchain technology. I am so excited about all that the conference has to offer and i will take the rest from here on. 
Linkedin: https://www.linkedin.com/in/callixte-nahimana-90b33148/
Personal github: -nacali07

Thank you for your time.
