### ISSUE TITLE
I want to go to NEO DevCon! My email: ronfroh@gmail.com

### ISSUE THREAD

**Issue by ronfroh** [neo-project/neo.org#164]
Former stock trader, current NEO and NEP5 trader (almost 100% of portfolio). Blockchain enthousiast and aspiring developer.

**Comment by chenzhitong** [comment]
You Joined GitHub 2 hours ago?

**Comment by ronfroh** [comment]
Yes, that is correct. I am an aspiring developer (as shared in the intro above) and never had the need to use GitHub. I've been following the Basic Blockchain Tutorial to get a better understanding of how Blockchains work.

If the invite is for traditionally educated CS grads only, I understand. I'm not that person. What I bring to the table is trader knowledge in combination with self-taught understanding of low-level blockchain technology. I believe my trader background gives me a unique angle in the developer community, as I assume most developers don't have trading background.

Again, I totally understand if you prefer to invite traditionally educated engineers, but if you are interested in developers with a non-traditional angle, I'd be happy to join the conference in San Francisco.

Thanks in advance!

**Comment by chenzhitong** [comment]
Can you provide other links or screenshots that prove you are a developer? @ronfroh
