### ISSUE TITLE
I want to go to NEO DevCon! My email: wlwanpan@protonmail.com

### ISSUE THREAD

**Issue by wlwanpan** [neo-project/neo.org#165]
Hello, I am a full stack developer working for a healthcare platform company based in Vancouver, BC. My main focus is front-end js but recently got into smart contract development which I am learning on the side. I would love to join you guys for the DevCon and discover more in depth about the NEO dev community.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @wlwanpan
