### ISSUE TITLE
I want to go to NEO DevCon! My email : L.pradeep.jain@gmail.com

### ISSUE THREAD

**Issue by pradeep145516** [neo-project/neo.org#166]
I develop Android applications and blockchain evangelist.  Here is the link to the app that I had created and uploaded on Play store. https://play.google.com/store/apps/details?id=com.pradeep.vasooliManager . Hope to attend the Conference. Cheers!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @pradeep145516
