### ISSUE TITLE
I want to go to NEO DevCon! My email: mestresan@gmail.com

### ISSUE THREAD

**Issue by danielsan** [neo-project/neo.org#169]
I'm a software engineer with about 15 years of experience. I'm currently working with Big Data and machine learning. Lots of Scala with Apache Spark.

This is me:
* https://www.linkedin.com/in/santanadaniel/

Fun fact, I was also a speaker at a conference in San Francisco last year at the same place as this one
* https://youtu.be/RiTAcqf_Jiw?t=12m26s

I have no experience with blockchain development but that's where I aiming my career to.

I'm also a crypto investor and a fan of Neo.
In fact, NEO is one of the few that I sent to my nano ledger.
Too valuable to stay there with the exchange

**Comment by danielsan** [comment]
A simple feedback would be very useful.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @danielsan
