### ISSUE TITLE
I want to go to NEO DevCon! My email: krspjoseph@gmail.com

### ISSUE THREAD

**Issue by krsjoseph** [neo-project/neo.org#173]
My name is Krs Joseph the Lead Developer of the new Morpheus Wallet for NEO/GAS and other blockchain assets.

http://morpheuswallet.com/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @krsjoseph

**Comment by krsjoseph** [comment]
Thanks!
