### ISSUE TITLE
I want to go to NEO DevCon! My Email:pranjal.baweja@gmail.com

### ISSUE THREAD

**Issue by chessy404** [neo-project/neo.org#174]
I am a blockchain developer and cybersecurity consultant at Ernst & Young( EY) - Mumbai. I have worked in   technologies like Smart Contracts, ( Ethereum, Hyperledger) , IPFS, BigchainDB. I am good at javascript, python, android etc. 

One of the blockchain project I had worked on is the Blockchain based KYC platform. - https://github.com/knc331/Proffer2k17

As a part of EY, I have worked on multiple blockchain based use cases in sector such as supply chain, media etc.

**Comment by chenzhitong** [comment]
You contribute less on GitHub and I didn't see your commit or pull request in that project.

**Comment by chenzhitong** [comment]
You contribute less on GitHub and I didn't see your commit or pull request in that project of KYC. But you can use **knc331** account to application to prove your identity.
