### ISSUE TITLE
I want to go to NEO DevCon! My email: christianstone@hotmail.com

### ISSUE THREAD

**Issue by christianstone** [neo-project/neo.org#175]
Serial entrepreneur with over 15 years of entrepreneurship experience in the technology, education and manufacturing sectors. In 2010, I completed both a Master in Business Administration and a Master in Education, while in 2016 I completed my Ph.D. Management at Carleton University, Ottawa, Canada, with a focus on Entrepreneurship and Strategy utilising quantitative research techniques.

I’m a partner and business development manager of the new Morpheus Wallet for NEO/GAS and other blockchain assets. Morpheus allows you to send and receive NEO and other NEP tokens with popular currencies and tokens like Bitcoin, Litecoin, Monero Ethereum, ERC-20 tokens with more to be added soon. Below is a link to our Github repo and Twitter with a video of our wallet.

https://github.com/MorpheusWallet/beta/
https://twitter.com/MorpheusWallet/status/947562637180784640

Cheers,
Christian.

**Comment by chenzhitong** [comment]
You contribute less on GitHub and have no code. @krsjoseph @MorpheusAdministrator Is he one of the developers of your project?

**Comment by MorpheusAdministrator** [comment]
Hi @chenzhitong @christianstone is part of our team and it would be great to have him accompany me to DevCon to represent @morpheuswallet.

**Comment by christianstone** [comment]
Hello @chenzhitong. Thank you for your reply. I've recently joined the team as part owner and business developer for our amazing project. I will be leading the strategic elements of the project including monetizing the features of the app through integration with related dapps, strategic partnerships, marketing and networking with devs in the community. I'm excited to be a part of the team with developers @MorpheusAdministrator and @krsjoseph and look forward to being a part of the NEO DevCon. Many thanks in advance.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @christianstone

**Comment by christianstone** [comment]
Got the code and signed up for the event! Many thanks my friend. Very much looking forward to it. @chenzhitong
