### ISSUE TITLE
I want to go to NEO DevCon! My email: rishabh.sharma9102@gmail.com

### ISSUE THREAD

**Issue by rishabh2d** [neo-project/neo.org#177]
My name is Rishabh Sharma and I am a freshman at the University of California, Davis. I am majoring in Computer Science and Engineering and my GPA is 3.7 / 4.0. 
I am proficient in: C, C++, Java and very familiar with Kotlin, Swift, Solidity. 
I can also with ease use the following technologies: Android Studio, Xcode, Visual Studio, Adobe Photoshop, Git. 

I am working on a personal software with my team which connects the various steps in supply chain management of large companies with customers using the Blockchain technology and I am strongly interested in attending this conference to network with people alike and learn!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @rishabh2d
