### ISSUE TITLE
I want to go to NEO DevCon! My email: alban@visa.com  - Software engineer at Visa

### ISSUE THREAD

**Issue by meetingmeeting** [neo-project/neo.org#179]
Hi My name is Albert and I am a software engineer at Visa inc.
I am proficient in Java, and Kotlin for android, C# for server side dot net and Unity3d and build several Payment solutions for Visa inc for VR, AR, and android mobile.
I am a contributor to darkWallet for bitcoin on github as well. 
I am also proficient in Javascript and node js and built several ios and android apps in React native.
Also built several facial recognition and deep learning apps with dlib in c++ and python as well.
* I am on a few block-chain projects in Visa and would love to incorporate neo.
 Best regards,
- Albert
website: http://albertahn.com
linkedin: https://www.linkedin.com/in/albertahn/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. Welcome to join NEO DevCon. @meetingmeeting

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. Welcome to NEO DevCon.

**Comment by meetingmeeting** [comment]
Thanks!
