### ISSUE TITLE
I want to go to NEO DevCon! My email: techieanant@gmail.com

### ISSUE THREAD

**Issue by techieanant** [neo-project/neo.org#180]
Currently my key areas of interest are in: Frameworks like ReactJS, AngularJS, AR/VR Applications and Smart contract platforms like Ethereum, Neo and Lisk to name a few. 

I'm a Front End Developer by profession and my Github does not have a lot of contributions as I work on consulting roles where I'm bound by non disclosure agreements and hence cannot share any code in part or its entirety. I'm proficient with HTML5, ReactJS, AngularJS, TypeScript, Electrode on the front end side. Extensive experience working with web Servers like Apache Tomcat and Nginx, Scripting Languages like BASH and Perl, Database Tools like MongoDB and Elastic Search, Programming Languages such as C, C++ and Java and Testing Tools like Jasmine, Mocha, Chai and Selenium. 

In addition to being a Front End Developer professionally, I've been a technology enthusiast for more than a decade and I'm well versed in contrasting aspects of technology such as iOS and Android Application Development, Designing/Modeling using Adobe Photoshop and 3DS Max, Building/troubleshooting computer systems and penetration testing computer networks.

I'm actively working on writing smart contracts for Ethereum, Neo and Lisk platforms and would greatly appreciate the opportunity to attend the Devcon to meet like minded people.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @techieanant

**Comment by techieanant** [comment]
Thank you.
