### ISSUE TITLE
I want to go to NEO DevCon! My email: pdragozov@gmail.com

### ISSUE THREAD

**Issue by dragozov** [neo-project/neo.org#183]
I'm a software developer with over 19 years of programming experience and an experienced executive from the gaming industry, having led engineering teams in some of the largest gaming companies such as PopCap and EA. 

Currently, I serve as the CTO at Linekong US Inc, the American arm of Linekong (www.linekong.com), a Hong Kong public company and a major games developer from China. 
We are researching the use of blockchain and smart contracts for building the next generation of entertainment software and find Neo and it's ecosystem to be one of the most interesting and promising.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @dragozov

**Comment by dragozov** [comment]
Thanks a lot, @chenzhitong. See you at the conference!
