### ISSUE TITLE
I want to go to NEO DevCon! My email: liuhuac@g.clemson.edu

### ISSUE THREAD

**Issue by liuhuac** [neo-project/neo.org#184]
I am a software engineer at vmware. Before working in vmware I was a PhD student at Clemson University, doing researches related to resource management in cloud computing and distributed computing. I am developing my skill on blockchain development. Here is a link to my google scholar page https://scholar.google.com/citations?user=EpAmWoEAAAAJ&hl=en&oi=ao

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @liuhuac
