### ISSUE TITLE
I want to go to NEO DevCon! My email: rxc@umich.edu

### ISSUE THREAD

**Issue by r-x-c** [neo-project/neo.org#185]
I'm a graduating senior majoring in Computer Science at the University of Michigan and have devoted +70% of my free time (on top of course work time) to develop cryptocurrency/blockchain pertinent skills, because I believe the adoption of these technologies will forever change the world (like the internet and smartphones).

I've done coursework in distributed systems, operating systems, and currently web systems. Some projects include implementing paxos, sharding, primary-backup replication, and a kv storage project with fault-tolerant shard masters, and fault tolerant shard owners.

I'm ABC, looking to work in China eventually for full time because I believe I'll learn the most there, and work with the smartest engineers in the world. Although I'm young, it just means that I can stay up later and dedicate more time than others. I believe Neo is the future, and can certainly create a product superior to Ethereum, with more functionality, security, and speed.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @r-x-c
