### ISSUE TITLE
I want to go to NEO DevCon! My email: luke.tych@gmail.com

### ISSUE THREAD

**Issue by fusillijerry89** [neo-project/neo.org#187]
Hello. I have been a developer for about 8 years now. I am from Vancouver but try to make as many trips down to San Francisco as I can. I admit that I tried to ignore blockchain technology for as long as I could, but cannot ignore it any longer. Some of my favourite projects so far are Stellar, QLink, Neblio and DeepBrain Chain.

https://github.com/stellar
https://github.com/qlinkDev/qlink
https://github.com/NeblioTeam/neblio

Cheers,

Luke

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @fusillijerry89
