### ISSUE TITLE
I want to go to NEO DevCon! My email: inesrodrigues@ebonus.gg

### ISSUE THREAD

**Issue by InesCARodrigues** [neo-project/neo.org#189]
I'm a 23 years old computer engineer from Portugal. 
Co-founder and CEO of eBonus.gg (https://ebonus.gg). A platform with already more than 1 million users registered and visited by more than 2 Million gamers monthly. 

The last few months we have been studying blockchain and the benefits it would bring to our business. As a developer myself I'm also very interested in the development of smart contracts.

It would be a pleasure to attend to the NEO DevCon to network and learn more about NEO (in each I'm already heavily invested). 

Thank you.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @InesCARodrigues
