### ISSUE TITLE
I want to go to NEO DevCon! My email: abraham.paniagua@gmail.com

### ISSUE THREAD

**Issue by melatonin355** [neo-project/neo.org#190]
I am a developer for Microsoft in SF and have been attending the SF NEO meetups since day 1 and am very excited to connect with fellow NEO enthusiasts !  

Currently I am working on a few blockchain  apps on the ethereum network and am interested in converting them into the NEO platform. 

For Example:
An alternative to Hallmark Cards on the BlockChain
https://github.com/CryptoLove2018

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @melatonin355
