### ISSUE TITLE
I want to go to NEO DevCon! My email: cnahiman@visa.com

### ISSUE THREAD

**Issue by nacali07** [neo-project/neo.org#194]
My name is Callixte, Nahimana. I am currently a Sr. SW with background in system programming, back-end and front-end. I just started investing into blockchain technology Programming so not much exciting projects that i have already built but it is a matter of time. I am hoping to use this as an opportunity to sky-rocket my future development, and work within the blockchain technology. I am so excited about all that the conference has to offer and i will take the rest from here on.

Linkedin: https://www.linkedin.com/in/callixte-nahimana-90b33148/

Personal github: -nacali07 

Thank you for your time.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @nacali07
