### ISSUE TITLE
I want to go to NeO DevCon! My email marcodimonaco100@gmail.com

### ISSUE THREAD

**Issue by marcodm100** [neo-project/neo.org#195]
Hi,

this is Marco and I'm new into the blockchain environment. My field is Online Marketing and Communication working on new creative projects and technological innovation. I'm not exactly a developer :)  
I'm enthusiastic about blockchain as a new technology for future development and I have been following the NEO project for a while. 
It would be a great chance to be at Neo DevCon, sure that it will be an opportunity to know better the NEO platform and the team to evaluate if NEO blockchain technology could be suitable for new business opportunities. (I'm sure it will).

Many thanks for the opportunity :) 
Marco

**Comment by chenzhitong** [comment]
Sorry, the free tickets are only for developers who have contributed to the GitHub. @marcodm100
