### ISSUE TITLE
I want to go to NEO DevCon! My email: filip@dvorak.fr

### ISSUE THREAD

**Issue by Flamak** [neo-project/neo.org#196]
Hello, I am a research scientist interested in the efficiency of cryptocurrencies as platforms.

-- Bio (linkedin: [dvorak.fr](http://dvorak.fr))
Before joining PARC, Filip worked at Microsoft (Denmark), Google (US) and LAAS-CNRS (France), where he focused on planning, big data and developed a domain-independent planning system FAPE. He also engaged in digital entertainment, co-founding the software studio ark8, and developed several titles. Filip received his Ph.D., M.S., RNDr. and B.S. at Charles University, Prague, and was a postdoctoral fellow at University of Toronto. He has authored 13 conference papers and one journal publication.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Flamak

**Comment by Flamak** [comment]
Thank you.
