### ISSUE TITLE
I want to go to NEO DevCon! My email address is tomiokashuji@gmail.com

### ISSUE THREAD

**Issue by tomiokashuji** [neo-project/neo.org#197]
I am working on blockchain-related technology though unfortunately it cannot be disclosed as per my terms with my employer and confidentiality. 

I do look forward getting more involved in working within the NEO ecosystem and coming to SF to attend.

**Comment by chenzhitong** [comment]
You joined GitHub just now. Can you provide other links or screenshots that prove you are a developer? @tomiokashuji
