### ISSUE TITLE
I want to go to NEO DevCon! My email: tamnguye@usc.edu

### ISSUE THREAD

**Issue by thln** [neo-project/neo.org#198]
Hello, my name is Tam Henry Le Nguyen, and I'm a current software engineer at Adobe Systems in Silicon Valley. My LinkedIn profile can be found [here](https://www.linkedin.com/in/tamhenrylenguyen/). I graduated from University of Southern California with both a Bachelor's and Master's in Computer Science. I am currently working on iOS apps and am strong in Objective C, Swift, and Java. I would love to work with NEO (whether through iOS or through other types of projects) and make it more accessible to the public. Please let me know if you have any other questions.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @thln
