### ISSUE TITLE
I want to go to NEO DevCon! My email: alexgpark@gmail.com

### ISSUE THREAD

**Issue by alexgpark** [neo-project/neo.org#199]
Hello, my name is Alex Park, and I'm currently the Growth lead at [Detour](www.detour.com), an consumer augmented reality startup in San Francisco. Prior to this, I founded an online learning platform teaching creative and technical skills.

I have past experience in web (HTML/CSS/JS/Rails) and mobile (Swift/iOS) development, and I am interested in creating consumer applications and educational content around NEO. 

Recently, I have been learning Solidity/Truffle and have built several test contracts to become familiar with these new development workflows -> now working on a stealth project.

My LinkedIn profile can be found [here](https://www.linkedin.com/in/alexgpark).

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @alexgpark
