### ISSUE TITLE
I want to go to NEO DevCon! My email: kevin7@gatech.edu

### ISSUE THREAD

**Issue by finle** [neo-project/neo.org#200]
Hello! My name is Fin and have professionally worked in Silicon Valley as a jack of all trades software engineer anywhere from full stack API development, helping out with the CI/CD pipeline, to product support and troubleshooting.

I am working on my MSCS at the Georgia Institute of Technology where I am specializing in AI. I actually encountered the cryptocurrency world when I took a class on machine learning for trading which applies various machine learning approaches (decision trees, reinforcement learning, neural networks) and applies them to technical analysis to optimize trading and exit strategies.

I have since then been excited about blockchain technology, smart contracts, and how this all can disrupt existing industries and technology today. I plan to write my thesis research topic on some aspect of blockchain and cannot contain my passion!

My LinkedIn: [https://www.linkedin.com/in/kevinhle/](https://www.linkedin.com/in/kevinhle/)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @finle
