### ISSUE TITLE
I want to go to NEO DevCon! My email: tiffany.shiu.2@live.com

### ISSUE THREAD

**Issue by tjshiu** [neo-project/neo.org#201]
Hi my name is Tiffany! 

I am someone who just recently started buying bitcoins, and I am interested in block chain technology. I will be starting a coding bootcamp here soon in the San Francisco area in February, and I would like to gain any more knowledge I can about block-chain before I start. The most I have done has been some small projects at the University I have attended writing in java. I am just eager to learn more. 

My github is: tjshiu

**Comment by chenzhitong** [comment]
You contribute less on GitHub and have no code. Can you provide other links or screenshots that prove you are a developer? @tjshiu

**Comment by tjshiu** [comment]
Sorry about that! I just uploaded my first semester development projects in java. 
https://github.com/tjshiu/First_Java_Semester
I have also been working on javascript and ruby at home. I plan on being a software engineer by the end of the bootcamp, which ends in May. Please let me know if there is anything else I can provide. Thanks! @chenzhitong

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tjshiu
