### ISSUE TITLE
I want to go to NEO DevCon! My email: shyduchak@projectico.io

### ISSUE THREAD

**Issue by projectico** [neo-project/neo.org#202]
This is Stephen Hyduchak, Founder of ProjectICO. www.projectico.io 

My lead engineer, Andrew and I want to attend DevCon for our new project releasing in February. 

We have shared with Tony and Susu and looking forward very much to attending!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @projectico
