### ISSUE TITLE
I want to go to NEO DevCon! My email: tzoumichelle@gmail.com

### ISSUE THREAD

**Issue by mtzou** [neo-project/neo.org#203]
Hello. 

My name is Michelle Tzou. I recently graduated from University of Florida with a Bachelor's in Computer Science. I have had software engineering internships at Immersed Games and J.P. Morgan Chase; I currently work in the technology sector for a large financial company in New York. My experiences include mobile app development, machine learning related projects, and web application design. 
 
In my free time, I have been immersing myself into the world of cryptocurrency and blockchain development. I am Chinese and am a strong supporter of Chinese technologies. I believe NEO has the potential to change the world and I want to help it become more accessible to the public.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mtzou
