### ISSUE TITLE
I want to go to NEO DevCon! My email: ricochenx@gmail.com

### ISSUE THREAD

**Issue by ricochen** [neo-project/neo.org#204]
Hello! I am a full stack engineer, with strong experience in front end technologies such as React, Angular, JavaScript, and back end technologies with Node.js, SQL, NoSQL, and databases. I also am experienced writing unit and functional tests using jasmine, mocha, chai, sinon, and nightwatch.js. I've participated in a few hackathons and thought it was an awesome experience creating a project from scratch and coming up with the design and architecture.

Here is a project I worked on to create a Siri clone: https://github.com/ricochen/kirk
I think it's pretty cool :D
The instructions are in the repo to try it out.
Most of my GitHub activity are from last year (2016), this year I've been focused more on my new software engineer job at Yahoo.

I am currently learning more about cryptocurrency and blockchain technology, and heavily invest and believe in this movement. I'm planning on learning Solidity and working for a blockchain company in the near future and would love to attend the NEO devcon. Thank you!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ricochen
