### ISSUE TITLE
I want to go to NEO DevCon! My email: mhoang08@gmail.com

### ISSUE THREAD

**Issue by eexwhyzee** [neo-project/neo.org#206]
Hi, my name is Minh!

I am Research Scientist with over 3 years of experience working in the field of in-vitro molecular diagnostics,  over 2 years of experience as a statistician in NBA basketball, and have recently completed Udacity's Machine Learning Engineer Nanodegree. What draws me toward machine learning is its versatility and the ability to apply algorithms in pretty much any field. I am particularly excited about using computer vision and AI to develop laboratory workflows that move away from manual lab work to more autonomy. 

With the diagnostics industry moving towards next generation sequencing, one area that is a concern is the privacy of our personal human genome data and this is where the application of blockchain technology could be very intriguing as a means of decentralizing and securing the large amount of human genome data generated by high throughput sequencing. 

I would love to attend NEO DevCon to further learn from the great minds in the crypto space!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @eexwhyzee
