### ISSUE TITLE
I want to go to NEO DevCon! 

### ISSUE THREAD

**Issue by tsaiDavid** [neo-project/neo.org#207]
Would love to go to NEO DevCon:

- Work as a software engineer at a healthcare company in SF
- Experienced with the Javascript ecosystem - particularly love being engaged with the React community
- Passionate about open-source and giving back to the community, please see my GH (one has more than 400 stars!)
- Would love to translate and help make accessibility even easier

Looking forward to the developer conference!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tsaiDavid
