### ISSUE TITLE
I want to go to NEO DevCon! My email: alouiseq@gmail.com

### ISSUE THREAD

**Issue by alouiseq** [neo-project/neo.org#208]
I would love to attend the NEO DevCon to interact with the City of Zion community and learn more about blockchain, NEO platform, and cryptocurrency. Area of Development:

- work as a software engineer at a startup building enterprise software in the healthcare space
- experience in software languages such as HTML, CSS, Javascript, Python, C/C++, Perl
- expertise in front-end technologies and web technologies
- avid sports fan, programming, and learning crypto
- Github link: https://github.com/alouiseq

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @alouiseq
