### ISSUE TITLE
I want to go to NEO DevCon! My email: pododavid@hotmail.it

### ISSUE THREAD

**Issue by lrdavid** [neo-project/neo.org#211]
Hi, I'm a foot specialist podiatrist, I often deal with different types of people, and with all I can establish a relationship of esteem and trust, I think it's the most important thing in any job, I work in collaboration with other doctors and I'm able to handle any kind of problem in the best way, they are intuitive and willing. I believe that the blockchain world is a real revolution and that we will have much to receive us humans. I am very interested in the project. Greetings

**Comment by chenzhitong** [comment]
Young joined GitHub just now, the free tickets are only for developers who have contributed to the GitHub.  @lrdavid
