### ISSUE TITLE
I want to go to NEO DevCon! My email: dtsui@kyokan.io

### ISSUE THREAD

**Issue by sdtsui** [neo-project/neo.org#216]
I am a full stack software engineer. I have contributed to several blockchain projects, including MetaMask, ethereumjs-vm, and OSS libraries in the React ecosystem. 

A little rushed now for links on mobile, but most of these projects and other contributions can be seen on GitHub. Let me know if I can elaborate. Thank you.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @sdtsui
