### ISSUE TITLE
I want to go to NEO DevCon! My email: andrewvdp@gmail.com

### ISSUE THREAD

**Issue by AndrewVDP** [neo-project/neo.org#220]
I am a software/devops engineer with a passion for blockchain. I was introduced to Ethereum 3 years ago but my attention has shifted to NEO about 7 months ago. My development experience is building applications at scale in Node.js, javascript, MongoDB, docker and kubernetes. 

https://github.com/AndrewVDP/hodlen
https://github.com/AndrewVDP/ethereum-event-listener

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @AndrewVDP
