### ISSUE TITLE
I want to go to NEO DevCon! My email: jordan.jambazov@os.university

### ISSUE THREAD

**Issue by jordanjambazov** [neo-project/neo.org#221]
I am a full stack software developer and technology lead at the [Open Source University](https://os.university) project. We are developing the first learning & career development blockchain platform, that will allow people to register their skills and certifications on Ethereum and directly interact with businesses and academia. One of the reasons why me and my team would like to join NEO DevCon is to explore the opportunity to port the project to NEO.

GitHub organization: https://github.com/OpenSourceUniversity/
Website: https://os.university/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jordanjambazov

**Comment by jordanjambazov** [comment]
@chenzhitong Thanks for the promo code! I'm closing the issue.
