### ISSUE TITLE
I want to go to NEO DevCon! My email: sandeep@listenloop.com

### ISSUE THREAD

**Issue by sandeep45** [neo-project/neo.org#222]
I would love to attend the NEO DevCon to interact with the City of Zion community and learn more about blockchain, NEO platform, and cryptocurrency. Area of Development:

work as a software engineer at a startup building software in the advertising space
experience in software languages such as Ruby, JavaScript, Node
expertise in front-end technologies and web technologies like React
avid table tennis player, programmer, and blockchain enthusiast

Github link: https://github.com/sandeep45

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @sandeep45
