### ISSUE TITLE
I want to go to NEO DevCon! 

### ISSUE THREAD

**Issue by odubno** [neo-project/neo.org#224]
Hello, my name is Oleh and I am a Software Developer and a part time student in Columbia University. I work primarily with Python.
I started looking into Blockchain development and I love the fact that I can apply my Python knowledge to NEO development.
I would love to attend the conference and get more exposure into the community.
Very excited about this opportunity and would love to meet the team in person!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @odubno

**Comment by odubno** [comment]
Thank you!!!

**Comment by silentpower808** [comment]
Hello @chenzhitong I would like to drive to San Francisco from Utah to attend the NEO Devcon. as well, my email is jaysonshawver@gmail.com
