### ISSUE TITLE
I want to go to NEO DevCon!

### ISSUE THREAD

**Issue by wunderwuzzi23** [neo-project/neo.org#225]
Hi, I am a indie game developer and interested to build distributed games that leverage blockchain technology - been mostly looking at Ethereum so far, but just learned about NEO as well and it seems to offer an interesting dev platform. I don't have any code on GitHub, but you can see/play one of my games at: https://play.google.com/store/apps/details?id=com.johanndigitalworks.games.wonderwitches

Looking forward to learn more about NEO.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @wunderwuzzi23
