### ISSUE TITLE
I want to go to NEO DevCon! My email: mmoravec09@gmail.com

### ISSUE THREAD

**Issue by mmoravec** [neo-project/neo.org#226]
I am the CTO at www.thortoken.com. We are looking to be the first "NEO smart economy" company to come out of San Francisco. I am a city of zion member "mattmo" and contributed to the Lucky NEO open source project - https://github.com/mmoravec/luckyneo. All Thor development can be found here: https://github.com/thortoken. I've contributed to the neo-python CityOfZion project.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mmoravec
