### ISSUE TITLE
I want to go to NEO DevCon! My email: dinhjeffreyy@gmail.com

### ISSUE THREAD

**Issue by dinhjeffrey** [neo-project/neo.org#227]
My name is Jeffrey and I was a chemistry major. I became uninterested in chemistry and self-learned coding with the help of meet up communities (lots of allstars here). 

I am good at node.js, and am starting to get into python and c#

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @dinhjeffrey
