### ISSUE TITLE
I want to go to NEO DevCon! My email: 4cryptomining@gmail.com

### ISSUE THREAD

**Issue by ibleeve** [neo-project/neo.org#228]
I will be honest, I don't have much experience in blckchain so I am not involved in any GitHub blockchain projects.  However I am very interested in what NEO is doing and their plans for the future which is why I am dying to go to Neo DevCon.  Yes I may not be the best candidate as a blockchain developer, but I believe in the future of Neo and blockchain as a whole and want to be as educated as possible.  Thank you and I appreciate the time you took to read my application.  I want to go to NEO DevCon!

**Comment by chenzhitong** [comment]
Thank you for your attention and support for NEO. But the free tickets are only for developers who have contributed to the GitHub.  @ibleeve
