### ISSUE TITLE
I want to go to NEO DevCon! My email: jacobvo3@gmail.com

### ISSUE THREAD

**Issue by jay5266** [neo-project/neo.org#229]
Hi,

My name is Jacob Vo, I'm currently a software engineer at Workday in Pleasanton, CA. I work on the continuous integration side for building, testing, packaging and publishing RPMs. I work with many CI tools, like Bamboo, Docker, Ant, Gradle, AWS, Artifactory and Bitbucket. Here's my Linkedin -  https://www.linkedin.com/in/jacobvol I've been a strong supporter since Antshares!

Please let me know if you have any other questions.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jay5266
