### ISSUE TITLE
I want to go to NEO DevCon! My email: josephyao15@gmail.com

### ISSUE THREAD

**Issue by joyao10** [neo-project/neo.org#232]
Hi,

My name is Joseph Yao. I'm currently a software engineer working in Palo Alto. My main skills are in front-end development: HTML/CSS/Javascript. I've had some interest in creating apps on the NEO blockchain protocol and would like to learn more!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @joyao10
