### ISSUE TITLE
I want to go to NEO DevCon! My email: thebuzdar@gmail.com

### ISSUE THREAD

**Issue by alanbuzdar** [neo-project/neo.org#234]
I am Alan. I'm 23 and graduated with my Masters in Computer Science around 6 months ago. I work at Microsoft as an iOS developer but in my free time I like to write Smart Contracts for Neo and Ethereum.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @alanbuzdar
