### ISSUE TITLE
I want to go to NEO DevCon! My email: vbazarsky@gmail.com

### ISSUE THREAD

**Issue by vbazarsky** [neo-project/neo.org#239]
Hi, my name is Vlad.
I am a full stack engineer. 
have some ideas around blockchain technology and want to learn more about neo.
Currently work with SAP SuccessFactors as team/project lead and dev architect.
Linkedin profile www.linkedin.com/in/vladimirbazarsky

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @vbazarsky
