### ISSUE TITLE
I want to go to NEO DevCon! My email: mbenchim@mail.yu.edu

### ISSUE THREAD

**Issue by benchi10** [neo-project/neo.org#240]
I am working on a platform that connects students with cryptocurrency startups.
My goal is to pay the salaries of interns in exchange for cryptocurrency startups tokens.
Check out my MVP: http://stufound.tilda.ws/.
Thanks,
Menajem.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @benchi10
