### ISSUE TITLE
“I want to go to NEO DevCon! My email: cody.baray@pepperdine.edu

### ISSUE THREAD

**Issue by CryptoCody** [neo-project/neo.org#241]
I created an app called Crypto tracker bot and want to learn more about coding on the Neo platform. I have been in the crypto space a little over a year and I love the smart economy Neo is building. I am currently in college learning to code and want to spread more news about the community to my crypto society on campus.I hope to hear Da Hungfei and all other NEP 5 tokens speak at the conference.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @CryptoCody
