### ISSUE TITLE
I want to go to NEO DevCon! My email: nkehrlein@student.umuc.edu

### ISSUE THREAD

**Issue by nkehrlein** [neo-project/neo.org#242]
My name is Nicholas and I am a computer science student that is new to programming but not to blockchains.  I have followed Neo for a while and to me it represents a very mature vision of the smart economy and I intend to work in this space in the future.  I would love to attend the conference.

-Nicholas Kehrlein

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @nkehrlein
