### ISSUE TITLE
I want to go to NEO DevCon! My email: jhp524@nyu.edu

### ISSUE THREAD

**Issue by wheredidjupark** [neo-project/neo.org#243]
Hi Neo Devcon Team,

I'm Ju Park and I attend NYU studying computer science. I'm specialized in Node.js and I became heavily involved in cryptocurrency and blockchain after learning the power it could unleash. I'd like to learn more about blockchain and hopefully develop an app with the platform. I'm currently involved in a project called Ceta Network http://ceta.network Looking forward to what's coming for NEO!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @wheredidjupark
