### ISSUE TITLE
I want to go to NEO DevCon! My email: vdoan@mail.sfsu.edu

### ISSUE THREAD

**Issue by VanJose** [neo-project/neo.org#245]
Hi, I am a new incoming student to SFSU in CS. I am a fresh newbie to development, but I self-taught and took online courses while in high school. I hope to focus on Ruby, JavaScript, Node and of course, smart contracts on NEO. Once I graduate, I want to contribute to NEO development full-time.

Van Doan

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @VanJose
