### ISSUE TITLE
I want to go to NEO DevCon! My email: antonassocareer@gmail.com

### ISSUE THREAD

**Issue by antoncoding** [neo-project/neo.org#247]
### Hi, My name is Anton Cheng, and I'm an IT student from National Taiwan University(NTU). 

I've been investing in crypto and coding in smart contracts for more than a year, and I love it! For me, blockchain and all the other decentralized protocols are just amazing, and I can't wait to join a community where there're lots of experts and enthusiasts that helps me learn more. 

I'm not a professional developer now, but that's what I would like to become. I'm good at `C++`, `Javascript`, `Django` and `Python`(especially in Machine Learning).

Here' my first smart contract about a bidding platform. Hope you guys like it and feel free to leave a comment!
https://github.com/antoncoding/truffle_pisa/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @antoncoding
