### ISSUE TITLE
I want to go to NEO DevCon! My email: Mbaray@zagmail.gonzaga.edu

### ISSUE THREAD

**Issue by matt9394** [neo-project/neo.org#248]
I love NEO/ANTSHARES and all projects from onchain. I am in college studying CS and have my own miner in my dorm room. I love all NEP 5 projects Deepbrian, Apex, Ontology, and Elastos. I watched the Rong Chen and Da Hungfei SF meetup on youtube like 5 times. Neo will have the best smart economy in the next 5 years and it would be awesome to see them in Silicon Valley and the Dev Con

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @matt9394
