### ISSUE TITLE
I want to go to NEO DevCon! My email: maaz.uddin@berkeley.edu

### ISSUE THREAD

**Issue by MaazUddin11** [neo-project/neo.org#249]
My name is Maaz Uddin. I am a Senior studying Computer Science at UC Berkeley. Some areas of development I am good at are security and algorithm optimization.

The blockchain projects I am involved with are not on Github as they are more research based. I am currently working on the NEP-5 Token Standard with NEO as well.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @MaazUddin11
