### ISSUE TITLE
I want to go to NEO DevCon! My email: s0541821@htw-berlin.de

### ISSUE THREAD

**Issue by nyyn** [neo-project/neo.org#252]
Hey,

I'm a business computing student from Berlin / Germany. We don't have edu emails here. But HTW Berlin is a university and s0541821@htw-berlin.de is my student email.

I will be in LA to that time and would also love to live stream if possible!

HTW Berlin - University of Applied Sciences (http://www.htw-berlin.de)

Thanks a lot!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @nyyn
