### ISSUE TITLE
I want to go to NEO DevCon! My email: momchil.jambazov@os.university

### ISSUE THREAD

**Issue by Momchil-Jambazov** [neo-project/neo.org#256]
I am a software developer and creative technologist at the Open Source University project. We are developing the first learning & career development blockchain platform, that will allow people to register their skills and certifications on Ethereum and directly interact with businesses and academia. One of the reasons why me and my team would like to join NEO DevCon is to explore the opportunity to port the project to NEO.

GitHub organization: https://github.com/OpenSourceUniversity/
Website: https://os.university/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Momchil-Jambazov
