### ISSUE TITLE
I want to go to NEO DevCon! My email: gkelley@wisc.edu

### ISSUE THREAD

**Issue by gkelley** [neo-project/neo.org#257]
I am a senior studying computer science at the University of Wisconsin Madison. I have a unmatched passion for prototyping and operate a local Madison tech startup called AdItYourself. I would love the opportunity to go to NEO DevCon and share my passions for NEO and developing.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @gkelley
