### ISSUE TITLE
I want to go to NEO DevCon! My email: bmeyer@wharton.upenn.edu

### ISSUE THREAD

**Issue by bmeyer18** [neo-project/neo.org#259]
Hello,

I am deeply passionate about NEO and its approach towards developing a smart economy. I am looking to learn as much about the ecosystem and work on a NEO related project. I believe in the long term vision of NEO and its approach towards digital identity-backed smart contracts, ability to communicate with other blockchains through a cross-chain protocol, quantum resistant cryptography, and distributed storage protocol and secure communication protocol.  and would like to use everything I have learned in business school (my major is international business development) to further it. I would like to fly out from the east coast to attend and join the NEO community.

Best,
Ben

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @bmeyer18
