### ISSUE TITLE
I want to go to NEO DevCon! My email: smnomaan@utexas.edu

### ISSUE THREAD

**Issue by smnomaan** [neo-project/neo.org#260]
Hi,

I am a Ph.D. student at the University of Texas at Austin. I am looking to learn as much about the NEO ecosystem. I have a special interest in Trinity state channel. I would be grateful if I get a chance to visit the NEO DevCon.

Thanks.
Nomaan

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @smnomaan
