### ISSUE TITLE
I want to go to NEO DevCon! My email: ntalcus@berkeley.edu

### ISSUE THREAD

**Issue by ntalcus** [neo-project/neo.org#262]
I am a developer at Blockchain at Berkeley and while I’ve only worked with Ethereum in terms of smart contracts I’m excited for the opportunity to learn more about the NEO system. I’ve read quite a bit about NEO and I appreciate the approach NEO has taken to create a feasible digital economy as opposed to just a system of smart contracts. With the opportunity to attend, I would almost certainly work more towards developing on NEO and work to introduce my fellow blockchain devs at Cal to NEO as well. Thank you and best of luck with the conference!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
