### ISSUE TITLE
I want to go to NEO DevCon! My email: mjs7506@psu.edu

### ISSUE THREAD

**Issue by mpascotti** [neo-project/neo.org#265]
Hi I am an "adult" learner at the old age of 26. I have experience in the startup space and am returning to school to study economics while working through self learning on free code camp. I am a major believer in NEO's contribution in the future to  smart contracts/digital identity on a global scale. I don't have any past blockchain projects, but this is where I am looking to head while/post university. 

Malcolm

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mpascotti
