### ISSUE TITLE
I want to go to NEO DevCon! My email: robot2@u.washington.edu

### ISSUE THREAD

**Issue by garlee** [neo-project/neo.org#266]
Hello,

I am very interested in attending NEO devcon because of my passion for governance and security. Have been mining and owning many different types of tokens and understanding the network effect of the NEO technology.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @garlee

**Comment by garlee** [comment]
@chenzhitong I haven't received. Could you try garlee@gmail.com?

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your gmail mailbox, please check your mailbox. @garlee
