### ISSUE TITLE
I want to go to NEO DevCon! My email: leland_lee@berkeley.edu

### ISSUE THREAD

**Issue by lelandlee** [neo-project/neo.org#267]
Hi!
I'm Leland, currently studying cognitive science / computer science at UC Berkeley. I help lead a group called Blockchain at Berkeley focusing on our external projects. Although in the past our contracts have been in Ethereum, increasing some of our clients our looking for us to build in NEO. I'm decentish at [data visualization](bl.ocks.org/lelandlee).

Most of my work tends to be analysis like [Quantifying Decentralisation](https://news.earn.com/quantifying-decentralization-e39db233c28e)

Thanks,
Leland

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @lelandlee
