### ISSUE TITLE
I want to go to NEO DevCon! My email: nyyn1234@gmail.com

### ISSUE THREAD

**Issue by nyyn** [neo-project/neo.org#268]
Hey guys, i'm done with studying computing in Berlin and work as Salesforce Administrator / Coder. I'm thinking about changing fields and build an dAPP on the NEO Blockchain.
I will be in SF around to visit some family and would love to participate.

Thans a lot!

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @nyyn
