### ISSUE TITLE
I want to go to NEO DevCon! My email: xz2li@uwaterloo.ca

### ISSUE THREAD

**Issue by movefast** [neo-project/neo.org#269]
Hi,
My name is Derek Li and I'm a math & computer science student at the University of Waterloo. I'm proficient in python, c++, and React JS and I've had 5+ years of experience in web backend, mobile, and distributed system development. I've done a price analysis on Bitcoin recently(https://github.com/movefast/crypto_exploration/blob/master/bitcoin_price_analysis.ipynb) and just get started on building Dapps. As a Chinese student, I couldn't be more supportive in the initiative of NEO and am very passionate about the prospect of building Dapps on Neo in any language compared to solidity and would love to learn more. I'm really excited to hear about the upcoming NEO DevCon and I hope to meet the NEO developers and other engineers currently working in the space and together learn more about opportunities in building NEO Dapps or even contributing to the core project itself!

Thanks for your time & consideration!
Derek

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @movefast
