### ISSUE TITLE
I want to go to NEO DevCon! My email: danyotam@amazon.com

### ISSUE THREAD

**Issue by yotamdarash** [neo-project/neo.org#270]
I'm an Amazon backend SDE mostly working with Hadoop for analysis of Amazon music user usage metrics, Java for backend services and Python for internal validation tools.  I am currently working on a website to allow users to buy space on a virtual matrix using ether.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @yotamdarash
