### ISSUE TITLE
I want to go to NEO DevCon! My email is eric.tu@uwaterloo.ca

### ISSUE THREAD

**Issue by tueric** [neo-project/neo.org#271]
I am a CS and math student at the University of Waterloo. I've been into blockchain for over a year now and I develop on Ethereum. I would like to go to the NEO DevCon so that I could explore the differences between both ecosystems and see what I can learn from both.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tueric
