### ISSUE TITLE
I want to go to NEO DevCon! My email: x6fu@berkeley.edu

### ISSUE THREAD

**Issue by 2leifu** [neo-project/neo.org#273]
Hi,

I'm Lauren, a first-year MBA student at UC Berkeley and a Consultant at Blockchain at Berkeley.

I have over 4 years of experience in investment banking, mostly focused on securitization. 
I’m excited about NEO and I want to explore the possibility of using blockchain to redesign and streamline the securitization lifecycle. 

The securitization market in the US alone is over 10 trillion dollars. However, the infrastructure underpinning this massive market hasn’t changed much since inception over 50 years ago. The players in the space have implemented band-aid solutions in isolation. As such, the current ecosystem is extremely manual, prone to error, fragmented, and opaque. 

I would love to attend NEO DevCon to further learn and see how we can restructure the securitization ecosystem.

Regards,
Lauren

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @2leifu
