### ISSUE TITLE
I want to go to NEO DevCon! My email: ianhunter@gmail.com

### ISSUE THREAD

**Issue by ian** [neo-project/neo.org#274]
I'm largely a fullstack developer, previously Rails/Ruby, now Node.  I prefer to do everything in React frontend.  Lots of experience on AWS.

Building a multi-exchange trading platform now, and of course mining like crazy.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ian
