### ISSUE TITLE
I want to go to NEO DevCon! My email: surya@berkeley.edu

### ISSUE THREAD

**Issue by ssendyl** [neo-project/neo.org#275]
My name is Surya. I'm a current master's student at UC Berkeley's School of Information, former data scientist at Mattermark, and former intern at Orbital Insight. I'm good at data science and machine learning. I'm excited about bringing these skills to blockchain development. 

I've done some work writing solidity smart contracts here: https://github.com/ssendyl/surya_data-x-f17/tree/master/08-blockchain-and-sql/hw-solidity-in-depth

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ssendyl
