### ISSUE TITLE
I want to go to NEO DevCon! My email: jasonyli@gmail.com

### ISSUE THREAD

**Issue by jasonyli** [neo-project/neo.org#279]

**Comment by jasonyli** [comment]
Seasoned developer in Silicon Valley, veteran startup-er.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer? @jasonyli

**Comment by jasonyli** [comment]
Is there a private email I can send you my LinkedIn profile? I don't want it to be public here. Interest in neo/crypto currency is just my part time hobby. Not related to my employer.

**Comment by chenzhitong** [comment]
chenzhitong12@hotmail.com @jasonyli
