### ISSUE TITLE
I want to go to NEO DevCon! My email: stang84@gatech.edu

### ISSUE THREAD

**Issue by Thescuba** [neo-project/neo.org#280]
I am currently an MS student at Georgia Tech with skills in data visualization, machine learning and computer vision. I am really excited about having blockchain tech applied to the current technology and how game theory, economics and ai will all mesh together to solve current problems.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Thescuba
