### ISSUE TITLE
I want to go to NEO DevCon! My email: willhellis@gmail.com

### ISSUE THREAD

**Issue by idefen1** [neo-project/neo.org#281]
Hi, my name is Will and I'm the lead iOS / Node.js developer for the app Crypto Tracker Bot (currently Top 50 on the App Store's Top Charts - All Categories & currently No. 13 on the Android Charts for New Paid Apps). Our team would love to join you at the conference. 

Links to the app: 
[iOS App Link](https://itunes.apple.com/us/app/crypto-tracker-bot/id1320756750?mt=8)
[Android App Link](https://play.google.com/store/apps/details?id=com.lwbrands.android.cryptotrackerbot)

![ios](https://user-images.githubusercontent.com/9583038/34897142-78101710-f7a1-11e7-8129-7c8f0b728d29.jpg)
![android](https://user-images.githubusercontent.com/9583038/34897147-7d991506-f7a1-11e7-80bf-a97c456eefa2.jpg)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @idefen1
