### ISSUE TITLE
I want to go to NEO DevCon! My email: danny@deds.co

### ISSUE THREAD

**Issue by dannyelkhoury** [neo-project/neo.org#283]
Hey my name is Danny Elkhoury but I would like to send my founder, JASON GEORGE CHEBAT to Neo DevCon if that is possible!

GitHub Repo:
https://github.com/verifyeddotcom/verified-prod
https://github.com/verifyeddotcom/app

Thank you in advance

**Comment by chenzhitong** [comment]
This links are 404. @dannyelkhoury
