### ISSUE TITLE
I want to go to NEO DevCon! My email: donBsage@yahoo.com

### ISSUE THREAD

**Issue by CryptoDS3** [neo-project/neo.org#284]
I am a crypto App developer for iOS and Android.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @CryptoDS3

**Comment by CryptoDS3** [comment]
Hi there,

I am part of the team that developed Crypto Tracker Bot App for iOS and Android:

![ctb_logo_1024](https://user-images.githubusercontent.com/35384733/34968993-6ed3f982-fa21-11e7-87ff-285ab0796940.png)
https://itunes.apple.com/us/app/crypto-tracker-bot/id1320756750?ls=1&mt=8

Unfortunately I am not a student so I don't have a .edu email address.  Also, everyone else on our App development team was able to get tickets:

- Will Ellis
- Cody Baray
- Nathan Udomsri

... so I was really hoping to be able to attend this along with them!

thx,
Don

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @CryptoDS3
