### ISSUE TITLE
I want to go to NEO DevCon! My email: Azngangsta@gmail.com

### ISSUE THREAD

**Issue by MechJosh0** [neo-project/neo.org#286]
I'm a full stack systems developer for private education institutions where we build internal platforms for our clients and their users. My main languages are php and javascript, with experience with React and vue js.

I don't have any blockchain experience as of yet but I'm looking to get involved somehow.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @MechJosh0
