### ISSUE TITLE
I want to go to NEO DevCon! My email: tonghao126@gmail.com

### ISSUE THREAD

**Issue by tonghao126** [neo-project/neo.org#287]
Hi, I am senior data scientist in a mobile game company in Manhattan. I am just started with development in NEO and look forward to learn more about it in Dev Con. I personally hold a bunch of NEO and have been watching NEO since last June.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tonghao126
