### ISSUE TITLE
I want to go top Neo DevCon! My email: omocal4u@hotmail.co.uk

### ISSUE THREAD

**Issue by omofra4u** [neo-project/neo.org#288]
My Name is Samuel Francis Odihiri and I am very good at developing in the .Net languages. Although, I have not been actively involve in blockchain projects, I believe attending this DevCon will provide me with the tool to contribute immensely to the Neo project.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @omofra4u
