### ISSUE TITLE
I want to go to NEO DevCon! My email: alexisgauba@berkeley.edu

### ISSUE THREAD

**Issue by alexisgauba** [neo-project/neo.org#289]
I'm Alexis, an undergraduate studying Electrical Engineering and Computer Science at UC Berkeley. I am a developer and researcher with Blockchain at Berkeley. I won Gnosis' $1500 prize at CalHacks for [this project](https://github.com/alexisgauba/Gnosis-Privacy-Token-Prediction-Market), worked on [Humanitas](https://github.com/nadir-akhtar/ethereal-2017), a blockchain marketplace to align incentives between parties, and [Radus](https://github.com/AdityaSripal/RadusICO), a sustainable crowdsale model. I have also done research on Proof of Stake and have been talking to NEO about potential research for both NEO and Ontology. Looking forward to DevCon!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @alexisgauba
