### ISSUE TITLE
 I want to go to NEO DevCon! My email: ehdyn81@gmail.com

### ISSUE THREAD

**Issue by ehdyn** [neo-project/neo.org#290]
My name is Ryan Dean, I mainly use visual programming languages for many years such as Max/MSP/Jitter, Reaktor, Touch Designer, etc... for developing innovative sequencers, synthesizers and effects with functions and capabilities that are not available from any commercial  products. I've not yet been a developer on any blockchain projects, but have a deep theoretical understanding of the prevalent methods in use right now and would like to become much more deeply involved in dApp development, especially relating to synthesizers and digital audio environments. My main specialty is physical modelling and modal synthesis.

Thank you for your consideration!

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?

**Comment by ehdyn** [comment]
Hello! Yes, sorry I was always working privately towards commercial apps so wasn't ready to share.. below are some basic examples.. mostly I specialize in Chaos, Simulation, Sequencing, Graphics, etc... but very excited to get into Neo.

Hope this gives some idea!

![ehdyn-linearfeedbackshiftregister](https://user-images.githubusercontent.com/35385436/34957640-72b5fa48-f9fc-11e7-952d-545d9502dfe0.png)

![ehdyn-impulsetraingenerator](https://user-images.githubusercontent.com/35385436/34957645-7b17a786-f9fc-11e7-9c19-d093300fd608.png)

![ehdyn-chirikovmap](https://user-images.githubusercontent.com/35385436/34957650-804ff97e-f9fc-11e7-94b9-2c6d72febac8.png)

![ehdyn-basisfunctiongenerator](https://user-images.githubusercontent.com/35385436/34957654-836a3bba-f9fc-11e7-8747-43e22b0cfc5e.png)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @ehdyn
