### ISSUE TITLE
I want to go to NEO DevCon! My email: sustarich@engineering.ucsb.edu

### ISSUE THREAD

**Issue by jesssustarich** [neo-project/neo.org#291]
I'm a graduate student at UCSB working on a project that computes crystallographic  protein structures using parallel computing, and am looking into how block chain technology could interface with similar calculations.

Thanks! Jess

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jesssustarich
