### ISSUE TITLE
I want to go to NEO DevCon! My email: eliott.atlani@berkeley.edu

### ISSUE THREAD

**Issue by BillyEliott** [neo-project/neo.org#292]
Hi! I'm a graduate student in Systems Engineering at UC Berkeley. Currently working on several blockchain related projects including the Sweetbridge protocol: https://bitbucket.org/sweetbridge/ https://sweetbridge.com/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @BillyEliott
