### ISSUE TITLE
I want to go to NEO DevCon! My email: jkhat@amazon.com 

### ISSUE THREAD

**Issue by theonlyjames** [neo-project/neo.org#293]
I've been experimenting with building DAPPs using ETH, Experimented creating an ERC20 Compliant token and test launched an ICO. I'm currently part of an "experimental" group at AMAZON AWS. I'd love to come check out the conference 🥇  💯  💯  💯  💯 💯  💯 💯  💯

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @theonlyjames
