### ISSUE TITLE
 I want to go to NEO DevCon! My email: vmohan2211@gmail.com

### ISSUE THREAD

**Issue by vmohan7** [neo-project/neo.org#294]
Virtual Reality Developer. Have a [Youtube Channel](https://www.youtube.com/fuseman) where I have done weekly tutorials teaching people how to develop for VR. Currently looking into Crypto / Blockchain as an area to add to our Youtube channel to teach more developers.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @vmohan7
