### ISSUE TITLE
I want to go to NEO DevCon! My email: nurakhchina@berkeley.edu

### ISSUE THREAD

**Issue by cctToken** [neo-project/neo.org#295]
Hello, my name is Nataliya Urakhchina. CS student at UC, Berkeley. I am a C++ developer. Currently working with smart contract development. I am also in the process of releasing my own crypto token: CCT Token. https://github.com/cctToken/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @cctToken
