### ISSUE TITLE
I want to go to NEO DevCon! My email: bradyjo@grinnell.edu

### ISSUE THREAD

**Issue by bradyjoh** [neo-project/neo.org#296]
Looking at this conference, this seems like something I'd be very interested in! I loved following along with Dogecoin, Bitcoin, and other blockchain-related events and would love to go to an event solely focused on it. Ethereum seems to be all the rage these days so I would love to get more details. Thanks for your consideration!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @bradyjoh
