### ISSUE TITLE
I want to go to NEO DevCon! My email: david.julian@student.oaklandcc.edu 

### ISSUE THREAD

**Issue by JUBANANAS** [neo-project/neo.org#297]
I am a software developer for nasa. Father of VRsports competitive gaming on the block chain. I create apps from scratch. I invented KFC.

**Comment by chenzhitong** [comment]
Can you honestly introduce yourself? @JUBANANAS

**Comment by JUBANANAS** [comment]
Sorry im not an interesting person. I just wanted to learn more about neo i
am currently holding 15 neo. 8000 DeepBrainChain. I just got out of
probation so i thought it would be cool to go see you guys and learn more
about my favorite blockchain..

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @JUBANANAS
