### ISSUE TITLE
I want to go to NEO DevCon! My email: trungt@uw.edu

### ISSUE THREAD

**Issue by trungt19** [neo-project/neo.org#298]
I am a senior at the University Of Washington majoring in Computer Science. Throughout my college journey, I have taken much interest into how software development can ultimately transform the world that connects us around the world. My qualifications include software development in Java, C, some python while learning fundamentals topics of data structures and algorithms.

My passion for technology has taken an alternate route into blockchain technology & the development of NEO's smart economy. I hope to be chosen as a candidate to be a part of this movement and will look forward to contribute to NEO and their ambitious vision. 

Best Regards,
Trung Thai

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @trungt19
