### ISSUE TITLE
Typos 

### ISSUE THREAD

**Issue by flavoredtaco** [neo-project/neo.org#3]
1) 
> Use digital certicate to guarantte trust
>   
  
Should be:  
  
> Use digital *certificate* to *guarantee* trust
>   
  
2)  
  
> Digital certificate is supported, allowing for trust for public chain.With digital certificate, the assets on blockchain becomes legally protected.  
  
Should be:  
  
> Digital certificate is supported, allowing for trust for public *chain. With* digital certificate, the assets on blockchain become legally protected.  
  
3)  
  
> Turing-complete smart contract, which will have high certainty and finality, support parallel operation,sharding and unlimited scalability when run in AVM.  
  
Should be:  
  
> Turing-complete smart contract, which will have high certainty and finality, support parallel *operation, sharding* and unlimited scalability when run in AVM.  
  
4)  
  
> NeoContract support programming languages such as C #, Java, and go,  developers can rapidly develop smart contracts based on the NEO without learning a new language.  
  
Should be:  
  
> NeoContract *supports* programming languages such as C #, Java, and go,  developers can rapidly develop smart contracts based on the NEO without learning a new language.  
  
5)  
  
> The innovative dBFT consensus mechanism,which guarantees transactions' finality and stability, on conditioned that less than 1/3 of nodes show Byzantine problems.  
  
Should be:  
  
> The innovative dBFT consensus *mechanism, which* guarantees transactions' finality and stability, *on condition* that less than 1/3 of nodes show Byzantine problems.  
  
6)  
  
> Antshares project initiated,seed-round fund received  
  
Should be:  
  
> Antshares project *initiated, seed*-round fund received  
  
7)  
  
> Antshares started on Github as an real time open source project  
  
Should be:  
  
> Antshares started on Github as *a real* time open source project  
  
8)  
  
> Antshares recruit more talents including Tony Tao, Secretary General of NEO Council  
  
Should be:  
  
> Antshares *recruits* more talents including Tony Tao, Secretary General of NEO Council  
  
9)  
  
> Second phase global ICO with 6119 btc raised  
  
Should be:  
  
> Second phase global ICO with 6119 *BTC* raised  
  
10)  
  
> ANS available on yunbi,yuanbao,19800,bittrex  
  
Should be:  
  
> ANS available on *Yunbi, Yuanbao, 19800, Bittrex*  
  
11)  
  
> Februari  
  
Should be:  
  
> *February*  
  
12)  
  
> nestfund.io, the official website of Nest,an Antshares-based Smart fund launched  
  
Should be:  
  
> nestfund.io, the official website of *Nest, an* Antshares-based Smart fund launched

**Typo fixes by [/u/zz25zz on Reddit](https://www.reddit.com/r/NEO/comments/6si2g0/new_website_neoorg_has_typos_please_fix_them/)**

**Comment by Yamakaza** [comment]
Another typo can be found in Technology section (Lattice cryptology-quantum computer-proof technology) "Introduced Lattice cryptography-based signing and encryption **techinique**"
Should be: technique
