### ISSUE TITLE
I want to go to NEO DevCon! My email: aparnakr@berkeley.edu

### ISSUE THREAD

**Issue by aparnakr** [neo-project/neo.org#300]
I am a CS major at Berkeley and have taught a [blockchain fundamentals](https://blockchain.berkeley.edu/decal/fa17/fund/) course. I have worked on [crypto economics - proof of stake research ](https://github.com/aparnakr/casper)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @aparnakr
