### ISSUE TITLE
I want to go to NEO DevCon! My email: robin.allemand@gmail.com

### ISSUE THREAD

**Issue by robinho321** [neo-project/neo.org#301]
My 9-6 is at a tech company in SF, and my hobbies include cryptocurrency research, iOS Development, and translation -- English, French, Mandarin Chinese, and Spanish. I'd love to go to NEO DevCon!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @robinho321
