### ISSUE TITLE
I want to go to NEO DevCon! My email: yc@berkeley.edu

### ISSUE THREAD

**Issue by mkchungs** [neo-project/neo.org#304]
I'm a blockchain protocol developer for an ethereum project. Currently researching on alternative consensus protocol. I came across Neo's dbft when I was studying dpos. Would like to learn more about Neo/Gas ecosystem and its smart contract platform.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mkchungs
