### ISSUE TITLE
I want to go to NEO DevCon! My email: delilonia@gmail.com

### ISSUE THREAD

**Issue by delilonia** [neo-project/neo.org#305]
I am a medical student and a cryptocurrency lover with a minimum of two years of experience. In fact I am pretty into and have been working for projects right from their early developmental stage till they become established. I am also an active user of steemit platform to add to this. My Github block chain links activities are:
https://github.com/innovacoin/innova
https://ethereumproject.github.io/etherwallet/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @delilonia
