### ISSUE TITLE
I want to go to NEO DevCon! My email: ahester2@gmu.edu

### ISSUE THREAD

**Issue by ahester2** [neo-project/neo.org#306]
My name is Allen Hester and I am currently working at NGO Xchange, a platform aimed at helping non-profits leverage the speed, security, and transparency of block chain.

Our white paper will be releasing sometime next week, but we are currently considering different platforms to be the underlying blockchain for NGO Xchange. We are already in some conversation with members of Neo about it being our potential choice. I am personally a big advocate for neo and I believe meeting others who are developing projects off Neo at Neo devcon would be really bennificial and enlightening for NGO Xchange.

http://www.ngoxchange.com

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ahester2
