### ISSUE TITLE
I want to go to NEO DevCon! My email: lhuynh11@jhu.edu

### ISSUE THREAD

**Issue by lahuynh** [neo-project/neo.org#307]
I finished undergrad in CS at university. Continuing my studies at JHU. Programming languages i know: C++, Java, Python, Web Development. I've been into crypto for a while now. I am a student looking to learn more about blockchain development. My friends and I are looking into making our own coin, but i've been doing research on these things. I would like to go to Neo DevCon to learn more :) I've worked on many programming projects, but aren't related to blockchain tech yet. If interested, i can provide links to it. Hoping to really go!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @lahuynh
