### ISSUE TITLE
I want to go to NEO DevCon! My email: tpn025@ucsd.edu

### ISSUE THREAD

**Issue by tnguyen2018** [neo-project/neo.org#308]
I am a bioengineer, but have experience in coding with matlab, python, java, and html. I've been interested in crypto and would like to go. A website containing one of my project can be access at http://envision-piccolo.herokuapp.com.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tnguyen2018
