### ISSUE TITLE
I want to go to NEO DevCon! My email: jreyna91@g.ucla.edu

### ISSUE THREAD

**Issue by jreyna91** [neo-project/neo.org#309]
Engineer and programmer with experience coding in Java, Python, and VBA. Currently taking computer science courses. Involved in Android/iOS projects related to blockchain space. Actively learning how to develop apps on Neo Platform.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jreyna91
