### ISSUE TITLE
I want to go to NEO DevCon! My email: vishesh@berkeley.edu

### ISSUE THREAD

**Issue by visheshmehta** [neo-project/neo.org#310]
I am Vishesh, a third-year undergraduate student from India studying Economics and Development Studies at UC Berkeley. I am a business consultant and researcher at Blockchain at Berkeley, with experience in cryptoeconomics and crowdsale design for ICOs. I have worked at [Sacred Capital ](https://sacred.capital/#/) conducting financial analysis on cryptocurrencies and leading research on blockchain innovations for governments and the social sector. I work with the cryptoeconomics team at Berkeley, which is potentially collaborating with Neo for research. Really excited for DevCon!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @visheshmehta
