### ISSUE TITLE
I want to go to NEO DevCon! My email is 13ljm9@queensu.ca

### ISSUE THREAD

**Issue by lucasmanuel1996** [neo-project/neo.org#312]
Hi there!

My name is Lucas Manuel and I am a fourth year student from Canada that founded our university's first blockchain club: Queen's Blockchain Innovation Community. I work as the Chair of Blockchain Adoption, and run lectures on topics such as fog computing, different consensus algorithms, how to trade different cryptocurrencies and keep them safe, smart contracts, and blockchain applications outside of cryptocurrency.

NEO is my by far favorite blockchain project currently, and I have invested over 90% in NEO since June (Antshares!). I have been an active Reddit contributor ever since then and would love to get involved in the ecosystem once I graduate. I am currently working in a group that has signed up for the NEO/Microsoft dev competition (I am proficient in Java, Javascript and Python) and would love the opportunity to attend this year's NEO DevCon.  

Feel free to check out my LinkedIn profile: https://www.linkedin.com/in/lucas-manuel/

Looking froward to hear your decision!

Lucas

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @lucasmanuel1996
