### ISSUE TITLE
I want to go to NEO DevCon! My email: minskiii@yahoo.com

### ISSUE THREAD

**Issue by Jupiter28** [neo-project/neo.org#313]

**Comment by chenzhitong** [comment]
Please write down a brief self-introduction and area of development you're good at. And write down links to GitHub blockchain projects that you are involved in. @Jupiter28

**Comment by Jupiter28** [comment]
Hello Neo Team,
My apology, I am not a developer. I am a student and would like to learn more about Neo and get expose to the project. I hope you can make get an exception for me to attend. Thank you in advance. Minski

**Comment by chenzhitong** [comment]
You can use the e-mail at the end of Edu and apply for student tickets. @Jupiter28

**Comment by Jupiter28** [comment]
Unfortunately, I am a drop out student, so I do not have an .edu email anymore. Minski

**Comment by chenzhitong** [comment]
If you have a student ID or other proof, you can send it to me. My email is chris@neo.org
