### ISSUE TITLE
I want to go to NEO DevCon! My email: chenjin79@gmail.com

### ISSUE THREAD

**Issue by PCSGH** [neo-project/neo.org#314]
I am a technical product manager at an investment bank. In the last eight years, I dedicated my time to developing cutting-edge technology solutions for the securities trading division. Through leading a team of business architects and software developers, I've become passionate about emerging technologies and products like blockchain and cryptocurrency. 

Although I don't personally write codes on a daily basis, I have a fairly good understanding of several computer languages (i.e. Javascript, Python, C++, learned at school & in my spare time), which allows me to discuss coding and algorithm with my technologists at length. I firmly believe in the idea of applying blockchain technology as the very tool to transform the landscape of banking and other critical infrastructure sectors. 

Prior to that, I studied Quantitative Finance in graduate school, and majored in Economics in college. Additionally, I attended an two-year honors program designed to foster entrepreneurship and leadership skills in technology and graduated from General Assembly as a certified product manager. 

I first met NEO team through an event held in NYC. I was fortunate to have the opportunity to speak to a few key members (i.e. Chen Zhao, Hongfei Da) about the team's mission and roadmap. I immediately became a fan. We have been in touch since. Recently I was looped in a few conversations about organizing NEO MeetUp events in the east coast and helping out in future events. I hope to further my contribution to this thriving community as a product evangelist and to meet more like-minded community members at the dev con event.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @PCSGH
