### ISSUE TITLE
I want to go to NEO DevCon! My email: brian@narrative.network

### ISSUE THREAD

**Issue by brianlenz** [neo-project/neo.org#316]
I have 17+ years of experience in software architecture and full-stack development including Java, SQL, MongoDB, JSP, HTML/CSS/JS. I'm CTO of [Social Strata, Inc.](https://www.socialstrata.com) and Narrative Limited, the company building [Narrative](https://www.narrative.network), the new Content Economy on the NEO blockchain. As CTO, I oversee every aspect of our technologies from IT and server infrastructure to software development. I am relatively new to blockchain (started 4 months ago). I originally worked on our Ethereum smart contract in Solidity: https://github.com/NarrativeNetwork/tokensale-smartcontract. We've since made the decision to switch to the NEO blockchain, so I am in the middle of porting our Ethereum smart contract to NEO (just getting started on that project now): https://github.com/NarrativeNetwork/tokensale-neo-smartcontract

I am super excited to be part of the NEO community and have started to engage in the NEO Discord, helping out as I am able.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @brianlenz
