### ISSUE TITLE
I want to go to NEO DevCon! My email: sullof@gmail.com

### ISSUE THREAD

**Issue by sullof** [neo-project/neo.org#317]
I am involved in many projects related with blockchain. Recently I am running [0xNIL](https://0xnil.org) ([github repo](https://github.com/0xNIL/initial-free-offering)),  with the idea of building the token on the Ethereum VM but from my tests it is very bad. So I am studying right now how to move it on Neo. The conference would be great to go deep in the Neo ecosystem :-)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @sullof
