### ISSUE TITLE
I want to go to NEO DevCon! My email: daniel@ischool.berkeley.edu

### ISSUE THREAD

**Issue by dandanbang** [neo-project/neo.org#318]
I am a Lecturer at UC Berkeley teaching full-stack development in the School of Information. Currently working as a data scientist full-time at Autodesk. I've been studying and investing blockchain for a while now and would really love to participate in this DevCon to contribute to the NEO community.

https://www.linkedin.com/in/wdanielchen/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @dandanbang
