### ISSUE TITLE
I want to go to NEO DevCon! My email: liuc@ohio.edu

### ISSUE THREAD

**Issue by drchangliu** [neo-project/neo.org#319]
I'm a researcher in software engineering. I'm interested in decentralized software applications such as Ethereum Smart Contracts. I'm also interested in NEO smart contracts and hope to learn more about the future direction of the NEO software infrastructure.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @drchangliu
