### ISSUE TITLE
I want to go to NEO DevCon! My email: zkoticha@berkeley.edu

### ISSUE THREAD

**Issue by zkoticha** [neo-project/neo.org#320]
I am a computer science and economics student at UC Berkeley. I am a Solidity dev with a strong interest in how blockchains will affect the financial space. I am head of cryptoeconomics research at Blockchain at Berkeley, and a member of research and development who is working with the NEO and Ontology teams on a couple of projects.

**Comment by chenzhitong** [comment]
Please write down a brief self-introduction and area of development you're good at. And write down links to GitHub blockchain projects that you are involved in. @zkoticha

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @zkoticha
