### ISSUE TITLE
I want to go to NEO DevCon! My email: dustin@alive5.com

### ISSUE THREAD

**Issue by alive5isthefuture** [neo-project/neo.org#323]
I am co-founder of alive5 and websitealive, a customer communications & loyalty platform looking to implement certain components on the blockchain. Currently trying to evaluate in parallel with Ethereum. We work with majority of all major league teams (NBA/NFL/NHL/MLB/NCAA) and other verticals that we see could benefit from our platform. Would also like to meet the team behind NEO.

Hope to see you in SF!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @alive5isthefuture
