### ISSUE TITLE
I want to go to NEO DevCon! My email: 295@holbertonschool.com

### ISSUE THREAD

**Issue by set808** [neo-project/neo.org#324]
Hello,

While i am not going to a traditional college I am a student at Holberton School in San Francisco. [Holberton School](www.holbertonschool.com) is a 2 year college alternative program for those that want to pursue a career in software development.  I've closely followed NEO from the days of Antshare. I've very early in my education, but my trajectory is geared towards blockchain development. I have considerable interest in NEO's smart contract technology and would love an opportunity to get more involved with the community. Blockchain is the future of our world and I want to be on the front lines once I finish school.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @set808
