### ISSUE TITLE
I want to go to NEO DevCon! My email: jdudman77@hotmail.com   

### ISSUE THREAD

**Issue by jdudman77** [neo-project/neo.org#325]
Please send two tickets one for myself and one for my lead developer.

jdudman77@hotmail.com
lcoopet@me.com

We are very excited to research the NEO platform for implementing a distributed business to business trade and transaction system with an international focus.  We intend to evaluate utilizing NEO contract and Digital certificates among other platform features. Both attending parties are grizzled software and business veterans  that have been involved at the founder/executive level in several successful start-ups with numerous industry awards.  We are looking forward to meeting the NEO Team!

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer? @jdudman77

**Comment by jdudman77** [comment]
Please see attached linked in profile (screenshot) for Larry Coopet:

![image](https://user-images.githubusercontent.com/35415407/34952874-02011a20-f9d0-11e7-97e5-f6f877049400.png)

**Comment by jdudman77** [comment]
II will be leading our efforts in this space, I have 30 years at the executive level in business development, product development/management and marketing in large and small technology companies (Jim Dudman) I have attached a screenshot of an early enterprise software project that I spearheaded, one of the first ever with legally acceptable digital signatures and identities for the pharmaceutical industry the product changed the way large pharma companies document and share research and protect their patents. It won scientific computing technical excellence award of the year.. there are many other award winninng projects that the two attendees have been involved with

. Please also see attached linked in profile (screenshot) for Larry Coopet:

**Comment by chenzhitong** [comment]
The 2 Promotional Codes has been sent to your mailbox (jdudman77@hotmail.com, lcoopet@me.com)
, please check your mailbox. @jdudman77

**Comment by jdudman77** [comment]
Thank you for the consideration!

I have not yet received the 2 codes in my inbox or in my junk maill files that are mentioned  below in your acceptance response.

can you please forward the codes again to my email @:  jdudman77@hotmail.com 



Best Regards
James Dudman
