### ISSUE TITLE
I want to go to NEO DevCon! My email: brandycamacho@gmail.com

### ISSUE THREAD

**Issue by bcamacho** [neo-project/neo.org#326]
I love this space! Neo is fantastic and I'm already playing around in my development sandbox. Still early in development stage as I'm learning by reviewing documentation and example source code. I would love to meet other NeoHeads :)  This will be a great conference!!!

Thank you,

Brandy

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @bcamacho
