### ISSUE TITLE
I want to go to NEO DevCon! My email: willyoo@wharton.upenn.edu

### ISSUE THREAD

**Issue by willyoo42** [neo-project/neo.org#327]
I am a student at The Wharton School researching cryptocurrencies and digital assets. I have developed applications with LRC and am advising a report on upcoming NEP5 tokens as well as decentralized exchange protocols. I am a full-stack developer as well. I've been studying and investing in NEP5 tokens as well as NEO/LRC for a while now and would really love to participate in this DevCon to contribute to the NEO community.

I am planning to meet with fellow developers at the conference.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @willyoo42
