### ISSUE TITLE
I want to go to NEO DevCon! My email: faizan10114@gmail.com

### ISSUE THREAD

**Issue by eff-kay** [neo-project/neo.org#328]
Hi, 

I have more than 3 years of experience working on Nuclues RTOS. Apart from that I also have strong web dev and android app dev experience, which I used to scratch my own itches every now and then. 

**I have been actively involved in the community, developed a few failed ICOs on ethereum for clients. Currently working on a project that helps developers build Dapps.**

My interest are in platform development and virtual machines.

cheers,
Faizan
[eff-kay.github.io](eff-kay.github.io)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @eff-kay
