### ISSUE TITLE
I want to go to NEO DevCon!  my email: zhengm18@mail.wlu.edu

### ISSUE THREAD

**Issue by zhengm96** [neo-project/neo.org#330]
I am a NEO holder since July, with connections to the Beijing community.  I would love to learn how to implement the master nodes for future NEO developments etc. 

https://github.com/dh110f17/bio-zhengm96.git

**Comment by chenzhitong** [comment]
You contribute less on GitHub and that link is 404.. Can you provide other links or screenshots that prove you are a developer?

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @zhengm96
