### ISSUE TITLE
I want to go to NEO DevCon! My email: krobison@stanford.edu

### ISSUE THREAD

**Issue by krobison9595** [neo-project/neo.org#331]

**Comment by chenzhitong** [comment]
Please write down a brief self-introduction and area of development you're good at. And write down links to GitHub blockchain projects that you are involved in.

**Comment by krobison9595** [comment]
Hello, thank you for the opportunity. I am very excited to be considered for a ticket. I first invested in NEO as antshares mid-July of last year when I saw a presentation by Da on the antshares developer vision and the underlying antshares protocol. 

I am a stanford university master’s student studying industrial engineering and public policy. I have taken extensive computer science classes and have had a couple of startups focused on raising inequity in education. The blockchain is the ultimate way to levy the low-income community out of poverty with powerful change in our world. I desire to build on the NEO ecosystem to make this goal a reality.

Best, 

Konner Robison
(775) 313-5037

Please excuse the brevity of this email as it was typed with two thumbs.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @krobison9595
