### ISSUE TITLE
I want to go to NEO DevCon! My email: jin_chang@mba.berkeley.edu

### ISSUE THREAD

**Issue by jinchang1** [neo-project/neo.org#335]
Currently an MBA candidate at Berkeley Haas and also a co-founder of a startup that we are considering for an ICO on NEO. My co-founder will also be attending (already approved by your team) and look forward to learning more. Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jinchang1
