### ISSUE TITLE
I want to go to NEO DevCon! My email: georgextwu@berkeley.edu

### ISSUE THREAD

**Issue by georgextwu** [neo-project/neo.org#339]
I am a recent graduate from Berkeley passionate about cryptography as well as developing a new cryptocurrency with a focus on China. I would love the chance to be able to participate in this DevCon and both be able to learn from my fellow developers as well as hopefully contribute to the growing community.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @georgextwu
