### ISSUE TITLE
I want to go to NEO DevCon! My email: benny.sadeh@gmail.com

### ISSUE THREAD

**Issue by bsadeh** [neo-project/neo.org#340]
I'm a software craftsman, mostly coding backends.
currently working with leverj.io developing a cryptocurrencies futures exchange on Etheruem
related projects: 
https://github.com/bsadeh/market-maker
https://github.com/bsadeh/solidity-solids

I'm very interested in developing on NEO and bypass the "programing in solidity" shackles ...

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @bsadeh
