### ISSUE TITLE
“I want to go to NEO DevCon! My email: gutt@mail.yu.edu”

### ISSUE THREAD

**Issue by jaimegutt18** [neo-project/neo.org#343]
My name is Jaime Gutt and I am a Venezuelan student who is a senior at Yeshiva University. As an avid promoter and investor of cryptocurrencies and blockchain technologies, I am currently forming a partnership with the leading cryptocurrency ATM Company in the country (Coinme, https://www.coinme.com/about/) in order be their prime distributor in Latin America and facilitate their entrance to Latin American countries. Coming from Venezuela and being affected by severe inflation I am extremely motivated to expand blockchain technologies in South America. I strongly look forward to the possibility of attending this conference and learning more about NEO.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jaimegutt18
