### ISSUE TITLE
 I want to go to NEO DevCon! My email: udomsrin@sandiego.edu

### ISSUE THREAD

**Issue by udomsrin** [neo-project/neo.org#344]
I'm really wanting to see Alex DiCarlo speak about NEO-ONE and Chris Hager's workshop about Smart Contract dev in Python since that is my stronger language. A flight from San Diego to SF won't be too hard to get too ;)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @udomsrin
