### ISSUE TITLE
I want to go to NEO DevCon! My email: sparc999@gmail.com

### ISSUE THREAD

**Issue by sparc999** [neo-project/neo.org#346]
YES!! I would like to thank @NEO_DevCon and @NEO_Blockchain for the ticket to NEO DevCon 2018! Excited to meet the NEO team, all the other NEO developers and community members. Thank you for this opportunity. Looking forward to this event.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @sparc999
