### ISSUE TITLE
I want to go to NEO dev con! My email is lom@rh.com 

### ISSUE THREAD

**Issue by lohithbo** [neo-project/neo.org#348]
Hi, I would like to take this opportunity and understand the initiatives taken by Neo Council in supply chain domain. I'm an architect in Retail company and we are actively looking at developing smart contracts around few of our modules using blockchain framework.  We are looking at Ethereum as well, since Neo is already using PoS and our understanding is that transaction charges at Neo platform will be much lesser than ethereum. We are in early stages so would be great to learn what can Neo bring to the table. 

Profile: https://www.linkedin.com/in/lohith-b-om-4a6b9220/
So Please share the tickets. Thanks, Lohith

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @lohithbo
