### ISSUE TITLE
I want to go to NEO DevCon! My email: clarence.hl.liu@gmail.com

### ISSUE THREAD

**Issue by ClarenceL** [neo-project/neo.org#349]
Hi,

I'm a full-stack senior JS engineer at www.headnote.com - a legal billing startup here in San Francisco out of the NFX Guild Accelerator program.
https://www.linkedin.com/in/clarencehlliu

Though we are not ready for blockchain now, we are trying to disrupt the legal industry and this may be something we will look at in the future, plus a personal interest of mine. Currently am developing an entry for the dev competition and hoping to contribute against the neo-js project since advancement of that platform would be awesome for JS developers like myself. Submitted my first issue a few weeks ago, https://github.com/CityOfZion/neo-js/issues/114

Would love to come see what other projects are going on and hopefully come up for something applicable to the legal industry.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ClarenceL
