### ISSUE TITLE
I want to go to NEO DevCon! My email: ericzhevel@berkeley.edu

### ISSUE THREAD

**Issue by EZHEVEL** [neo-project/neo.org#352]
I am an undergraduate student at UC Berkeley studying Economics. I am interested in bringing emerging technologies to market and spent the last year working for one of the fastest growing machine learning start-ups, DigitalGenius. I became interested in Cryptocurrencies as of October 2017 and have invested in multiple coins. My goals for 2018 are to become more immersed in the blockchain space by investing in promising projects and learn more about the underlying technology. I believe NEO DevCon will be a great step for my involvement in the Blockchain and Cryptocurrency space and hope to join you there with a student scholarship.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @EZHEVEL
