### ISSUE TITLE
I want to go to NEO DevCon! My email: mu_yang@mba.berkeley.edu

### ISSUE THREAD

**Issue by mafario** [neo-project/neo.org#353]
My name is Mu and I am a first year MBA student at Berkeley Haas. I am passionate about leveraging BlockChain and its trust-less network to save credit costs and to remove frictions in the economy. While I am not from a programming background, I've developed technical aptitude from self-studying and learning from BlockChain expert. I am hoping for an opportunity to get more exposure to the leading forces of the BlockChain technology by going to NEO DevCon.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mafario
