### ISSUE TITLE
I want to go to NEO DevCon! My email: GenoZhou@Gmail.com

### ISSUE THREAD

**Issue by GenoZhou** [neo-project/neo.org#354]
Hi Team,
This is Hanxuan Zhou (Geno), an iOS developer from Toronto.
I work as a software developer at one of the banks in Canada.
I am applying this for my personal interest. I know about blockchain from a few sessions by devs and venders hold at my workplace, and many of my colleagues are interested in this technology. I started to know about NEO from one of my friend who was attending the competition and I was totally amazed and inspired.
I am interested to see how NEO can be applied into real world. I was luckily assigned with a token of Hashpuppies a few weeks ago, and I cannot wait to see more ambitious applications to be implemented by the community.
I hope it is not too late to be part of the community, I would like to explore how you folks utilize the blockchain technology and how myself could adopt this technology into my ideas.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @GenoZhou
