### ISSUE TITLE
I want to go to NEO DevCon! My email: rabah@bithunch.com

### ISSUE THREAD

**Issue by rabahs** [neo-project/neo.org#356]
I am a Blockchain and full-stack developer/consultant and currently looking at NEO for one of my projects. Thanks

**Comment by rabahs** [comment]
I am a Blockchain and full-stack developer/consultant and currently looking at NEO for one of my projects. Thanks

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @rabahs
