### ISSUE TITLE
I want to go to Neo DevCon! My email: ahsan.salem@gmail.com

### ISSUE THREAD

**Issue by playgrnd** [neo-project/neo.org#357]
Hi Team,

My name is Ahsan and I have over 5 years of experience in the financial sector. I have worked for one of the biggest credit card companies in the US and I know how inefficient their developments cycles could be.  I have recently started studying and investing in the blockchain technology and I really love NEO!! I am a software engineer with work experience in Data warehouse, business intelligence and ETL

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @playgrnd

**Comment by playgrnd** [comment]
Hello,  Please find the link to my linked in account:
https://www.linkedin.com/in/ahsan-salem-079a0322/
I don't use gethub because our software is a propriotary technology and it is called Ab initio. Also, you can see my profile on team tree house
https://teamtreehouse.com/ahsansalem
I can send you some screen shot from my laptop if you send me your email address please.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @playgrnd
