### ISSUE TITLE
I want to go to NEO DevCon! My email: ishanishu@gmail.com

### ISSUE THREAD

**Issue by ishanishu** [neo-project/neo.org#358]
I am working with groww.in (investment platform based out of India). I am personally involved in creating back-end transaction platform for mutual funds. I haven't done any blockchain projects but want to explore blockchain to create mutual funds.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.

**Comment by ishanishu** [comment]
PFb snapshot of my code

Thanks
Ishan Bansal
Phone Number: +91-99720-94460

Why consider the environment before printing this email!!
