### ISSUE TITLE
I want to go to NEO DevCon! My email: josef.hazi@queens.ox.ac.uk

### ISSUE THREAD

**Issue by Josefcoin** [neo-project/neo.org#359]
I have been in the blockchain and crypto space since 2014. I am very passionate about the NEO ecosystem and all the new projects built on top of it such as QLink, Zeepin, Deep Brain, and others. I study at the Queen's College, Oxford University UK.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Josefcoin
