### ISSUE TITLE
I want to go to NEO DevCon! My email: josehazi@mit.edu

### ISSUE THREAD

**Issue by oxford-crypto** [neo-project/neo.org#360]
Just submitting my MIT email as well. I am currently at Oxford but used to be at MIT so wanted to make sure you notice the "edu" ending. I have many reasons to attend - want to learn more about current as well as new NEO projects and investments. I am also helping GBIC promote some of the NEO's projects - namely I was one of the KOL (key opinion leader) on the Deep Brain ICO. I am currently more involved in the investment and marketing part and I am par of several blockchain funds, however, my goal is to learn more about the tech part and start coding blockchains myself. Also you can check my online presence on steemit.com/@oxfordcrypto and https://www.reddit.com/user/crypto_oxford/. In particular, my Deep Brain Chain article went viral with over 15 000 views https://steemit.com/neo/@oxfordcrypto/the-deep-brain-chain-project-usd15m-ico-that-neo-invested-in

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @oxford-crypto
