### ISSUE TITLE
I want to go to NEO DevCon! My email: alexanderekoren@gmail.com

### ISSUE THREAD

**Issue by AlexEKoren** [neo-project/neo.org#361]
I have a few private repos of developments I've put together, but my main focus has been on making blockchain tech easily accessible to mobile users. I am an iOS developer full time and want to enable easy transactions from mobile to other clients for NEO and other currencies.

I was selected as a 2014 Thiel Fellow for my mobile development work and have been working with NEO since ANS and before. I'd love to come to the event and am sure I'll be able to contribute!

Skillset:
Objective-C / Swift
Python
C / C++
Networking
Blockchain Fundamentals

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @AlexEKoren
