### ISSUE TITLE
I want to go to NEO DevCon! My email: mackey32@gmail.com

### ISSUE THREAD

**Issue by naoyamakino** [neo-project/neo.org#362]
I have been exploring blockchain technologies in recent months and created few Truffle based Dapps, deployed to rinkeby testnet and getting familiar into this space. My profession is in mobile development; more than 5 years of mobile app development, particularly in Android. Using my professional skill in mobile development and with more understanding of blockchain technology, I am interested in building mobile apps leveraging some of the blockchain technology. I am very excited about NEO platform, and this is a great opportunity to know more about the ecosystem and hoping to build DApps on NEO.

My skillset:
Java, Swift, Kotlin, Go, JS, Solidity

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @naoyamakino
