### ISSUE TITLE
I want to go to NEO DevCon! My email: gloriasemme@gmail.com

### ISSUE THREAD

**Issue by gloriji** [neo-project/neo.org#363]
I'm Gloria from Berlin. I studied pure mathematics and got into coding last year after university. I'm not amazing at coding (yet) but I'm working on it practicing daily in my job as data engineer. I have diverse talents. I'm good at learning, at motivating others and also at convincing people of whatever it may be. I have an extremely high frustration tolerance and am good at sticking with problems until they are solved. I  understood the potential of blockchain technology last summer and since are spending my free time learning about just anything in the crypto space.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @gloriji
