### ISSUE TITLE
I want to go to NEO DevCon! My email: tehxx010@umn.edu

### ISSUE THREAD

**Issue by soonliteh** [neo-project/neo.org#365]
I am a bitcoin and blockchain public speaker. In addition to being a full-time graduate student, I frequently give seminars and public presentations regarding bitcoin, blockchain technology and its future second-layer solutions. 

I am interested to check out how NEO would address scalability, particularly with network bandwidth. I am also keen to learn the implementation of cross-chain interaction and decentralized exchanges.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @soonliteh
