### ISSUE TITLE
“I HELLA want to go to NEO DevCon! My email: george@sfindie.com ”

### ISSUE THREAD

**Issue by jasonvoorheesjr** [neo-project/neo.org#366]
Hi, I work with sfindie an all year  san francisco indie film festival. We've been working on creating a blockchain for indiefilm submissions and and would love to checkout your company and see what you have to offer. Thank you for giving us a chance to attend. If you can spare 3 tickets that would be amazing but if not one will work for myself. I will take plenty of notes. thank you

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @jasonvoorheesjr

**Comment by jasonvoorheesjr** [comment]
I can not provide screenshots, the only thing I can provide is our website www.sfindie.com we attract around 200,000 users a month and receive about 5000 film submissions a year. This is the reason I would like to check out neo devcon. I would like to add sfindie to the neo network. I like neos design and company philosophy. We want to create a smart economy in sfindie and I would like to learn more about what you offer. Im not trying to get free tickets, If I can purchase one or two I would gladly do so. Thank you for responding by the way.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jasonvoorheesjr
