### ISSUE TITLE
I want to go to NEO DevCon! My email: Because.the.Blockchain@gmail.com

### ISSUE THREAD

**Issue by btbc** [neo-project/neo.org#367]
I am working during the day as full stack software engineer at a 500 Fortune company working on building a great frontend experience in the React ecosystem. At night I work on crypto projects. The last one was an identity blockchain. The previous one an ICO platform. 

Very excited about NEO. I have been looking into it since it was Antshares.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @btbc
