### ISSUE TITLE
I want to go to NEO DevCon! My email: jason@suncoast.io

### ISSUE THREAD

**Issue by ambethia** [neo-project/neo.org#368]
Hello! City of Zion Developer checking in, these are the CoZ projects I am developing:

- https://github.com/CityOfZion/neo-ruby
- https://github.com/CityOfZion/neo-ruby-sdk
- https://github.com/CityOfZion/neo-gql

Please also review my GitHub profile for additional credentials: https://github.com/ambethia/

Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ambethia
