### ISSUE TITLE
I want to go to NEO DevCon! My email: noe.bos@hva.nl

### ISSUE THREAD

**Issue by NoeBoss** [neo-project/neo.org#369]
Hi there, I am a pyschology student at a Dutch university (we dont have .edu email adresses), with a huge interest in blockchain and Neo specifically. I recently started learning python in my spare time. I am very interested in going to the Neo DevCon but since I would have to buy a plane ticket to get there, it's already going to be expensive for me. Getting a ticket would help me out a lot! I really want to get to know the developing world better and learn a lot to start contributing.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @NoeBoss
