### ISSUE TITLE
I want to go to NEO DevCon! My email: kbshop85@gmail.com

### ISSUE THREAD

**Issue by KBog** [neo-project/neo.org#370]
Hi, I'm a software engineer who started my own company in 2014 (www.tooride.com) and currently working at a startup in the Bay (www.trybooster.com)

I haven't worked on Blockchain projects yet, but I own some NEOs and would be interested to learn about the dev community around it! Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @KBog
