### ISSUE TITLE
I want to go to NEO DevCon! My email: betterever2@gmail.com

### ISSUE THREAD

**Issue by sase1017** [neo-project/neo.org#371]
Hi Neo DevCon,

I am C# developer, have been learning blockchain technology for a while, I am from New York, I would like to attend NEO DevCon to learn NEO platform and technology in order to launch my own project in the near future.

My email address is: betterever2@gmail.com

Best,
Ken

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @sase1017

**Comment by sase1017** [comment]
Hi chenzhitong,

We don't always use github as source control, I am in consulting industry so most our clients prefer SoureTree or TFS due to security reason(open source), so far only one project used github and only used as internal term share.

I am also learning blockchain technology, I believe NEO Dev Con is great place to learn and interact with other on-training blockchian developers to grow NEO ecosystem together. I will be flying from New York and in SF for 2 days to dedicate my learning for NEO, receiving a ticket will be a huge support for me and reduce the cost drastically for my trip and training.

Much appropriate it~

Best regards,
Ken

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @sase1017
