### ISSUE TITLE
I want to go to NEO DevCon! My email: mhamlett@hmc.edu

### ISSUE THREAD

**Issue by MichaelHamlett** [neo-project/neo.org#373]
Hello,

I'm a second year studying Computer Science at Harvey Mudd College. I am currently interested in iOS development, but I would love to learn more about Neo, blockchain, and how to develop dapps. I've been following Neo since August and this seems like a great learning opportunity.

Best,
Michael Hamlett

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @MichaelHamlett
