### ISSUE TITLE
I want to go to NEO DevCon! My email: david.m.sievers@accenture.com

### ISSUE THREAD

**Issue by dsievers4** [neo-project/neo.org#374]
I work at Accenture in our global Innovation Network. I work on a wide variety of blockchain projects. Would love to learn more in order to better understand opportunities to collaborate together. Thank you for your consideration.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @dsievers4
