### ISSUE TITLE
I want to go to NEO DevCon! My email: fodesdiop@gmail.com

### ISSUE THREAD

**Issue by diop** [neo-project/neo.org#375]
I'm currently a Full Stack Software Engineer in the San Francisco Bay Area and am very passionate about Blockchain Technologies. 

My team and I just participated in the WCEF Hackathon and would love to attend Neo DevCon. 

+ [https://devpost.com/software/flyers-ai](https://devpost.com/software/flyers-ai)
+ [http://www.flyers.ai/](http://www.flyers.ai/)

+ [https://www.blockchaindevelopers.io/](https://www.blockchaindevelopers.io/)
+ [Oakland Blockchain Developers Meetup Co-Organizer](https://www.meetup.com/Oakland-Blockchain-Developers-Meetup/)

Thank you.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @diop
