### ISSUE TITLE
I want to go to NEO DevCon! My email: christian.s.h.ling@gmail.com

### ISSUE THREAD

**Issue by csling** [neo-project/neo.org#376]
Hello! I am a full-stack developer who currently works as a software engineer at a FAANG company. Before working as a software engineer, I graduated from Harvard Law School and worked at an international law firm for around two years as a corporate attorney. I'm currently learning blockchain development and am interested in creating distributed apps that are related to the legal industry and community-based / social financial products. I'd love to attend NEO DevCon to make connections and friends in the industry and to see if NEO would be a good fit for my future app ideas. 

Please let me know if you'd like me to privately email you my LinkedIn profile.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @csling
