### ISSUE TITLE
I want to go to NEO DevCon! My email: emberleyjason@gmail.com

### ISSUE THREAD

**Issue by jason00111** [neo-project/neo.org#378]
I enjoy writing code and I live in the SF Bay area.
Most of my experience is in web development.  I'm familiar with solidity and web3.
I would like to become more involved in blockchain projects.

Blockchain project:
- https://devpost.com/software/flyers-ai
- https://github.com/diop/flyers-api

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jason00111
