### ISSUE TITLE
I want to go to NEO DevCon! My email: raythai@stanford.edu

### ISSUE THREAD

**Issue by raymond513** [neo-project/neo.org#379]
Hi, 
I'm Ray Thai. I'm ecstatic to be extended the opportunity to receive tickets to NEO DevCon. I'm a computer science student at Stanford University. I invested in NEO in August because I believed in the platform's technological superiority and its ability to make blockchain accessible to institutions and government. I've taken all but two courses in Stanford's computer science core and am a student instructor for [Stanford's Beyond Blockchain course](http://web.stanford.edu/class/bioe60/).  Last summer, I worked in software development for Hewlett Packard and I plan to work as a developer after graduating. I am especially interested in blockchain development and have begun experimenting with programming smart contracts. I hope to attend NEO DevCon to meet other like-minded developers and personally see different ways to develop on the NEO ecosystem.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @raymond513
