### ISSUE TITLE
I want to go to NEO DevCon! My email: eddienaude@gmail.com

### ISSUE THREAD

**Issue by eddienaude** [neo-project/neo.org#381]
Hi, I am a student Boston University in computer information systems; and a physician. I am interested in using your platform to develop smart contract based health records, prescribing systems and chronic disease management smart flow sheets.
I will be pleased and honoured if I can attend your DevCon.

Best regards.

Dr. Eddie Naude, MBCHB, CCFP

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @eddienaude
