### ISSUE TITLE
I want to go to NEO DevCon! My email: syok89315@tacomacc.edu

### ISSUE THREAD

**Issue by syok15** [neo-project/neo.org#383]
Hello NEO team,

My name is Sannarouth Yok and I'm a full time student majoring in Computer Science at Tacoma Community College. I have almost reached the pre-requisites for entry to University of Washington (Java 1 & 2 + Calc) and have gained quite an interest in cryptocurrency and blockchain technology. Perhaps most notably is NEO's recent rise to one of the top crypto of 2018 and the company's implementation of smart economy.

My passion revolves around coding and playing around with Java but blockchain technology will revolutionize how we see assets such as digital property and currency. I want to be apart of the NEO movement & nothing would mean more to be surrounded by like minded individuals that will leave an imprint on society in terms of a decentralized currency.

Thank you and I hope to be chosen as a candidate for the NEO DevCon Tickets!

Best Regards,
Sannarouth Yok

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @syok15
