### ISSUE TITLE
I want to go to NEO DevCon! My email: gawli.n@husky.neu.edu

### ISSUE THREAD

**Issue by niranjangawli** [neo-project/neo.org#384]
Hello NEO team,

My name is Niranjan Gawli and I'm a full time student in Information Systems at Northestern University. I'm currently good at development in Java and Java frameworks such as Spring MVC & have gained quite an interest in cryptocurrency and blockchain technology. NEO's blockchain is one of the solutions that allows me to write smart contract in Java and then compile them in bytecode for NVM which is amazing for me as this reduces the time learning new technology.

I will look forward to being a part of NEO ecosystem and contribute to its growth. I've very recently started to code on blockchain technologies. One of project is below that I developed as a part of a team at WCEF Hackathon. In brief, Kittykeychain is a naming service like ENS (Ethereum Naming service) but for all the Crypto wallet addresses.

Git: https://github.com/mtlapinski/uname-frontend
Presentation: https://github.com/mtlapinski/uname-frontend/blob/master/uname_v7.pdf

Thank you, I hope to attend NEO DevCon Tickets and learn more about its ecosystem.

Best Regards,
Sannarouth Yok

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @niranjangawli
