### ISSUE TITLE
I want to go to NEO DevCon! My email: kmckoy@mail.ccsf.edu

### ISSUE THREAD

**Issue by kloove** [neo-project/neo.org#386]
I want to go to NEO DevCon! My email: kmckoy@mail.ccsf.edu

**Comment by chenzhitong** [comment]
Please write down a brief self-introduction. @kloove

**Comment by kloove** [comment]
Hey there!
I've been involved and have a continued interest in cryptocurrency, in particular, cryptocurrencies that have real world application and value. NEO fits right in here with it's real store of value for businesses that is both on-chain and off-chain. I've been following NEO since they were Antshares and i will continue to follow them into a better future fueled by all the amazing things coming out of blockchain technologies.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @kloove
