### ISSUE TITLE
I want to go to NEO DevCon! My email: xueenda@gmail.com

### ISSUE THREAD

**Issue by xueenda** [neo-project/neo.org#387]
To whom it may concern:
I am very interested in NEO DevCon.

Here is my brief introduction:
Enda Xue

Backend Developer  | Full Stack | Inventor | Entrepreneur

I believe a great engineer is the one with great business ideas and good at leveraging existing infrastructure to solve the real world problem.

Github contributions in last two years plus most of my personal projects are on bitbucket:
1,666 contributions in 2017
1,373 contributions in 2016

I am very interested in Blockchain technology. I wish I can join there with you guys and have more discussions.

My LinkedIn:
[https://www.linkedin.com/in/xueenda/](https://www.linkedin.com/in/xueenda/)

Cheers,
Enda

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @xueenda
