### ISSUE TITLE
I want to go to NEO DevCon! My email: tim.siwula@consensys.net

### ISSUE THREAD

**Issue by tcsiwula** [neo-project/neo.org#388]
Ethereum protocol dev here to see all this neo is about!

https://www.npmjs.com/package/happychain
https://github.com/ethereum/benchmarking
https://github.com/happyethereum/dns-to-ens

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tcsiwula
