### ISSUE TITLE
I want to go to NEO DevCon! My email: buffaloweblove@mail.com

### ISSUE THREAD

**Issue by biko-the-bird** [neo-project/neo.org#389]
Hello I am a junior developer wanting to learn about the functionality of blockchains. I am most experienced with Swift and Python. I am currently attending classes to improve my skills. I would like to attend NEO Con to study your platform and work on projects on top of it after the conference. I am based in NYC.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @biko-the-bird

**Comment by biko-the-bird** [comment]
@chenzhitong I have not received any message regarding the promotional code yet. I will check again in 8 hours.

**Comment by chenzhitong** [comment]
The first one I forgot to write the subject, I guess in the junk email, I have to send it again. @biko-the-bird

**Comment by biko-the-bird** [comment]
@chenzhitong it has arrived thank you for resending. See you at the conference cheers
