### ISSUE TITLE
I want to go to NEO DevCon! My email: nzoghb@berkeley.edu

### ISSUE THREAD

**Issue by nzoghb** [neo-project/neo.org#390]
I teach a for-credit blockchain class at UC - Berkeley called Blockchain for Developers. This involves everything from syllabus design to lecturing. My main area of focus is blockchain and distributed system education. Course assignments can be found here: github.com/Blockchain-for-Developers

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @nzoghb
