### ISSUE TITLE
I want to go to NEO DevCon! My email: shaun_he@mba.berkeley.edu

### ISSUE THREAD

**Issue by Shaun221** [neo-project/neo.org#391]
I'm a first-year full-time MBA student at UC Berkeley, Haas School of Business. My current focus is AI and Blockchain, and I will be helping a cryptocurrency startup this semester. Would be loving to join the NEO DevCon to learn and to share. - Shaun

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Shaun221
