### ISSUE TITLE
I want to go to NEO DevCon! My email: dzhao0@stanford.edu

### ISSUE THREAD

**Issue by dzhxo** [neo-project/neo.org#392]
Hi all,
My name is David and I'm at Stanford. I'm an AI researcher in the Stanford Vision Lab, the president of Stanford ACM, and am the lead organizer/instructor of a class at Stanford called BioE60: Beyond Bitcoin (beyondbitcoin.stanford.edu). I am also involved in the venture capital field as a partner at Contrary Capital, and am actively looking into cryptocurrency investments. I've worked in data science at ZingBox, an IoT cybersecurity company, and have a strong interest in the security/crypto space. I plan on working as a developer post-graduation. I hope to get the chance to attend NEO DevCon!

Best,
David

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @dzhxo
