### ISSUE TITLE
I want to go to NEO DevCon! My email: mtl@mit.edu

### ISSUE THREAD

**Issue by mtlapinski** [neo-project/neo.org#393]
I'm an MIT PhD who built his first distributed system in 1998 and am heavily into blockchain, cryptography, security. I also possess deep knowledge of several domains related to tech and beyond. More info on LinkedIn. 

[https://www.linkedin.com/in/mtlapinski/](https://www.linkedin.com/in/mtlapinski/)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @mtlapinski
