### ISSUE TITLE
I want to go to Devcon! My email: dojha@berkeley.edu

### ISSUE THREAD

**Issue by ValarDragon** [neo-project/neo.org#394]
My name is Dev Ojha. I am a freshman Electrical Engineering and Computer Science major at UC Berkeley. The areas of development I focus on are cryptanalysis, security, and algorithm design. I am currently doing research with Blockchain at Berkeley.

The blockchain projects I am currently working on are not public on github, since they are more research based. I am in a team doing Proof of Stake research, and the team has been talking to NEO about a potential research partnership with NEO and Ontology. I am looking forward to DevCon!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ValarDragon
