### ISSUE TITLE
I want to go to NEO Devcon! My email: efYqDtgi1cX@protonmail.com

### ISSUE THREAD

**Issue by thewinniewu** [neo-project/neo.org#395]
I'm a Software Engineer at Square in San Francisco, Harvard '16, with a developing interest in blockchain and the cryptocurrency space, haven't contributed to any blockchain projects other than what I work on at work (yet!) :)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @thewinniewu
