### ISSUE TITLE
I want to go to NEO DevCon! My email: mypoland2011@gmail.com

### ISSUE THREAD

**Issue by ABAPMUSTAFA** [neo-project/neo.org#398]
Hi i am 5 years of SAP Abap developer and wants to join your network.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer? @ABAPMUSTAFA

**Comment by ABAPMUSTAFA** [comment]
Here is my linked in profile

https://www.linkedin.com/in/abapmustafa/

MUSTAFA YILMAZ

2018-01-17 13:05 GMT+03:00 陈志同 <notifications@github.com>:

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ABAPMUSTAFA
