### ISSUE TITLE
I want to go to NEO DevCon! My email: joe@artbykenji.com

### ISSUE THREAD

**Issue by br0therjay** [neo-project/neo.org#402]
I'm a Cryptocurrency investor and trader, working on creating a decentralized exchange system for the ASEAN Market. Currently, I have nothing to show on this project as it is ongoing, however it would be of great benefit for me to meet up with the community at DevCon and talk more on this project. Hope to even meet the NEO team and see if your smart contracts systems is able to fit in to this!

**Comment by chenzhitong** [comment]
Sorry, the free tickets are only for developers who have contributed to the GitHub. @br0therjay
