### ISSUE TITLE
I want to go to NEO DevCon! My email: chuck.lam@stanfordalumni.org

### ISSUE THREAD

**Issue by chucklam** [neo-project/neo.org#405]
I am interested in attending NEO DevCon.

My name is Chuck Lam. I'm a full-stack developer and data scientist. I have a PhD in pattern recognition / machine learning, and I'm the author of one of the first books on Hadoop: https://www.amazon.com/Hadoop-Action-Chuck-Lam/dp/1935182196

Github shows I had 83 (public) contributions in 2014. Most of my projects had been private.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @chucklam
