### ISSUE TITLE
I want to go to NEO DevCon! My email: solangegueiros@gmail.com

### ISSUE THREAD

**Issue by solangegueiros** [neo-project/neo.org#406]
To whom it may concern:
I would love to participate at NEO DevCon.

Here is my brief introduction:
Solange Gueiros

Blockchain specialist

I know a lot about Ethereum Blockchain.
I have same projects with energy, payments, exchanges, ICOs and tokens. 
I'd like to develop some of these projects at Neo Blockchain.
I think this can be as good for NEO as for me. 

Some of projects are not public, one of them are at bitbucket.
I have a few things at github:
https://github.com/solangegueiros/

I really like to teach. In Brazil I don't know anyone who has knowledge about Neo, I can be a teacher.

I write at Medium:
https://medium.com/@solangegueiros

Also I have more than twenty years of professional experience. 
Extremely adaptable to differents projects and environments with a great capacity to absorb and develop new technologies!

My LinkedIn:
https://www.linkedin.com/in/solangegueiros

Best regards,
Solange

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @solangegueiros
