### ISSUE TITLE
I want to go to NEO DevCon! My email Carl.travis@holbertonschool.com

### ISSUE THREAD

**Issue by cctravis1** [neo-project/neo.org#407]
Hello my name is Carl Travis and my journey to where I. Today began with NEO.

I am attending Holberton School in San Fransisco which is a non-traditional software engineering school based very close to where devcon will be held.

I started researching and investing in NEO during the name change and this is where my NEO love affair began.

I liked everything I saw from the dev team and roadmap and knew I wanted to learn to develop smart contracts in the future with a focus on NEO. I began looking for educational opportunities that would give me the skills to become the NEO developer I wanted to be and I came across Holberton school. 

To make a long story short I was accepted into the current cohort and picked up and moved my life to San Fransisco to begin my education and journey to becoming a NEO dev. Upon arrival I found out another of my fellow students was also into NEO since the ant share days and also had the same dream to be a NEO dev after we finishing our studies. This was the first person I meet in real life that had the same belief in NEO as myself and was working towards the goal of becoming a NEO dev. 

Attending NEO devcon would not just be a dream come true but the next logical step on my journey to becoming a NEO dev.

I have taught many people about NEO over the last year and would be excited, humbled and truly grateful to attend NEO Devcon. Thanks for the opportunity.

My current GitHub is cctravis1 and consists mostly of work for school. 

Thanks again
Carl Travis

**Comment by cctravis1** [comment]
Sorry for the above typo... I was very excited to get this application in and not miss out on the ticket deadline and typed this quickly on my phone. 

Correction.....
Hello my name is Carl Travis and my journey to where I am Today began with NEO.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @cctravis1
