### ISSUE TITLE
I want to go to NEO DevCon! My email: darwin_arifin@berkeley.edu

### ISSUE THREAD

**Issue by Dellman1225** [neo-project/neo.org#408]
I am currently a first year Haas MBA student. I have a PhD in Chemical Engineering, and have experience in renewable energy and semi-conductor manufacturing. I am a highly analytical entrepreneur interested in the application of blockchain in supply chain and manufacturing.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Dellman1225
