### ISSUE TITLE
I want to go to NEO DevCon! My email: nikhil.jacob@insead.edu

### ISSUE THREAD

**Issue by njay386** [neo-project/neo.org#410]
First off, thank you for organizing this! I am an MBA student and a cryptocurrency investor and enthusiast. With my background in finance, tech VC, and startups, I help bridge the gap between blockchain concept tech functionality and the average non-tech person's approach to cryptocurrency. I am a big believer in the upcoming pipeline of NEO projects, and am particularly excited about Trinity. I am an avid supporter of projects through their telegram/reddit communities, and i help evangelize the process and benefits of scaling, cryptography and encryption, utility of blockchain assets, and the incentive structures upon which these platforms are built. 

https://github.com/trinityrnaseq/trinityrnaseq
https://github.com/CityOfZion/neon-wallet/releases
https://github.com/wanchain
https://github.com/Zilliqa/docs

Projects I am looking forward to:
NEX
Zeepin

Best,
Nik

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @njay386
