### ISSUE TITLE
I want to go to NEO DevCon! My email: accavdar@gmail.com

### ISSUE THREAD

**Issue by accavdar** [neo-project/neo.org#411]
Hi,

My name is Cetin and I really want to attend NEO DevCon.

I'm a Senior Data Engineer and working in Udemy. My public profile: https://github.com/accavdar?tab=repositories. I'm basically focusing on big data processing, scalability, machine learning and distributed systems. 

Most of my contributions are in the private repositories. Sorry about it. 
I'm `Wanchain`s (https://github.com/wanchain) community/test developer. I'm also interested in `etheremj` (https://github.com/ethereum/ethereumj), `cardano-sl` (https://github.com/input-output-hk/cardano-sl), `ripple` (https://github.com/ripple/ripple-lib-java) and of course `neo` (https://github.com/neo-project/neo-devpack-java)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @accavdar
