### ISSUE TITLE
I want to go to NEO DevCon! My email: cindayle@u.washington.edu

### ISSUE THREAD

**Issue by drstrangele** [neo-project/neo.org#412]
I want to go to NEO DevCon! My email: cindayle@u.washington.edu

I'm a software engineering student at General Assembly and I'm also a student at the University of Washington.  I don't have any blockchain development experience but I'm very interested in learning and I've been a huge fan of NEO.   

Here is a link to a project I had worked on at a hackathon -
https://github.com/drstrangele/bareskills 

Thanks,

Cin

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @drstrangele
