### ISSUE TITLE
I want to go to NEO DevCon! My email: geordiewicks@gmail.com

### ISSUE THREAD

**Issue by gwicks56** [neo-project/neo.org#414]
I'm a software dev working at the University of Oregon. Have some experience with the bitcoin blockchain, mainly the BitcoinJ implementation. I do mainly Android dev as part of a research project here, but to pass IRB also have extensive privacy, security and cryptology knowledge.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @gwicks56
