### ISSUE TITLE
I want to go to NEO DevCon! My email: rayhernandez@stanford.edu

### ISSUE THREAD

**Issue by HernandezRay** [neo-project/neo.org#417]
Hi, 

My name is Ray Hernandez and I am co-president of Stanford GSB's Blockchain Club. I have been contributing to the growing blockchain community within Stanford and would love to attend the NEO DevCon. It would provide me with an opportunity to continue learning about NEO and help spread knowledge about it's potential to our community. 

Thank you, 
Ray

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @HernandezRay
