### ISSUE TITLE
I want to go to NEO DevCon! My email: yidagao@stanford.edu

### ISSUE THREAD

**Issue by github1273** [neo-project/neo.org#420]
Hi - I graduated from MIT with a major in computer science and math. I am also a crypto investor. Zhao Chen recommended that I apply for the developer position as I have a unique background in investing and programming. I’m currently a student at Stanford. Here is a link to the blockchain projects I’m part of:

https://github.com/neonexchange/neo-ico-template

https://github.com/0xProject/contracts

And Ontology.

Best,
Yida

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @github1273
