### ISSUE TITLE
I want to go to NEO DevCon! My email: ustymenko@gmail.com

### ISSUE THREAD

**Issue by vaustymenko** [neo-project/neo.org#421]
I'm a software architect with expertise in security, business intelligence and ecommerce. https://devpost.com/software/ibcs-international-blockchain-credit-score?ref_content=contribution-prompt&ref_feature=engagement&ref_medium=email&utm_campaign=contribution-prompt&utm_content=contribution_reminder&utm_medium=email&utm_source=transactional#app-team

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @vaustymenko
