### ISSUE TITLE
I want to go to NEO DevCon! My email: tkothari@stanford.edu

### ISSUE THREAD

**Issue by Tanay1998** [neo-project/neo.org#422]
I'm an IOI medalist and have been into software development for 8 years. One of my products: Convert.cc which provided personalized music discovery got 2.5 million downloads. Currently I am an undergrad at Stanford, doing AI research with Andrew Ng. 

I got interested in blockchain technologies mid-last year and have since been reading lots of whitepapers, doing tutorials for solidity development, investing in cryptocurrencies, and meeting people to learn more about this space.

My project for WCEF Hackathon (going to be launched on Ethereum MainNet soon): https://github.com/cumbach/CryptoCanvas
I'm working on one more stealth mode project as well which are going to be launched soon.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Tanay1998
