### ISSUE TITLE
I want to go to NEO DevCon! My email: mxia@fb.com

### ISSUE THREAD

**Issue by opqpop** [neo-project/neo.org#423]
Hi,

My name is Mark and I'm a Software Engineer at Facebook for almost 4 years. I graduated from Princeton University in 2012 with a Bachelors and have been working as a software engineer since. I spent a year developing iOS mobile games at a company called Storm8, a year developing crawling and caching systems at Groupon, and almost 4 years at Facebook on various teams, from working on improving the quality of people's Ads targeting data to building out a FB Sports product to building a yelp competitor app called FB Local. 

My Linkedin: https://www.linkedin.com/in/mark-xia-a6632119/

Area of development I'm good at: designing and building API layers, model architecture, backend systems, big data analysis, pipelines, scalability, tooling. Can code in any language, PHP and Java are my strongest. Have also spent a year writing mobile apps in objC.

I am actually relatively new to blockchain development, and am in the process of brushing up on how to get started. I would like to gain more insights in this conference, and try and see if I can start contributing to some open source blockchain projects I really like. I am also part of a FB crypto group that also has several engineers interested in getting on-hands experience, so I hope to bring back what I learn to them too and get them excited about the NEO developer community. I also invest heavily in crypto, very bullish on NEO!

This is my github, but it has past hobby projects I worked on a few years back. An example is a Twitch stream indexing site I built for the video game, League of Legends. It queries game data APIs and Twitch API to figure out at which timestamps and which videos a certain match with certain characters being played occurred in, so those who want to watch video game replays of a certain character (i.e. the one you like to play) can quickly find what timestamp and video to go to. The code is here on this github: https://github.com/opqpop/river

Please let me know if there's anything else I can provide. My work email is mxia@fb.com, while my personal email is mtxia1@gmail.com. Either one is fine for the ticket link if my application is accepted.

Thanks,
Mark

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @opqpop
