### ISSUE TITLE
I want to go to NEO DevCon! My email: bjorn@g-unitrecords.com

### ISSUE THREAD

**Issue by bjorncg** [neo-project/neo.org#424]
Hello my name is Bjorn Gregg, I am the director of strategic development  For Grammy Award-nominated rapper 50 Cent, we are currently exploring ways of leveraging the blockchain and neo's smart economy for his extensive digital assets(music, art,movies)  And similarly my business partner Corentin is looking into a similar option for Alesso and Shots studio’s influencers

Can I apply for 2 tickets .

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @bjorncg
