### ISSUE TITLE
I want to go to NEO DevCon! My email: nosttrader@yahoo.com

### ISSUE THREAD

**Issue by nosttrader** [neo-project/neo.org#425]
I'm an embedded software engineer and looking to developed on blockchain.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.

**Comment by nosttrader** [comment]
www.linkedin.com/in/hoangle
Here is a link to my linked page that shows my development history.

**Comment by nosttrader** [comment]
Let me know if you need anything else, So I can start booking accommodation for the trip.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
