### ISSUE TITLE
I want to go to NEO DevCon! My email: thomas1@stanford.edu

### ISSUE THREAD

**Issue by tomcal36dc** [neo-project/neo.org#427]
Hi,

My name is Thomas Callaghan and I am a second-year student at Stanford's Graduate School of Business. I am recently getting involved in this space and see it as the next big thing. We have the opportunity to get involved early and help influence the space much like Bill Gates was in the right place at the right time leading to his influence. I think Neo may be one of these opportunities as I explore the space.

Thanks,
Thomas

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
