### ISSUE TITLE
I want to go to NEO DevCon! My email: maxim@us.ibm.com

### ISSUE THREAD

**Issue by maximilien** [neo-project/neo.org#428]

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @maximilien

**Comment by maximilien** [comment]
@chenzhitong never got it! Did you send to the email in title?

**Comment by chenzhitong** [comment]
I send the email to maxim@us.ibm.com, please check if it is in the junk emil, the subject of the email is "promotional Code for NEO DevCon"
