### ISSUE TITLE
I want to go to NEO DevCon! My email: javidantech@gmail.com

### ISSUE THREAD

**Issue by javidansalarian** [neo-project/neo.org#430]
I've been developing iOS and macOS apps since 2013 and I will be really happy to contribute your projects.
Warm wishes and good luck for NEO project.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets. @javidansalarian
