### ISSUE TITLE
I want to go to NEO DevCon! My email: cedric.chane-ching@hec.edu

### ISSUE THREAD

**Issue by Arkrixe** [neo-project/neo.org#432]
Exchange Student at UC Berkeley & Student in HEC Paris, Europe's 1rst Business School.
Studied CS & Mechy in Paris. 
Coded a few smart contracts and fan of the blockchain.
Creating a new blockchain startup right now : FunnyChain.
https://github.com/mortenhillbom/FunnyChain
With a team of 5 composed of engineers from Youtube & Google, Cisco & Paypal.

Hope you give me the chance to attend Neo DevCon ! Would be an amazing opportunity & I loooove neo (bought a bunch)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Arkrixe
