### ISSUE TITLE
I want to go to NEO DevCon! My email: bantale1@binghamton.edu

### ISSUE THREAD

**Issue by bantalek** [neo-project/neo.org#433]
Ciao, 

I'm a software engineer and CTO at a startup in the Bay Area. I am working in blockchain full time, recently deployed this website [https://cryptocoins.how](https://cryptocoins.how) with a small team and am currently putting a team together for a NEO project in 2018. I own a handful of NEO and would be interested to build stronger relations with the dev community at this conference. 

Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @bantalek
