### ISSUE TITLE
I want to go to NEO DevCon! My email: chaolu.dev@gmail.com

### ISSUE THREAD

**Issue by oceanchild** [neo-project/neo.org#434]
I am an experienced software engineer from Canada registering for the first ever NEO developer contest. I am a big fan of blockchain/cryptocurrency. I have done Ethereum smart contract development in the past and I have been holding NEO since the price was at $6. I have good faith in NEO becoming the scalable dominant dApp platform and this is the reason why I am interested in coming to the NEO DevCon. I would like to learn more about NEO's roadmap and the vision for 2018 and onwards.

My team has started a blockchain consulting firm in Canada focusing on helping traditional company from various industries raising capital via ICO as well as incorporating blockchain technology to help shaping the landscape and adopting this great technology.

Here is a link to my LinkedIn profile: https://www.linkedin.com/in/chaoludev/
Some of my project source is at bitbucket. But here is one of my recent personal project:
http://adoreapp.love (Adore App)

Regards,

Chao Lu

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @oceanchild
