### ISSUE TITLE
I want to go to NEO DevCon! My email: mmccraner@student.sierracollege.edu

### ISSUE THREAD

**Issue by fingerscrossed2** [neo-project/neo.org#435]
Hello!

I would love to attend the conference, but the cost is over my budget. I study CS and am focusing my studies toward blockchain endeavors. I am a big fan and holder of NEO.

Thank you for the opportunity.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @fingerscrossed2
