### ISSUE TITLE
I want to go to NEO DevCon! My email: davcampos1@gmail.com 

### ISSUE THREAD

**Issue by camposdavid** [neo-project/neo.org#436]
I work in the tech industry in San Francisco as a developer/developer evangelist. I love working on front-end web development, that is my specialty. Depth, colors, animations, bootstrap, responsiveness, beautiful images, gradient colors, and the list goes on. 

To me, no other coin compares to NEO, it is the future and really destroys all other coins with regards to tech, team, community, vision, architecture, and support. It would be a dream to be a part of the NEO convention. 

Also, my other student email address is for my MBA at the University of Florida, david.campos@ufl.edu--the connecting email is connected to my GitHub account. If selected, feel free to send the ticket to davcampos1@gmail.com. 

It would be a dream come true to attend the event---and 4 days after my birthday, lol. And, I would be happy to lend my time on a project if you or anyone on the NEO team needs help. In fact, I have quit my job to go all-in with NEO, that's how much I believe int he vision. 

Thank you greatly and have a wonderful weekend!

Best wishes, 
David Campos

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @camposdavid
