### ISSUE TITLE
 want to go to NEO DevCon! My email: parsa.attari@berkeley.edu

### ISSUE THREAD

**Issue by parsaattari** [neo-project/neo.org#440]
Currently, a senior at UC Berkeley studying Cognitive Science. I have been following Neo since it was called Antshares. Neo was the first place that I started to develop on the blockchain. I am currently in the works of creating an authentication service using fingerprints all using python and Neo. I have been reading about Neo for a long time and truly believe in what makes it stand out. At my previous internship, I attempted to convince my manager to set up a small test environment to develop such things as authentication for employees of the company using Neo.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
