### ISSUE TITLE
I want to go to NEO DevCon! My email: mark.loonen@gmail.com

### ISSUE THREAD

**Issue by mrk1media** [neo-project/neo.org#441]
Developer and NEO supporter.
Active in community, CoZ, and events.
Currently working on python and NEO based video service.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?

**Comment by mrk1media** [comment]
Hi! Sorry I dont have projects on GitHub.
Still learning and being involved is my main focus. Went to the Amsterdam meetups but was compact so would love to see a DevCon of bigger size.
Thanks for your consideration!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
