### ISSUE TITLE
I want to go to NEO DevCon! My email: leo@thortoken.com

### ISSUE THREAD

**Issue by reolong** [neo-project/neo.org#444]
I am a founding developer at www.thortoken.com. We are looking to be the first "NEO smart economy" company to come out of San Francisco. I worked with our CTO "mattmo" and contributed to the Lucky NEO open source project - https://github.com/mmoravec/luckyneo. All Thor development can be found here: https://github.com/thortoken.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
