### ISSUE TITLE
I want to go to NEO DevCon! My email: yjkimjunior@berkeley.edu

### ISSUE THREAD

**Issue by yjkimjunior** [neo-project/neo.org#445]
I am a senior at UC Berkeley and incoming backend engineer at a YC backed payments gateway startup (they started as a cross border remittance app using bitcoin but were a little early). I am a blockchain enthusiast and have been learning Solidity by jumping straight in the deep end by getting involved with a couple hackathons, most recently at WCEF.co in SF. I'm a big fan of some upcoming NEO projects, namely Qlink and DeepBrainChain which are my primary short term motivations for wanting to attend this devcon.

Some links:
https://devpost.com/software/coda
https://devpost.com/software/space-dao

Best,
Kim

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
