### ISSUE TITLE
I want to go to NEO DevCon! My email: kkn24@cornell.edu

### ISSUE THREAD

**Issue by kevink94** [neo-project/neo.org#446]
Hi,

I am a student at Cornell University looking forward to learning about solidity. I have been involved in the space for 2 years and have helped a variety of startups launch successful ICO's, in addition to joining the CoinAgenda conference team in Barcelona and Las Vegas. I have attended 5+ blockchain specific hackathons and I'm looking to start a new project in the space to help musicians get paid.

Thank you for the initiative!

Kevin

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
