### ISSUE TITLE
I want to go to NEO DevCon! My email: msharris@berkeley.edu

### ISSUE THREAD

**Issue by mharris100** [neo-project/neo.org#447]
Hey! I am Sophomore Computer science student at UC Berkeley. I have been fascinated by cryptocurrency since I learned about it last summer and I have lots ideas for projects that can use blockchain and specifically NEO. This semester I am taking a class on blockchain development so I would love to go to DevCon to meet some people I can collaborate with!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
