### ISSUE TITLE
I want to go to NEO DevCon! My email: jlin2700@gmail.com

### ISSUE THREAD

**Issue by jlin27** [neo-project/neo.org#448]
Hi! I'm a Content Developer at Udacity (https://www.udacity.com/), an Educational Tech company. My primary focus is teaching how individuals (beginners through advanced) mobile (Android) development. I'm a beginner developer in the blockchain space, eagerly learning and would love to be able to teach and spread the word about NEO!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
