### ISSUE TITLE
I want to go to NEO DevCon! My email: tianqin@berkeley.edu

### ISSUE THREAD

**Issue by spockqin** [neo-project/neo.org#449]
I am a sophomore Electrical Engineering and Computer Science student at UC Berkeley and a Software Developer at Blockchain at Berkeley. I've been developing web apps interacting with Ethereum and Tendermint. Main skills include Node, React, Mongo, Javascript, Python, Java, Solidity, and Linux administration. Below are projects I've done:

1. A motivation app where smart contracts settle bets [bet-on-it](https://github.com/spockqin/bet-on-it). This project won first prize at Cal Hacks
2. A forum where quality posts are rewarded by smart contracts [eth-forum](https://github.com/spockqin/ethereum-forum)
3. A web app that visualizes cryptocurrency price trends and run arbitrage algorithms [R-bitrage](https://github.com/spockqin/crypto-price)

I'm also currently working on a Qualcomm blockchain project whose details cannot be revealed and am about to start working on a decentralized insurance project. I'm very excited about blockchain technology and hope to have a chance to attend DevCon to grow, observe, and connect.

I appreciate the opportunity!

Sincerely,
Tian

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
