### ISSUE TITLE
I want to go to NEO DevCon! My email: dsherman@sdsu.edu

### ISSUE THREAD

**Issue by Nideesh1** [neo-project/neo.org#452]
Hi, 

I'm interested in developing smart contracts for NEO. I have already run some on the Ethereum Ropsten and Rinkeby testnet. You can check my github to see my solidity development: https://github.com/Nideesh1/SolidityPractice.

I want hands on experience on the NEO blockchain. I have industry experience working on Javascript and Java.
Email my ticket at: dsherman@sdsu.edu

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
