### ISSUE TITLE
I want to go to NEO DevCon! My email: jshendwg@gmail.com

### ISSUE THREAD

**Issue by jshendwg** [neo-project/neo.org#457]
Hi, I am a software developer by trade for over 15 years and recently dived into blockchain tech over the last year and half.  I am an expert in mobile app development but don't have any blockchain projects on github yet (starting on one with a friend and looking to start others as well thus the interest in NEO).  Thanks

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
