### ISSUE TITLE
I want to go to NEO DevCon! My email: Janbodden@student.fullsail.edu

### ISSUE THREAD

**Issue by jbblockchain** [neo-project/neo.org#458]
To whom this may concern,

First I would like to thank you for the opportunity of attending this event and open my horizons in this new technology of blockchain a very exciting one! My name is Jan and I am currently studying Film production at Full Sail university located in South Florida. I have been involved in the blockchain community for a year now, more on the side of investment side. I am very excited for a few projects that will decentralize the entertainment industry in which I'm studying for.

Below are the projects that i'm involved in:
https://github.com/flixxo
https://github.com/imusify

Thank you again!

Jan

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jbblockchain
