### ISSUE TITLE
I want to go to NEO DevCon! My email: jacobtylorcamacho@gmail.com

### ISSUE THREAD

**Issue by JTCAMACH0** [neo-project/neo.org#459]
I am a aspiring developer and student of the Android Nano Degree I love the block chain and I'd be honored to attend this conference!

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.
