### ISSUE TITLE
 I want to go to NEO DevCon! My email: smcginn6@my.smccd.edu

### ISSUE THREAD

**Issue by seanxyz1** [neo-project/neo.org#460]
I am attending College of San Mateo with plans to transfer to UC Berkeley. I am majoring in Computer Science with a focus on Java and Python.

I am very interested in the NEO project and would love the opportunity to learn more about it from the developers working on this project.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
