### ISSUE TITLE
I want to go to NEO DevCon! My email: polotx2000@gmail.com

### ISSUE THREAD

**Issue by Polotx2000** [neo-project/neo.org#461]
I am currently working with a team that will be creating a new coin that we are interested in releasing on the NEO platform. Our group is called the Black crypto group with well over 55,000 members. I am currently working under Charles Wu and Boyce Watkins. I have skills in various development departments and I think NEO fits our financial platform nicely. Looking forward to hearing from your team.

You can find our group here:

https://www.facebook.com/groups/blackcryptoinvesting/?hc_location=group

**Comment by Polotx2000** [comment]
https://www.facebook.com/groups/blackcryptoinvesting/?hc_location=group

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
