### ISSUE TITLE
I want to go to NEO DevCon! My email: iakarshfans@gmail.com

### ISSUE THREAD

**Issue by akarshlimitless** [neo-project/neo.org#462]
Hi I'm a student entrepreneur and a software developer with lots of experience in blockchain and is currently working on a crypto forecasting portfolio web application. I have been following NEO from when it was ANS.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.

**Comment by akarshlimitless** [comment]
avalsan@student.42.us.org

**Comment by chenzhitong** [comment]
You seem to have applied use avalsan@student.42.us.org. The Promotional Code has been sent to your mailbox, please check your mailbox.
