### ISSUE TITLE
I want to go to NEO DevCon! My email: kdgoodboy@gmail.com

### ISSUE THREAD

**Issue by kdhenhao** [neo-project/neo.org#464]
I am currently a full stack developer in Toronto who has 5 years working experiences and has involved in various IT projects mainly focused on JAVA and python. I am really interested in blockchain especially neo blockchain, I understand the technology and would like to contribute to it. Myself is also a miner. I really hope to participate in the neo dev conference, contribute to neo blockchain and the community. Thank you!

Justin

**Comment by kdhenhao** [comment]
Hi Zhitong,
Thanks for the reply. Here is my linkedin, I haven't update it for a while:
https://www.linkedin.com/in/dingkong/

The attached is the screenshot of the current project I am working on.

I really hope to attend the DevCon and be the part of the NEO community.
Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
