### ISSUE TITLE
I want to go to NEO DevCon! My email: j28tan@edu.uwaterloo.ca

### ISSUE THREAD

**Issue by jonathantan** [neo-project/neo.org#468]
Hi, I'm a senior in Computer Engineering from the University of Waterloo in Canada. I've been developing blockchain apps for about a year now and have been a follower of NEO since it was AntShares back in 2014. I plan would build my next app on top of NEO and would love to be invited to the NEO dev summit to meet the developers of this awesome project! I look forward to more great things coming from NEO that will shape the future :)

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
