### ISSUE TITLE
I want to go to NEO DevCon! My email: laukevin3@gmail.com

### ISSUE THREAD

**Issue by laukevin3** [neo-project/neo.org#469]
Hi - I graduated from UC Davis with a major in computer science and math. I am also a crypto investor. Zhao Chen recommended that I apply for the developer position as I have a unique background in investing and programming. I’m currently a student at Stanford. Here is a link to the blockchain projects I’m part of:

https://github.com/neonexchange/neo-ico-template

https://github.com/0xProject/contracts

Best,
Kevin

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
