### ISSUE TITLE
Website is loading very slow. Add Cloudflare?

### ISSUE THREAD

**Issue by metachris** [neo-project/neo.org#47]
The website of neo.org is often loading very slowly. 

A free and quick solution would be to add Cloudflare in front of it, and have the Cloudflare CDN deliver the content. https://www.cloudflare.com/plans (the free plan would suffice)

**Comment by anfn101** [comment]
@chenzhitong @MingxiaYan What are your thoughts?

**Comment by chenzhitong** [comment]
neo.org contains the database, even if put the static file on the CDN, I estimate the loading speed will not improve. And after using CND website update will become more cumbersome, there is no better way to find a solution. @anfn101 @metachris

**Comment by ianaz** [comment]
What about caching DB requests if that's the issue? Right now, with people waiting for the news to come out, it's loading indefinitely

**Comment by chenzhitong** [comment]
I've configured the CDN and put the static files(img, css, js) on the Azure CDN，I have been deployed on the official web now. Run for a while and then look at the effect. https://github.com/neo-project/neo.org/pull/693

**Comment by chenzhitong** [comment]
This is the image of the official website deployed in Azure Hong Kong. It uses the same CDN scheme, and I'm testing the speed of Azure Hong Kong and Aliyun Beijing. http://neo.eastasia.cloudapp.azure.com/
