### ISSUE TITLE
I want to go to NEO DevCon! My email: apiswswsw@gmail.com

### ISSUE THREAD

**Issue by swswsw** [neo-project/neo.org#472]
I had been working on blockchain or cryptocurrency related projects for a while.   We had worked on blockchain startup doing permissioned distributed ledger before.  

Someo f the opensource project related to blockchain/distributed ledger space.  
https://github.com/swswsw/generic_token
https://github.com/swswsw/etherpricing
https://github.com/swswsw/stellarj
https://github.com/swswsw/coinpubnub

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
