### ISSUE TITLE
I want to go to NEO DevCon! My email: thinhdho@berkeley.edu

### ISSUE THREAD

**Issue by billytho1911** [neo-project/neo.org#473]
I am a junior student in Joint Chemical Engineering/Materials Science Engineering at UC Berkeley. I am interested in using blockchain technology to implement it in the field of Chemical Engineering. I took some cryptography classes online from Coursera and EdX. I am enrolling in DeCal Blockchain at UC Berkeley now. I did not get involved in any blockchain project yet but I hope I will get involved into one in the future.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
