### ISSUE TITLE
I want to go to NEO DevCon! My email: m.w.f.van.der.deen@st.hanze.nl

### ISSUE THREAD

**Issue by Mardcrypto** [neo-project/neo.org#476]
My name is Mart van der Deen, I'm a serial entrepreneur/student (almost graduated: February). I am a distributor of high quality Italian wine in the Netherland, working on a start-up called Blue Bite, a teeth whitening gadget and student of the Hanze Hogeschool in Groningen studying International Business and Management. 

No I am not a developer but I would love to go to the NEO DevCon to get more insight in the space/projects to bring my business to the next level. I'm already talking with some developers on how to implement Blockchain to my businesses: RFID chipping is one of them.

I have also done a livestream during the Amsterdam Meetup: https://www.youtube.com/watch?v=D7uiMBdUQLc&t=2641s for Chicocrypto aka Tyler Swope. He interviewed a lot of the founders of projects build on NEO Ecosystem and Da Hong Fei himself. He is a friend of mine and will take me to the DevCon.

I would be honoured to get a ticket for the neo DevCon! 

Best Regards,

Mart van der Deen

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Mardcrypto
