### ISSUE TITLE
I want to go to NEO DevCon! My email: thainq@blockpass.org

### ISSUE THREAD

**Issue by thainq-ibl** [neo-project/neo.org#477]
I'm Thai Ng, I'm a senior blockchain developer, our project we working on is Blockpass.

Blockpass is a passport certificate build on the blockchain.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
