### ISSUE TITLE
 want to go to NEO DevCon! My email: glambeth@umich.edu

### ISSUE THREAD

**Issue by glambeth** [neo-project/neo.org#478]
Hi, I'm George. I study CS and have been involved in crypto since 2013. I've done security audits for many ERC-20s (>1b in value). 

I've contributed to these repos:

- https://github.com/0xProject/contracts
- https://github.com/ConsenSys/smart-contract-best-practices
- https://github.com/blockstack/blockstack-browser
- https://github.com/glambeth/zecProxy

I'm interested in consensus algorithms.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
