### ISSUE TITLE
I want to go to NEO DevCon! My email: ceo@sassytags.com

### ISSUE THREAD

**Issue by richkuo** [neo-project/neo.org#479]
I am a full stack web and mobile app developer.

I've done 100% of the technical work for www.bringmethat.com

I've also participated on SO: https://stackoverflow.com/users/920821/richard-kuo

I am looking to incorporate blockchain/smart contract technology into current and future applications I work on.

<img width="867" alt="screen shot 2018-01-22 at 12 09 10 pm" src="https://user-images.githubusercontent.com/880112/35233800-21a2c8d6-ff6d-11e7-9ab8-561dd229b017.png">

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.

**Comment by richkuo** [comment]
Please delete this issue
