### ISSUE TITLE
I want to go to NEO DevCon! My email: jowelbodden@student.fullsail.edu

### ISSUE THREAD

**Issue by jowbod** [neo-project/neo.org#480]
To whom this may concern,

First, I would like to thank NEO Devcon for the opportunity for students to attend this blockchain technology event.  My name is Jowel and I am currently studying Music Business at Full Sail University located in South Florida. Over the past year, I have gotten heavily involved in the blockchain space by investing and participating in projects that are finding solutions to the many entertainment industry problems. What interests me the most about attending NEO Devcon is the fact that I believe NEO has more potential than other blockchains to become the go to platform for the entertainment industry due to TPS, consensus, and scalability. Some of the projects that I have been involved with are:

https://github.com/Opus-foundation/
https://github.com/ujomusic
https://github.com/flixxo
https://github.com/imusify

Thanks again for the opportunity.

Jowel

P.S My brother has already been accepted. His email is janbodden@student.fullsail.edu. If I get accepted I will be attending with him.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
