### ISSUE TITLE
I want to go to NEO DevCon! My email: mittendorf@post.harvard.edu

### ISSUE THREAD

**Issue by superclarkan** [neo-project/neo.org#482]
Hi - I graduated from Harvard with a major in computer science and math. I am also a crypto investor. A team member recommended that I apply for the developer position as I have a unique background in investing and programming. 

I have over 10 years of experience in software development and a similar amount in investing side.

Best,
Alex

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
