### ISSUE TITLE
I want to go to NEO DevCon! My email: cogorman17@berkeley.edu

### ISSUE THREAD

**Issue by cogorman2017** [neo-project/neo.org#483]
I am currently a senior at UC Berkeley studying Economics, with a passion for fintech. Although I have not been active in developing my own projects, over this past year, I have been working with a late stage tech VC fund in San Francisco, exposing me to the opportunities and innovation of cryptocurrencies and blockchain technology, ultimately developing into a growing interest in the space. I am also currently working with a family office in San Francisco looking to institutionalize their capital as they pivot into a full-fledged real-assets focused private equity fund. In relation to our work, I would love to learn more about ICOs and the tokenization of real assets. It would be a privilege to attend this conference and learn from some of the best in the industry.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
