### ISSUE TITLE
I want to go to NEO DevCon! My email: pwhizzard@gmail.com

### ISSUE THREAD

**Issue by pwhizzard** [neo-project/neo.org#485]
I've been working in tech for the past 10 years and have done so in a lot of different positions. 
Quick background:
I went to college for Math and C.S.
I was a network engineer for Cisco
I started 5 years ago at Meraki (now owned by Cisco) as a network engineer
I moved to product management Meraki
I'm now a software engineer at Meraki

I specialize in full stack development (React, Redux, and Ruby on Rails) and making solutions that automate and simplify processes for enterprise customers internationally.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
