### ISSUE TITLE
I want to go to NEO DevCon! My email: samridh@berkeley.edu

### ISSUE THREAD

**Issue by samridhsaluja** [neo-project/neo.org#486]
As a senior at UC Berkeley, I have worked closely with distributed apps and have experience building full stack applications. My area of interest is security, which I developed through teaching security at Berkeley and taking advanced cryptography courses. I would love a chance to attend this conference and learn from the world's best blockchain developers.

**More info about my past work is at www.samridh.me** 

Thank you!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
