### ISSUE TITLE
I want to go to NEO DevCon! My email: solomanasoloman@gmail.com

### ISSUE THREAD

**Issue by SalSoloman** [neo-project/neo.org#487]
An apprentice at Learners Guild bootcamp. Learning Javascript, Node.js and other technologies to build a full stack web app. Very new to the blockchain space and would love to learn more about it. 
Currently not involved in Blockchain projects

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
