### ISSUE TITLE
I want to go to NEO DevCon! My email: whaddoc1@students.kennesaw.edu

### ISSUE THREAD

**Issue by atlasphoenix** [neo-project/neo.org#489]
Hello my name is Will! I'm a computer science major at Kennesaw State University, a rising research institution in Kennesaw GA USA. My area of focus is app development. My goal is to develop apps that seamlessly work between mac, pc, android and IOS.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
