### ISSUE TITLE
I want to go to NEO DevCon! My email: miguelzferr@gmail.com

### ISSUE THREAD

**Issue by gonmf** [neo-project/neo.org#491]
I'm a core infrastructure developer, involved in distributed systems, platforms and compiler. Recently started in the crypto and blockchain space, mostly with Ethereum, now switching to Neo.
I am active in the crypto comunity, and currently developing an exchange, and an online gambling website (both private source for now, sorry).

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
