### ISSUE TITLE
I want to go to NEO DevCon! My email: ngkenneth@gmail.com 

### ISSUE THREAD

**Issue by iconcells** [neo-project/neo.org#492]
I am a developer who works in blockchain development on the healthcare.  The links to GitHub blockchain projects that I am working on is 
https://github.com/WCEF/wellweb
https://github.com/Nyceane/InfiniBlocks
.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
