### ISSUE TITLE
 I want to go to NEO DevCon! My email: saalaoudi@ucdavis.edu

### ISSUE THREAD

**Issue by malaoudi2019** [neo-project/neo.org#494]
I am working on integrating one small part of the biomedical industry (lab tests and research) into the blockchain to create a collaborative movement for one common mission. Starting with decentralizing lab tests & research on an open platform to allow other colleges/institutions to get involved and help with the direction and quality of the research.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.

**Comment by malaoudi2019** [comment]
I still did not receive anything yet. Can you double check?

**Comment by chenzhitong** [comment]
I have send the email again.

**Comment by malaoudi2019** [comment]
Hi chen,

I still did not get anyting :( Can you send just the code ?
