### ISSUE TITLE
I want to go to NEO DevCon! My email: jmb140730@utdallas.edu

### ISSUE THREAD

**Issue by jaybutera** [neo-project/neo.org#495]
I'm a student of computer science with strong intention to create the next big NEO dapp. Experience in machine learning, Solidity contracts, and distributed systems.

https://github.com/jaybutera/SalesChain
https://github.com/jaybutera/tradebot

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
