### ISSUE TITLE
I want to go to NEO DevCon! My email: jeton_hoxha@student.uml.edu

### ISSUE THREAD

**Issue by jchoxha** [neo-project/neo.org#496]
Hi my name is Jeton. I'm currently studying computer science at the University of Massachusetts at Lowell. I'm extremely interested in blockchain technology and its capacity to change the world. Attending NEO DevCon would be extremely exciting for me as I've been following the NEO platform for quite some time and would love to be a part of future developments.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
