### ISSUE TITLE
I want to go to NEO DevCon! My email: avalsan@student.42.us.org

### ISSUE THREAD

**Issue by limitlessmanhattan** [neo-project/neo.org#497]
Hi! I'm a student at 42, Silicon Valley. Interested in blockchain and have been following NEO from the time it was ANS. Also want to be a part of City of Zion soon. Looking forward to see the latest updates and developments happening in NEO during the DevCon.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
