### ISSUE TITLE
I want to go to NEO DevCon! My email: 4303969@gmail.com

### ISSUE THREAD

**Issue by Clickbuyclick** [neo-project/neo.org#500]
Hi
I am the web designer, engineer,and the co-founder for CoinIran website. I would like to attend your upcoming NEO Conference. This would allow and help me and our site to provide more efficient and complete data to our users. 
Would greatly appreciate if you could consider and invite me to to this great conference 

Regards,

Coiniran.com

https://coiniran.com/en/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
