### ISSUE TITLE
 I want to go to NEO DevCon! My email: balaoudi@mail.sfsu.edu

### ISSUE THREAD

**Issue by malaoudi20** [neo-project/neo.org#503]
Dear NEO, 

Thank you so much for offering this valuable opportunity for students to get to know the future capabilities of NEO. 

I am currently learning Python, Kotlin, and C#, so I can create smart contracts and participate in NEO. However, being able to attend NEO DevCon is extremely beneficial for m future involvement and development with NEO. Furthermore, being able to network and get to know the leader in the platform is motivating and critical for my future plans. 

I am a follower, small investor and a believer in NEO's potential scalability, TPS, and consensus. I have been following NEO since it was ANS. 

Thank you!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
