### ISSUE TITLE
I want to go to NEO DevCon! My email: alextreece@utdallas.edu

### ISSUE THREAD

**Issue by alextreece** [neo-project/neo.org#504]

**Comment by chenzhitong** [comment]
Write down a brief self-introduction please.

**Comment by alextreece** [comment]
Sure. I'm the Director of our new blockchain initiative at the University of Texas at Dallas (https://en.wikipedia.org/wiki/University_of_Texas_at_Dallas). We are focused on training blockchain developers, producing projects on a variety of platforms (including NEO), and getting those projects funded and into the ecosystem. We also conduct educational events for the community.

Outside that, I'm involved with blockchain and smart contract development on a personal basis. Would love to learn more about the NEO ecosystem.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
