### ISSUE TITLE
I want to go to NEO DevCon! My email: matt@mtnlabs.io

### ISSUE THREAD

**Issue by MattNguyen** [neo-project/neo.org#511]
I'm a self-taught, full-stack developer with an interest in blockchain development. I've worked on front and backend, as well as experience building distributed systems. I have some blockchain projects listed on [MTN Labs](https://github.com/mtnlabs).

I'm also invested in NEO as well as other cryptocurrencies.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
