### ISSUE TITLE
I want to go to NEO DevCon! My email: shaurya@stanford.edu

### ISSUE THREAD

**Issue by shaurya** [neo-project/neo.org#513]
Hi, having worked in the startup ecosystem and having developed several full-stack apps, currently deployed and supporting thousands of DAUs, I am excited about the developments that blockchain and decentralization bring to our technological arsenal to tackle real-world problems. I have been in the crypto space since 2011 and have also published papers at the intersection of Crypto & Machine Learning. Recently, I have built expertise in the transportation space and would love to explore synergies there. This conference looks like an exciting place to delve into that further. Looking forward to hearing back.

Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
