### ISSUE TITLE
I want to go to NEO DevCon! My email: jnakano89@gmail.com

### ISSUE THREAD

**Issue by jnakano** [neo-project/neo.org#518]
Hi there!

My name is Jonhnson, I've been a Frontend developer for over 5 years and build mainly in javascript. I'm a huge fan of NEO and it's platform. I've been trying to learn using Neo-js from NPM and look forward to learning more about NEO development! 

Here is a link to a project I did at the Techcrunch Disrupt Hackathon:
https://github.com/sf-disrupt-hackathon/coachinga

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
