### ISSUE TITLE
I want to go NEO DevCon! My email: raingrove@gmail.com

### ISSUE THREAD

**Issue by petejkim** [neo-project/neo.org#52]
I created Cipher Browser, a mobile Ethereum wallet + Web 3 Dapp browser: https://www.cipherbrowser.com/

I'd love to learn more about NEO and see if I can build a similar client for NEO.

Other blockchain projects on GitHub: https://github.com/petejkim/wallet.ts

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
