### ISSUE TITLE
I want to go to NEO DevCon! My email willx1@protonmail.com

### ISSUE THREAD

**Issue by incepted** [neo-project/neo.org#521]
Interested in the java development portion of Neo.  Past work with JDK in this account.

**Comment by incepted** [comment]
Have spent time in the blockchain space and have have followed this project since Antshares along with attending the recent events in NYC and Seoul.  Looking to learn more about the upcoming projects to help engage the community on a technical level.  Have met a few of the team and look forward to meeting more for additional insight for the future of the platform.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
