### ISSUE TITLE
I want to go to NEO DevCon! My email: 100303817@alumnos.uc3m.es

### ISSUE THREAD

**Issue by Pabsm94** [neo-project/neo.org#522]
Hi!! I am an aerospace grad and Python junior software developer from Spain. I am currently finishing the  Machine Learning Nanodegree, and just finished the Deep Learning Nanodegree, offered at Udacity.com. I am also a great fan of the blockchain and cryptocurrency technology, with a passion on applying data science in Python towards the FinTech field.  In addition i would like to expand my professional career as blockchain developer/Engineer and I just signed up in BlockGeeks!!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
