### ISSUE TITLE
I want to go to NEO DevCon! My email: khari.washington@1stur.com

### ISSUE THREAD

**Issue by kbusiness10** [neo-project/neo.org#524]
I would like to attend Neo Devcon. I am a mathematician and developer who attended Oakwood University in Huntsville Alabama. I currently have invested in Neo and would like to network and see how what I know as a developer can be applied to the Neo blockchain. Thanks

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.
