### ISSUE TITLE
I want to go to NEO Devcon. My email address is cgu@ucdavis.edu

### ISSUE THREAD

**Issue by bch3nabo** [neo-project/neo.org#528]

**Comment by chenzhitong** [comment]
Write down a brief self-introduction please.

**Comment by bch3nabo** [comment]
Hi, I am currently a scientific researcher in the biotech community. The underlying technology behind Bitcoin and other crypto currencies are rapidly changing industries such as banking. I am interested to see if there are opportunities to apply the same type of technology in the biotechnology field.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
