### ISSUE TITLE
I want to go to NEO DevCon! My email is aman.sethi.work@gmail.com

### ISSUE THREAD

**Issue by thesurvivingloop** [neo-project/neo.org#53]
I am a senior software developer with over a decade of development experience. I work in the San Francisco Bay Area. 

I have been following NEO since the Antshares days and would love to begin developing. I attended the recent NEO meetup in SF. 

I would love to start developing for NEO.

Most of my development experience has been on system level programming and low level languages like C, C++. I also have work experience with C# . NET.

Here is my linked in profile:
https://www.linkedin.com/in/amanksethi/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @thesurvivingloop

**Comment by thesurvivingloop** [comment]
Thanks!
