### ISSUE TITLE
I want to go to NEO DevCon! My email: akilunov@ucdavis.edu

### ISSUE THREAD

**Issue by akilunov** [neo-project/neo.org#531]
I'm a DevOps engineer getting my MBA from UC Davis and am really excited about bitcoin and the future of blockchain technology! I'm also a founding member of our school's crypto-currency club, which strives to educate students on all things crypto!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
