### ISSUE TITLE
I want to go to NEO DevCon! My email: dliang5@ucsc.edu

### ISSUE THREAD

**Issue by TheFoodGuy** [neo-project/neo.org#533]
Hi, my name is David Liang. I currently attend UC Santa Cruz, and I am planning and working on implementing ARK's technology in unifying blockchains under its ecosystem in my software design capstone class. I am experienced in backend development mainly in data science related such as analyzing genomes for DNA breakages. 

https://github.com/zdolson/EthereumEnergyMicrotransactions 
https://github.com/zdolson/BlockchainHub (currently starting this month).

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
