### ISSUE TITLE
I want to go to NEO DevCon! My email: malvinyeung@gmail.com

### ISSUE THREAD

**Issue by malvinyeung** [neo-project/neo.org#534]
Hi!

I am a General Assembly and Code Fellows graduate of intensive bootcamps in California and Seattle for Front-End Development and UX Design. I am also a crypto investor and part of many syndicates. I have much interest in the NEO platform for dapps and was recommended to apply for the developer position as I have a unique background in programming and blockchain tech knowledge. I’m currently a student at Stanford while working on side projects like bidapp.io & gemswallet.io (both not released yet). I'm also doing some voluntary work while I learn for Jesse Leimgruber: https://github.com/hellobloom/core

Best,
Malvin

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
