### ISSUE TITLE
I want to go to NEO DevCon! My email:baillot@gmail.com

### ISSUE THREAD

**Issue by YohanBaillot** [neo-project/neo.org#536]

**Comment by YohanBaillot** [comment]
I am a professional with 20 years experience in Augmented reality development and I would like to use blockchain in AR/VR projects and AR framework we are building. We would be very interested in a collaboration bring together our expertises

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
