### ISSUE TITLE
I want to go to NEO DevCon! My email: bellokano@gmail.com

### ISSUE THREAD

**Issue by bellokano** [neo-project/neo.org#538]
I am from northern Nigeria with Highly interest in changing lives using blockchain technology. I have MBA in business admin. I am entrepreneur learning to invest in Blockchain tech.

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?  Alternatively, you can use the e-mail at the end of Edu and apply for student tickets.
