### ISSUE TITLE
I want to go to NEO DevCon! My email: aaronharris@csus.edu

### ISSUE THREAD

**Issue by Aaronleeart** [neo-project/neo.org#539]
My email: aaronharris@csus.edu

**Comment by chenzhitong** [comment]
Write down a brief self-introduction please.

**Comment by Aaronleeart** [comment]
Hello,

My name is Aaron Lee Harris, I am currently a Senior pursuing a bachelor degree in graphic design from Sacramento State. I am passionate about the concept of design; the luxury of constant improvement, refinement, and variations. Great design is the framework for intelligence and culture. Great design is the framework for intelligence and culture. Art and design have separate roles but they can beautifully function together like John Coltrane and his tenor saxophone. I believe I can learn a lot about your great organization because I am a creative individual, seeking new opportunities, and experienced in several disciplines. I am an avid learner, self-starter, and helpful team member. Thank you for your time and consideration.

Respectfully, 

Aaron Lee Harris

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
