### ISSUE TITLE
I want to go NEO DevCon! My email: aaronbesson@gmail.com

### ISSUE THREAD

**Issue by MorpheusAdministrator** [neo-project/neo.org#54]
My name is Aaron Besson and I am the creator, designer and co-developer of the new Morpheus Wallet for NEO/GAS and other blockchain assets.

![screen shot 2018-01-03 at 7 36 27 am](https://user-images.githubusercontent.com/13420186/34519089-d970b23a-f058-11e7-95fc-ad0d0562123e.png)

Morpheus allows you to send and receive NEO and other NEP tokens with popular currencies and tokens like Bitcoin, Litecoin, Monero Ethereum, ERC-20 tokens and more to be added soon. I am a UX/UI designer and developer with 20 years experience in website design/development and software design/development. I am a natural problem solver and love a new challenge which is why I decided to get into NEO blockchain software development 8 months ago. Below is a link to our Github repo and Twitter with a video of our wallet.

https://github.com/MorpheusWallet/beta/tree/aaron
https://twitter.com/MorpheusWallet/status/947562637180784640

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @MorpheusAdministrator

**Comment by MorpheusAdministrator** [comment]
Thank you!! I have redeemed the promotional code and got my ticket. I look forward to meeting you all at Neo Dec Con 2018 so I can thank you in person.
