### ISSUE TITLE
I want to go to NEO DevCon! My email: zdolson@ucsc.edu

### ISSUE THREAD

**Issue by zdolson** [neo-project/neo.org#541]
Hello! My name is Zachary Olson, I am currently a senior at the University of California, Santa Cruz. For my Senior Design series, I have worked with a sponsored project that focused on incorporating blockchain technology/tokenization into energy monitoring systems, as well as now pursuing using Ark technology to unify the many existing blockchains under an adaptive and versatile ecosystem.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
