### ISSUE TITLE
 want to go to NEO DevCon! My email: bcwan@ucsc.edu

### ISSUE THREAD

**Issue by bcwan** [neo-project/neo.org#542]
My name is Brian and my interest is in full stack. I have been researching and investing in cryptocurrency, and I've been looking into NEO quite some time. In the future, I plan to make a project in regards to blockchain technology, and learning more about NEO from the experts would definitely help me.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
