### ISSUE TITLE
I want to go to NEO DevCon! My email: luke.xie@sloan.mit.edu

### ISSUE THREAD

**Issue by ChangWufei** [neo-project/neo.org#543]
Hi there!

I'm at MIT Sloan and have been investing in and working on blockchain projects since last year.  Just came back from the Bitcoin Conference in Miami and excited to meet more blockchain believers, especially in Asia!

Thank you,
Luke

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
