### ISSUE TITLE
I want to go to Neo Devcon! My email: yangmic1@gmail.com

### ISSUE THREAD

**Issue by bebop23** [neo-project/neo.org#548]
My name is Michael and I've been involved with crypto since 2011.  I've been following Neo since it was called Antshares!  I've been getting involved with Origins: https://github.com/OriginProtocol and I am looking forward to seeing how can start developing on the Neo platform.  I'm an enterprise software engineer with 10 years of experience.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
