### ISSUE TITLE
I want to go to Neo Devcon! My email: vilatran@ucsc.edu

### ISSUE THREAD

**Issue by vtran1228** [neo-project/neo.org#550]
Greetings! My name is Victoria Tran, I am a 3rd-year CS student at the University of California, Santa Cruz. My interests and technical experience stem from full-stack development and Android mobile applications. I have been researching into cryptocurrency and NEO recently in order to better understand what I'm investing my time and assets in.

Currently, I am working on a sponsored project for my Capstone Design Series. This is focused on finding the intersections between energy monitoring systems and blockchain tokenization. We are also thinking about utilizing Ark's technology to interface with many already existing blockchains at the convenience of an ecosystem that's easy to manipulate and manage. If given the chance to attend this event, having expert insight about what makes NEO special, their current interests, and what their future implementations could involve, would be immensely helpful to our Capstone project.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
