### ISSUE TITLE
I want to go to NEO DevCon! My email: mkshelar@yahoo.com

### ISSUE THREAD

**Issue by mshelar** [neo-project/neo.org#551]
I stands at the forefront of the fastest moving security landscape. I have spent the past five years evangelizing an application security program and has helped position my organization as a leader in implementing security in the Health Care applications.

I am interested to work on blockchain project and interested to attend NEO conference to explore possibility of developing blockchain applications based on NEO platform.

**Comment by mshelar** [comment]
You can read some of my Blogs @ http://universal-idea.blogspot.com/

**Comment by chenzhitong** [comment]
You contribute less on GitHub. Can you provide other links or screenshots that prove you are a developer?
