### ISSUE TITLE
I want to go to NEO DevCon! My email: rshahatit@berkeley.edu

### ISSUE THREAD

**Issue by Rshahatit** [neo-project/neo.org#552]
Hello, I am a senior at UC Berkeley majoring in Cognitive Science. I got into the crypto scene about a year ago. I wanted to really understand the fundamentals so I applied for the blockchain decal held by Blockchain at Berkeley and will be taking that this semester. I have read some white papers on various crypto currencies. I have not started active development yet, but I hope to very soon. One thing I appreciate about NEO is the ability to develop in multiple languages. I had heard about you guys when you were still called AntShares. I plan on also applying to blockchain at Berkeley, volunteering at conferences for blockchain, and competing in blockchain hackathons.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
