### ISSUE TITLE
I want to go to NEO DevCon ! My email : Denuit90@gmail.com

### ISSUE THREAD

**Issue by MaximeDenuit** [neo-project/neo.org#555]
I'm a developer who graduated in Computer Science last year, now working for a mobile development company ! I'm also known as M_Nightly.

I'm also working on a dApp on the NEO blockchain.. More information soon :) 

I'm currently working on a Xamarin NEO wallet with AboimPinto, Phyros and lostfella.

I'd LOVE to come to the NEO DevCon !

.NET / Xamarin / Web developer

You can check my github and here is my gitlab for extra dev
https://gitlab.com/DenuitMaxime

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
