### ISSUE TITLE
I want to go to NEO DevCon!!! My email: chian111@mail.chapman.edu

### ISSUE THREAD

**Issue by nobutakahemmi** [neo-project/neo.org#556]
Hi NEO DevCon,

I am a huge fan of NEO and interesting in developing a deeper knowledge of what NEO can do and how I can be involved with the project. 
My area of study is entrepreneurship and marketing, and for the last 14 months I have been involved with blockchain technology and developing and understanding. I have also worked with several developers to start small projects on how we can build smart contracts and on my side, how we can build a business. 
I am also building up my knowledge for an educational component around cryptocurrencies and blockchain technology. Would love to go to Neo DevCon!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.

**Comment by nobutakahemmi** [comment]
Thank you.
