### ISSUE TITLE
I want to Go to Neo DevCon! My email: GouthamSwaroop.Beese@students.globeuniversity.edu

### ISSUE THREAD

**Issue by nep5beesetty** [neo-project/neo.org#558]
I'm a MBA student and a fulltime Systems Analyst with an undergraduate degree in Finance, now working for a Tax & Accounting firm. 

I am well versed with Python and I would like to create a dApp of my own on the NEO blockchain. :)

I'd LOVE to come to the NEO DevCon !

Scalable Blockchains with decentralized consensus is the future and I would love to be part of a platform that is trying to bring compliance to the mass market.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
