### ISSUE TITLE
I want to go NEO DevCon! My email :  johnniy5@me.com

### ISSUE THREAD

**Issue by 4math2379** [neo-project/neo.org#56]
Heya  !

As a Neo Supporter i wanna be here ! 

I'm a Smart contract developper , using in the future blockchain development and Drones.
see stuff at www.rahma.io.

Hope see you at Dev con

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @4math2379

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?

**Comment by 4math2379** [comment]
Hello. 

What do you mean ? Why ask this question ?

**Comment by 4math2379** [comment]
Dude why come here argue about that. I am a supporter of Neo. An holder , and Smart contract engineer. You think I’m not eligible for the con ?

**Comment by TheCoinJunkie** [comment]
According to the rules your not

**Comment by TheCoinJunkie** [comment]
The free tickets are not for NEO supporters, they are for devs who have contributed to the github. You have not !!!

**Comment by 4math2379** [comment]
You should calm yourself. 
Read the paste here : http://devcon.neo.org

I pasted for you « Neo Smart Economy is excited to announce the first NEO Developers Conference which will take place on January 30-31, in San Francisco.
    With multiple sessions and workshops NEO DevCon is bringing the NEO community together for a 2-day conference full of innovative ideas and projects, featuring many top speakers from the Blockchain space.
    Come and join us to learn about the existing and upcoming NEO based projects, meet leading developers from different parts of the world and become a member of the global NEO community！« 


Si your the person who made the rules and decide ? 
Regards

**Comment by 4math2379** [comment]
@chenzhitong

**Comment by TheCoinJunkie** [comment]
Your more than welcome to go to the event as anyone is. But i have seen many people who were denied a ticket because they have are not a neo dev. Yet you host a bs website on github and your all the sudden a developer more deserving then others ?

**Comment by 4math2379** [comment]
I’m sincerely sorry for your fiend. 
But I made a demand here. I said i’m A developer with smart Contract. And they send me an invite. If you have a reclamation you should mail or ask Neo organisation. 
If you can please stop be aggressive with me it can be cool. 
Regards

**Comment by TheCoinJunkie** [comment]
Nobody is being aggressive. I am just stating your not a developer and you recieved your ticket under false pretenses. It isn't about a friend or anything like that. Your not a developer bottom line you lied and said you are

**Comment by 4math2379** [comment]
I’ don’t have to justified my dev activities with you. As I post in my 1srt post here i’am a smart contract developper. And with an associate we made a smart contract audit company. We wan’t to integrate Neo. 
That s it point. 
I never said anywhere I am a Neo Dev officially. 
You should again calm yourself.

**Comment by TheCoinJunkie** [comment]
So you deserve to go because you know how to be shady and make yourself look like something your not ? My posting here is nothing against you. It is they neo is not following their own rules to hand out these tickets. 
Do you think it is right that numerous others have been denied because they have no verifiable neo developer commits but others are given tickets who also have no verifiable commits either ? Why do you deserve to go vs someone else ?

**Comment by TheCoinJunkie** [comment]
Thw deciding factor was not if you asked for a ticket and were interested in going. It was if you were a neo developer and you are not

**Comment by TheCoinJunkie** [comment]
The  deciding factor was not if you asked for a ticket and were interested in going. It was if you were a neo developer and you are not

**Comment by 4math2379** [comment]
You should ask Neo. 
@chenzhitong ?

**Comment by chenzhitong** [comment]
As long as he's a developer, he doesn't have to be a NEO developer. I will look at the GitHub of each submitter, and if there is no contribution, I cannot send him tickets. Others have Repositories, Stars and Followers in his GitHub. But you don't have any Repositories in GitHub. You should reflect on yourself instead of questioning others. @TheCoinJunkie
