### ISSUE TITLE
I want to go to NeoDevcon! My Email: brianrod1@berkeley.edu

### ISSUE THREAD

**Issue by dtmpower2** [neo-project/neo.org#560]
Hello! I am an educator and would love to learn more about Blockchain technology and how I can integrate it into my field of study. I believe that blockchain will play a big role in the future of our society. 

Thank you so much!

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
