### ISSUE TITLE
I want to go to NEO DevCon! My email: neyroud@yahoo.com

### ISSUE THREAD

**Issue by Telemarking** [neo-project/neo.org#561]

**Comment by chenzhitong** [comment]
Write down a brief self-introduction and area of development you're good at. And write down links to GitHub blockchain projects that you are involved in.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
