### ISSUE TITLE
I want to go to NEO DevCon! My email is millsc@student.ncmich.edu

### ISSUE THREAD

**Issue by nathanielmcgann3** [neo-project/neo.org#563]
Hello, my name is Nate! I am a 22 year old entrepreneur from Northern Michigan and I have travelled all the way to California to go to NEO DevCon! I have owned/ran multi business that have done 100’s of 1,000’s in sale revenue and I am also an investor. 

I started investing in Blue Chip stocks a few years back and eventually got into foreign currency trading which lead me to crypto currency trading/investing. I currently am personally assisntanting my boss named George who is a 7 figure crypto investor and a computer programmer out of Michigan University. 

He has mentored me the last year in the crypto space and now we are trying to go to the next level. I would love to attend NEO DevCon this week and be able to learn more able the technology/blockchain and network with others in the community. 

Thank you for the opportunity to qualify for a free ticket! 

Hope to see you there,
     Nate

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.
