### ISSUE TITLE
I want to go to NEO DevCon! My email: matthew@tryeats.com

### ISSUE THREAD

**Issue by chuninator** [neo-project/neo.org#566]
4+ years iOS Swift and Javascript development. Currently building an open and accessible food marketplace (Eats closed repo) allowing anyone to grow food at home and sell it to their community. 我是华人。现在我住在夏威夷。

**Comment by chenzhitong** [comment]
欢迎参加DevCon，促销代码已经发送到了你的邮箱中，请注意查收。另外祝贺你获得了我们最后一张免费票（如果之后我们不再追加的话）。
