### ISSUE TITLE
I want to go to NEO DevCon! My email: gong.jim@gmail.com

### ISSUE THREAD

**Issue by jimgong92** [neo-project/neo.org#567]
3yr fullstack product dev (currently at Twitch for 1.5 years). Specialize in UI/design.

First invested in crypto space in winter 2012 (BTC)

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
