### ISSUE TITLE
I want to go to NEO DevCon! My email: luxmidutt@loadtap.com

### ISSUE THREAD

**Issue by luxmidutt** [neo-project/neo.org#568]
Hi,  our company is Loadtap and we are an enterprise SaaS for logistics. I am CTO at Loadtap and my development focus is distributed systems using Java and Scala (10+years), and full stack using MEAN stack (3+ years). I previously worked for Apple as a senior software developer. We are looking at NEO as a platform to implement blockchain for our current software that is already sold within logistics in the US. Logistics and truck transportation in the US has a huge need for blockchain as all of the data is locked away in silos and the industry suffers from huge lack of transparency and accountability. 

Here is my linkedin: https://www.linkedin.com/in/luxmi-dutt-sharma-9611386/

Our company is based in Redwood City, CA so we are very close to where DevCon is being held.

I have attached a screenshot of our private repos to prove Loadtap has active projects in GitHub. 
![screen shot 2018-01-24 at 4 03 37 pm](https://user-images.githubusercontent.com/39710/35363717-361391ec-0120-11e8-843c-e9879f4957ba.png)

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。

**Comment by luxmidutt** [comment]
Does that mean I didn't make the cut? Ah man, is there anyway I can be put on a waitlist for the no shows? I was really hoping to go as our CEO us pushing us to incorporate blockchain within our current product. Please let me know. Thanks for offering free tickets either way; great thing that you guys did for developers and students.

**Comment by luxmidutt** [comment]
@chenzhitong I posted on reddit to ask someone that has a free ticket that isn't going. As you can see with the attached photo, some folks are trying to sell their promotional free tickets. We're trying to go to actually learn about NEO to see if it is a good platform for our technology. Please let us know if you guys open up more tickets or if there is a waitlist. Would really appreciate it. 
![screen shot 2018-01-26 at 9 42 36 am](https://user-images.githubusercontent.com/39710/35452985-66973ba8-027d-11e8-9653-f8f7bef49497.png)
