### ISSUE TITLE
I want to go NEO DevCon! My email: varun@skcript.com

### ISSUE THREAD

**Issue by varun-raj** [neo-project/neo.org#57]
Hi, 

I'm a blockchain engineer, working on Hyperledger currently. Working various client projects and some personal projects for my organization. 

Looking forward to seeing various potentials of Neo during the event. 

Check out my contributions to Hyperledger community at http://skcript.com/svr/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @varun-raj
