### ISSUE TITLE
I want to go to NEO DevCon! My email is angel.rho@outlook.es 

### ISSUE THREAD

**Issue by Angelrho** [neo-project/neo.org#571]
Hello, my name is Angel I am a 23 year old entrepreneur from Guadalajara, Jalisco.
I have been operating for approximately 2 years and now I am really interested in developing Neo for the future.

I am currently taking online trading classes from Houston to know how to better manage investments in the short, medium and long term.

I belong to a community called Mr.C01n where content is created of all kinds of topics related to Cryptocurrencies, making multiple conferences and courses.

I would love to attend NEO DevCon this week and be able to learn more with the technology / blockchain and network with others in the community.

mrc01n.com

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
