### ISSUE TITLE
I want to go to NEO DevCon! My email: myoung890@insite.4cd.edu

### ISSUE THREAD

**Issue by myo99** [neo-project/neo.org#572]
Hi. I am pretty new to development, but I took many online courses and am always trying to learn more! I hope to focus on C#, Javascript, and Node in hopes of understanding how to build dapps on the Neo blockchain. I want to contribute to NEO development!

Mike

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
