### ISSUE TITLE
 I want to go to NEO DevCon! My email: josecervantes@anfraj.com

### ISSUE THREAD

**Issue by Pakocon** [neo-project/neo.org#573]
Hi, im a dev currently in the subscribed teams in the 1st Neo Dev Competition, already in the Gitter forum.  I am a fullstack developer with more than 5years of experience in JS, C# Objective-C and Swift.  I would like to apply to this event so i can get the opportunity to get as much knowledge as possible and make meetups locally in Mexico to help other devs in the correct implementation of blockchain solutions based on NEO.  I really like the way you could use some of the major programming languages and the fast block generation, this will improve the adoption.

Thanks for your attention.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
