### ISSUE TITLE
I want to go to NEO DevCon: My email mark.tyneway@gmail.com

### ISSUE THREAD

**Issue by Tynes** [neo-project/neo.org#575]
I am a backend engineer for IBM Watson and am learning more about blockchain technology every day. Attending NEO DevCon would be a great way for me to network with the community and learn more about NEO. I've been working through Mastering Bitcoin but it's leaving me only wanting more. 

-Mark

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
