### ISSUE TITLE
I want to go to NEO DevCon! My email: lakerwiz@hotmail.com

### ISSUE THREAD

**Issue by lakerwiz** [neo-project/neo.org#581]
Hi there,

I've been a Frontend developer for over 2 years and build mainly in javascript, NodeJS and React. I am researching about blockchain technology in CrewFire team and I would like to use blockchain in some spercial projects we are building. Attending NEO DevCon would be a great opportunity for me to network with the community and learn more about NEO.

Thanks

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
