### ISSUE TITLE
 I want to go to NEO DevCon! My email: legary2@art.edu

### ISSUE THREAD

**Issue by jelaire** [neo-project/neo.org#582]
Hi, 
I am new to web development and did my first project last semester at Academy of Art University, where I am in the Web Design & New Media MFA program. I am constantly learning and understanding more about blockchain technologies, specifically on NEO. I work in entertainment and business development for startups. I am currently working with imusify and it would be an great networking opportunity for our team since I am local to the SF bay area to attend. 
Thank you, 
JL

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
