### ISSUE TITLE
I want to go to NEO DevCon! My email: ocbarone@dons.usfca.edu

### ISSUE THREAD

**Issue by ocbarone** [neo-project/neo.org#584]
I am a current third year undergraduate student at the University of San Francisco. I am a design major with an emphasis in graphic design interested in the learning and understanding of cryptocurrencies. I have been following NEO in particular and am interested in several of the projects that are being presented such as iMusify. 
I feel being a part of the conference will greatly enhance my knowledge of the upcoming trends and projects as well as perform as a guide for my future graphics path in the industry.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
