### ISSUE TITLE
I want to go to NEO DevCon! My email: cmalla9@gmail.com

### ISSUE THREAD

**Issue by chai2** [neo-project/neo.org#585]
Hi. I have been in development(Full stack) for almost 10 years. I took in-person Blockchain developer course at U.C Berkeley last year. I've been working on developer dApps for couple of months now. 

We are about to bootstrap an enterprise scale application and want to explore the possibilities and other support from Neo community about developing on an dApp on Neo ecosystem.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
