### ISSUE TITLE
I want to go to NEO DevCon! My email: salilvanvari@berkeley.edu

### ISSUE THREAD

**Issue by sirlittle** [neo-project/neo.org#586]
I am second-semester senior studying Computer Science at UC Berkeley and I have recently grown very fond of blockchain and its applications! I began researching the Neo project late last year and since discovering its high potential, I have been enthralled with creating something of my own and putting it onto the network. I would love to get a ticket for NEO DevCon so that I can learn how people are currently launching their own companies onto the NEO platform.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
