### ISSUE TITLE
I want to go to Neo DevCon! My email is hbeauton@mail.sfsu.edu

### ISSUE THREAD

**Issue by hbeau1234** [neo-project/neo.org#588]
Hi my name is Hannah and I’m an international relations major and I want to attend to learn more about how blockchain technology will effect the United States and it’s relations with other countries, along with how it will effect the US dollar and other currencies.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
