### ISSUE TITLE
I want to go to NEO DevCon! My email: jhallac@mit.edu

### ISSUE THREAD

**Issue by dqmaster12** [neo-project/neo.org#589]
Hi there,

My name is Jake Hallac and I am a 2nd-year MBA student at MIT. I’m a long-time hodler and advocate of NEO. I am also a research assistant for Professor Christian Catalini in the MIT Cryptoeconomics Lab and am active in the MIT Bitcoin Club. 

As a side note, I speak basic Mandarin and my soon-to-be fiancé is Chinese. :)

Best,
Jake

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。

**Comment by dqmaster12** [comment]
Hi,

Does this mean I did not get a free ticket?

Best,
Jake

**Comment by chenzhitong** [comment]
Yes, you're late.
