### ISSUE TITLE
I want to go to NEO DevCon! My email: neosaloon@gmx.com

### ISSUE THREAD

**Issue by gad0lin** [neo-project/neo.org#591]
I am developer interested in creating my own project on one of the leading blockchain platforms. NEO is one of the most interesting and uprising players, which seems a good choice. I am based in bay area and spending too much time in blockchain world.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
