### ISSUE TITLE
I want to go to NEO DevCon! My email: xihw@microsoft.com

### ISSUE THREAD

**Issue by xihw** [neo-project/neo.org#593]
I'm a Infra/Backend developer working in Microsoft. I have rich experiences in telemetry data/metric pipeline system/services. I also have experience in cloud services especially two years' experiences in developing AWS services previously. I'm skilled in many different languages C++, Java, Scala, Python, and technologies ELK, spark, docker...

I have great enthusiasm for blockchain technology. I studies blockchain in my spare time, have some investigations in Ethereum. This is a project with my friend: https://github.com/CryptoLove2018/LoveContractBeta.git

I wish to get a chance to attend the conference, learning technologies and meeting brilliant people!!

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
