### ISSUE TITLE
I want to go to NEO DevCon! My email: rk2749@columbia.edu

### ISSUE THREAD

**Issue by rkapurbh** [neo-project/neo.org#594]
I'm a Student IOS and Blockchain Developer at Columbia University. I study Computer Science & Economics. Here is a link to an [app](https://itunes.apple.com/us/app/kikoo-create-an-emoji/id1214159936?mt=8) I built. I've done research in p2p networks, graph theory, and exchange-based financial markets.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
