### ISSUE TITLE
I want to go to NEO DevCon! My email: nanandan3@gatech.edu

### ISSUE THREAD

**Issue by niteshanandan** [neo-project/neo.org#595]
Hey! I'm a grad student at Georgia Tech and a software engineer at Salesforce. I've also taken a blockchain for developers course at UC Berkeley. 
https://github.com/niteshanandan

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
