### ISSUE TITLE
I want to go to NEO DevCon! My email: lamhenry09@gmail.com

### ISSUE THREAD

**Issue by hennyname** [neo-project/neo.org#596]
I'm interested in the future and NEO is the future. I heavily invested in NEO coins and think the architecture, code base, support, and community are renounced as the next gen crypto coin that will take over the world. It would be a great birthday present to go to the NEO conference.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
