### ISSUE TITLE
I want to go to NEO DevCon! My email: kray@sonsothunder.com

### ISSUE THREAD

**Issue by kenray** [neo-project/neo.org#597]
My name is Ken Ray and I've been coding for decades, but I'm about to get involved in the first blockchain project I've ever had (it's not set up on GitHub yet though - we haven't started coding yet). I'm really excited to go to NEO DevCon though, so please send me a ticket if you can spare one!

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
