### ISSUE TITLE
I want to go to NEO DevCon! My email: nat.wittayatanaseth@kellogg.northwestern.edu

### ISSUE THREAD

**Issue by Nattariya** [neo-project/neo.org#599]

**Comment by Nattariya** [comment]
Hi, I'm a FinTech believer and Blockchain/Crypto enthusiast. I am interning at Pantera Capital, and has been involved in the VC space both in Asia and at 500 Startups. I see a lot of deal flows through Pantera, and I help advise companies on how they can develop they business model and make a case for fundraising. The project that I'm involved in advising the most is {Set} Protocol. 

https://github.com/felix2feng/Set-Protocol

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
