### ISSUE TITLE
I want to go to NEO DevCon! My email: stefandasbach@gmail.com

### ISSUE THREAD

**Issue by Stefandasbach** [neo-project/neo.org#60]
I’ve been interested in NEO for a while and want to get more involved in development. I participated in the first dApp competition, submitting Lucky NEO along with my team (https://github.com/mmoravec/luckyneo). I’m particularly strong at iOS, macOS, and web development. I think the community could use a better iOS and macOS application presence.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Stefandasbach
