### ISSUE TITLE
I want to go to NEO DevCon! My email: nvodoor@gmail.com

### ISSUE THREAD

**Issue by nvodoor** [neo-project/neo.org#600]
I'm a software engineer and data analyst who is experienced with Javascript and Python.

My Linked In is here: www.linkedin.com/in/nvodoor

I'm experienced in Python, PHP & Javascript. I've utilized the React.js framework to develop a variety of projects. I've also developed a RESTFUL API.

I'm a recent investor and developer in crypto. I've developed a Cryptopia API wrapper: https://github.com/DiscoBotDev/CryptopiaAPI

I would love to learn how to develop dAPPs on Neo and I'm hopeful I can get in to your conference to do so.

**Comment by chenzhitong** [comment]
We have a total of 400 free tickets, now all the tickets have been sent out, thank you for your enthusiastic participation。The application for free tickets has been closed。
