### ISSUE TITLE
I want to go NEO DevCon! My email: v_garcia9@hotmail.com

### ISSUE THREAD

**Issue by victorgarcia9** [neo-project/neo.org#61]
Hey, I am Victor Garcia a current full stack developer and solidity engineer working on the HelloSugoi project, a platform created to improve the economic relationship between artists, event organizers, and vendor services. I am currently working with my team to improve our ledger technology.

https://www.hellosugoi.com/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @victorgarcia9
