### ISSUE TITLE
I want to go NEO DevCon! My email: wicia_6@wp.pl

### ISSUE THREAD

**Issue by Wiciaki** [neo-project/neo.org#62]
Hey there, I'm a junior C#/Java developer.

I'm highly interested in the blockchain technology, although I haven't participated in any blockchain projects yet. 

Do you have a place for an inexperienced, yet excited developer like me?

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @Wiciaki

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?

**Comment by chenzhitong** [comment]
你烦不烦，就因为你没得到票，就要质疑所有拿到票的开发者吗，你在GitHub曾经有过一行代码？ @TheCoinJunkie
