### ISSUE TITLE
Neo Address Validation for Test Net

### ISSUE THREAD

**Issue by prathab** [neo-project/neo.org#625]
Hi,

The TestNet application checks if the Neo public address matches "0[0-9|abcdef]{65}"
https://github.com/neo-project/neo.org/blob/27f0f9079b4d75cab1d1bd5583b6607bc3bcf35d/NeoWeb/Views/Testnet/Create.cshtml#L73

But when I generate a address using wallet it doesn't follow this regex.   So one of them should be wrong or am I missing something very basic?

Prathab

**Comment by chenzhitong** [comment]
This field is NEO public key, not NEO address. @prathab

**Comment by chenzhitong** [comment]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/6295602/35791649-232b6222-0a84-11e8-81fc-872f5a946e52.png">
Please enter your own NEO public key. If the application succeeds, we will send Neo/GAS to a multiple signature address and tell you how to use it.

**Comment by bittcoin555** [comment]
Application is where and where pozt neo public address send info to bittcoin@protonmail.com or twitter @143cryptocouple
