### ISSUE TITLE
I want to go NEO DevCon! My email: jmsaulnier.dev@gmail.com

### ISSUE THREAD

**Issue by jmsaulnier** [neo-project/neo.org#64]
Currently creative developer interested starting developing smart contracts on NEO (Antshares ^^) blockchain and starting contributing to COZ https://github.com/CityOfZion/neon-wallet/pull/376, I actually would love to work full time on NEO ecosystem :)
Except Coinbase, crypto projects lack in general of good User Experience, I would love to contribute improving this :)
Dev Con would be the best to understand better NEO ecosystem (bright) future :)

https://www.linkedin.com/in/jmsaulnier/

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jmsaulnier
