### ISSUE TITLE
I want to go NEO DevCon! My email: bestfrienndk@gmail.com

### ISSUE THREAD

**Issue by bestfriendndk** [neo-project/neo.org#65]
Hey there, I'm a junior C#/nodejs/php developer.

I'm highly interested in the blockchain technology, although I haven't participated in any blockchain projects yet.

Do you have a place for an inexperienced, yet excited developer like me?

**Comment by Wiciaki** [comment]
You could as well write your own, original description, rather than copy mine.

https://github.com/neo-project/neo.org/issues/62
