### ISSUE TITLE
 I want to go NEO DevCon! 

### ISSUE THREAD

**Issue by tanitall** [neo-project/neo.org#66]
I am a new developer learning blockchain technology and would love to attend to learn more about NEO!

I have been following and supporting NEO for about 7 months now on NEO's Slack & NEO Discord, Reddit, and Telegram.   Compared to others here, I may not have the experienced blockchain programming credentials, but I have the heart and energy to learn more about NEO and develop in it!   I am an experienced data analyst and leader, with 10 years experience in database/data warehousing and business intelligence/analytics.  

Please consider me and I hope I can get the opportunity to grow and develop!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tanitall

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?
