### ISSUE TITLE
Image for Alex Guba not loading correctly

### ISSUE THREAD

**Issue by gubanotorious** [neo-project/neo.org#662]
Local tests / load of the image pass fine, but when deployed to NEO.org, the base64 loaded image bytes are representing an empty / blank image.  

The image is correctly added and appears in the project wwwroot/images/team in the csproj.   I can't identify the issue causing the loading issue on the production site from my end locally.

Was it deployed correctly?

![local](https://user-images.githubusercontent.com/6355333/39055215-9992dd46-4481-11e8-9495-e1a48482f4b5.JPG)
![neo](https://user-images.githubusercontent.com/6355333/39055216-99a3333a-4481-11e8-8633-2e2b302246fb.JPG)

**Comment by chenzhitong** [comment]
I'm sorry, it was a mistake in the deployment process, and I'm going to fix this in Monday. @gubanotorious
