### ISSUE TITLE
I want to go NEO DevCon! My email: shannon@carbonfive.com

### ISSUE THREAD

**Issue by shannonwells** [neo-project/neo.org#67]
I'm a developer for a contracting firm in SF.  I have only started being interested in blockchain this year and I am very interested in developing for the NEO blockchain.  I'm not participating in developing blockchain projects currently, however, I am giving an Intro to Blockchain talk at CodeMash next week. I'm a full stack web developer also good with APIs (both design and integration).  I'm mainly interested in applications for blockchain other than cryptocurrency.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @shannonwells

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?
