### ISSUE TITLE
I want to go NEO DevCon! My email: ken@carbonfive.com

### ISSUE THREAD

**Issue by viceversus** [neo-project/neo.org#68]
My name is Ken Shimizu, and I have been developing software professionally for 5 years.

I am a Android, iOS, Web Developer and Team Lead at Carbon Five. I have not participated in any cryptocurrency projects, but am taking a class in February.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @viceversus

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ? 

Says " i have not participated in any cryptocurrency projects"

**Comment by chenzhitong** [comment]
你烦不烦，就因为你没得到票，就要质疑所有拿到票的开发者吗，你在GitHub上曾经有过一行代码？ @TheCoinJunkie
