### ISSUE TITLE
 I want to go NEO DevCon! My email: aneyzberg@gmail.com

### ISSUE THREAD

**Issue by aneyzberg** [neo-project/neo.org#69]
My name is Anna Neyzberg and I am a developer at a consultancy called Carbon Five. 

I have currently been learning about Block chain using solidity, following the newline course. 

I am currently very interested in the Elixir programming language and started and organization last year to help underrepresented folks in tech learn Elixir and Phoenix.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @aneyzberg

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?
