### ISSUE TITLE
I want to go NEO DevCon! My email: dbschwartz@protonmail.com

### ISSUE THREAD

**Issue by dvdschwrtz** [neo-project/neo.org#71]
I work on Neon Wallet, Neo Scan and NEX. My old username was bjornborg on slack but I changed it to my github handle. I am really excited to attend the conference and meet everyone!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @dvdschwrtz

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?
