### ISSUE TITLE
I want to go NEO DevCon! My email: t@tonyy.in

### ISSUE THREAD

**Issue by tonyin** [neo-project/neo.org#72]
Hi there! I'm an ex- Data Scientist @Linkedin and Trader @Optiver. I started my own business last year focused on consumer apps and blogging. My development strengths are data (analysis, SQL, ETL data pipelines, visualization), web apps (javascript), and general scripting (python). I would love to start developing NEO dapps!

Ethereum (Solidity) investing DAO: https://github.com/tonyin/the-daio
Shills tracker for NEO discord #market channel: https://github.com/tonyin/neoblockcha.in (located at https://neoblockcha.in/shillist)
Crypto weekly roundup articles and whitepaper summaries: https://steemit.com/@aeto

Thank you Neo DevCon team!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tonyin
