### ISSUE TITLE
I want to go NEO DevCon! My email: neo-devcon@midnight-labs.org

### ISSUE THREAD

**Issue by HarryR** [neo-project/neo.org#74]
See my github account.

I am interested in bringing privacy and anonymity solutions to NEO, as well as the technology to introduce cross-chain atomic swaps to NEO which are compatible with Bitcoin, Mimblewimble and Ethereum.

See:

 * https://github.com/clearmatics/mobius
 * https://github.com/HarryR/solcrypto

etc.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @HarryR
