### ISSUE TITLE
I want to go NEO DevCon! My email: vsv819@gmail.com

### ISSUE THREAD

**Issue by vskryabin** [neo-project/neo.org#75]
Hello NEO team,

I'm a full-stack developer located in San Francisco Bay Area and I have worked for over 10 years on a large variety of products including SaaS, Cloud applications, distributed systems with Java and C#.
I also worked on Apple and Android metadata-driven apps on Objective C and Java.

I also doing various presentations and teaching development on Objective C, Java and related technologies.

I'm currently going over blockchain technologies and want to start developing cool dApps projects on NEO myself or with my teammates.

Would love to go to NEO DevCon and spread the word! Thank you very much!

Regards,
Slava Skryabin

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about?  @vskryabin

**Comment by vskryabin** [comment]
Hello @chenzhitong, please take a look at the following publish for Mobile metadata-driven applications I have contributed. I can provide you references which will confirm my heavy development involvement:

TAP (acquired by Oracle, iOS & Android)
https://itunes.apple.com/us/app/oracle-hcm-cloud/id529345370?mt=8
https://play.google.com/store/apps/details?id=com.oracle.apps.oracle_tap&hl=en
http://www.youtube.com/watch?v=cK4aW0kZTWs&t=87m45s (Taleo presentation)
https://www.youtube.com/watch?v=_VV6SkOM-Bc (Oracle)

The following on SaaS Cloud applications 
http://www.oracle.com/us/products/applications/taleo/business-edition/overview/index.html (acquired by Oracle from Taleo)
http://www.oracle.com/us/products/applications/taleo/enterprise/learn/features/index.html (acquired from Learn.com)
Can provide references as well.

I also have patent pending in the last phase on development project which you can check my name on (2 inventors: Viacheslav Skryabin and Brijeshkumar Chavda)
https://portal.uspto.gov/pair/PublicPair
The application number is 14/681,996.

I teach on the nights and weekends as well at Potnov Computer School https://www.portnov.com/ and plan to start doing it about blockchain technologies on other schools.

I have been following NEO since Antshares times and believe in NEO great potential. We would like to start building NEO based projects and I believe DevCon could be a big step to look into that! 

Let me know if you need any other information from me.

**Comment by vskryabin** [comment]
@chenzhitong, I'm a bit nervous if you read my message, let me know if you have any comments. Hope to see you in San Francisco!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @vskryabin
