### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: kimrader@gmail.com

### ISSUE THREAD

**Issue by kimbor** [neo-project/neo.org#767]
I'm a student working on MSc in Digital Currency from University of Nicosia. I'm also an IT manager with 20 years of industry experience. My solidity-related github projects:
https://github.com/kimbor/lottery-react
https://github.com/kimbor/remittance
https://github.com/kimbor/splitter

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.
