### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: gconaty@gmail.com

### ISSUE THREAD

**Issue by gconaty** [neo-project/neo.org#769]
1) Garrett is a a technical leader who finds fulfillment in critical analysis of new technologies, creating practical applications, and teaching. He has had many opportunities to work on the leading edge of the technical curve for 20+ years, including CORBA, J2EE, the commercialization of open source, Javascript frameworks, cloud migration and most recently blockchain.

2) Leading teams of developers to ship great products.  Discovering the value in new tech and its applications

3) Mostly private (blockchain: https://github.com/AnimalVentures)

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.

**Comment by sitaxi** [comment]
If you have any questions feel free to respond the mail to me.
