### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: hasseljr@ucmail.uc.edu

### ISSUE THREAD

**Issue by hasseljr** [neo-project/neo.org#770]
I'm an aerospace engineer with 5 years work experience. In my career I use Matlab (analytical programming, similar language to C), and LabView (graphical programming) nearly every day. I started programming in high school and am quite comfortable with C/C++, Java, HTML. I do not have any contributions on Github unfortunately as the majority of my coding thus far has been for private sector. However I am very interested to get involved with cryptocurrencies and in particular NEO. I have no doubts over the future of cryptocurrencies and over the past few years learning about them has become a passion of mine, I would love to learn to contribute.

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.

**Comment by sitaxi** [comment]
If you have any questions feel free to respond the mail to me.
