### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: jcqnly@gmail.com

### ISSUE THREAD

**Issue by jcqnly** [neo-project/neo.org#772]
1) Software Engineer looking to change the face of the development field by helping under represented engineers break into the field.
2) Area of expertise - C#, ASP.NET
3) I am involved with - 
https://github.com/Will-Clinic/Front-end-Application
https://github.com/Noodlicious
https://github.com/MisterRobotoArigato

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.

**Comment by sitaxi** [comment]
If you have any questions feel free to respond the mail to me.
