### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: trueinsider@gmail.com

### ISSUE THREAD

**Issue by trueinsider** [neo-project/neo.org#773]
I'm a Sr Backend Engineer with experience over 7 years in GameDev. I've been contributing to some blockchain projects since May 2018 (nOS, Ontology, NKN).

I have experience building distributed systems that scale and interested in core blockchain technology.

Some projects could be found on my repository page:
https://github.com/trueinsider?tab=repositories

https://github.com/nos/client/pulls?q=is%3Apr+author%3Atrueinsider+is%3Aclosed
https://github.com/OntologyCommunityDevelopers/ontology-kotlin-sdk
https://github.com/nknorg/nkn/pulls?q=is%3Apr+author%3Atrueinsider+is%3Aclosed

Also I won two intermediate challenges in NEO Blockchain Challenge Tokyo 8.24:
https://github.com/neo-ngd/Hackathon/blob/master/8.24%20NEO%20Blockchain%20Challenge%20-%20Tokyo.md#challenge-result

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.

**Comment by sitaxi** [comment]
If you have any questions feel free to respond the mail to me.
