### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: Suldan.mohamed@stonybrook.edu

### ISSUE THREAD

**Issue by suldanm** [neo-project/neo.org#775]
Greetings,

I am a Public Health student at Stony Brook University who really sees a future with the NEO platform. I recently went to Madagascar for the past semester working with the reforestation team, my project focus was utilizing the positive aspects of blockchain technology into tracking carbon emissions with credits. I believe in blockchain and its real world application. It would be a great blessing to be able to attend DevCon 2019.

All the best,
Suldan Mohamed

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.

**Comment by sitaxi** [comment]
If you have any questions feel free to respond the mail to me.
