### ISSUE TITLE
I want to go to DevCon! My email: s-patrick.taiwo@lwtech.edu

### ISSUE THREAD

**Issue by nin369** [neo-project/neo.org#778]
Hi there, my name is Patrick and I'm a concept designer and illustrator striving to obtain a Bachelor's degree in Digital Gaming and Interactive Media at Lake Washington Institute of Technology. After taking certain paths, I've decided to make a drastic career change from the horticulture industry to the video game industry due to the fact that I've always been passionate about art and video games ever since I was a child. Long story short, I've been working on a incredibly ambitious vision for the future of gaming which focuses on the  implementation of digital currencies within its framework in order to unleash a new era of gaming and possibilities.  I have very little knowledge/experience with digital currencies and blockchain technology, though the case for integrating such components throughout society is becoming increasingly compelling as advancements are progressing. Being a Washington State resident, as well as an aspiring ambitious artist, gamer and visionary, it would be an excellent learning opportunity to attend this convention and gain knowledge over what I'm fully convinced will give rise to the next greatest thing. I hope to see you there!

-Patrick A. Taiwo

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.
