### ISSUE TITLE
I want to go to NEO DevCon 2019! My email: johntheodorecooper@gmail.com

### ISSUE THREAD

**Issue by johntc77** [neo-project/neo.org#779]
Hi there,

I'm a block development student. I run a blockchain development company based out of Vancouver and I'm currently learning new software development skills related to blockchain and cryptocurrency. My area of expertise is in economic research and quantitive modeling use Python and R. I am currently involved in a few private company projects including: a supply chain management software for a local gold mining company, a renewable energy project leveraging the Tezos network, and a crypto-mining auditing project. 

Thanks,
John

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.
