### ISSUE TITLE
 I want to go to NEO DevCon! My Email: snowypowers@gmail.com

### ISSUE THREAD

**Issue by snowypowers** [neo-project/neo.org#78]
I am the main maintainer of `@cityofzion/neon-js` and would like to join the devcon. I started off as a translator but moved into dev work.

https://github.com/snowypowers/ansy
https://github.com/CityOfZion/neon-js

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @snowypowers
