### ISSUE TITLE
Type the issue title as: “I want to go to NEO DevCon 2019! My email: paulmbultman@gmail.com

### ISSUE THREAD

**Issue by indiemusic** [neo-project/neo.org#781]
1) My name is Paul Bultman and I have run the website Indie-Music.com since 1996. I'm currently interested in the potential crossover of Music and Crypto. I also work as a telegram chat monitor for the Viola.AI project, Matchmaking app using AI and Crypto (VAI) 
2) Entertainment / Crypto Market
3) https://github.com/ViolaAI

**Comment by sitaxi** [comment]
Thank you for your support.Plz check your email later.
