### ISSUE TITLE
I want to go NEO DevCon! My email: ronald.mannak@gmail.com

### ISSUE THREAD

**Issue by ronaldmannak** [neo-project/neo.org#79]
Developer of the open source native Swifthereum framework (http://github.com/indisputableLabs/Swifthereum/). I foresee demand for native blockchain apps increasing for mobile and desktop apps, once blockchain becomes a more mainstream accepted. Swifthereum is the native framework which I plan to expand to multiple blockchains.

Currently co-founder of Indisputable Labs. Previously PhD student on trust in P2P networks.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @ronaldmannak
