### ISSUE TITLE
I want to go NEO DevCon! My email: susguzman@gmail.com

### ISSUE THREAD

**Issue by susguzman** [neo-project/neo.org#82]
I am a developer, database administrator and now Neo and blockchain lover. I work and live in Guatemala.

With my friends and I have created a developer team named MayaDev to participate in the first Neo Dev Competition. We are so excited know more about Neo and become us Neo Developers.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @susguzman
