### ISSUE TITLE
I want to go to NEO DevCon! My email: hamdi.allam97@gmail.com

### ISSUE THREAD

**Issue by hamdiallam** [neo-project/neo.org#83]
Hi! I currently am a junior at UC Berkeley studying Electrical Engineering and Computer Science. I am super interested and am an investor in NEO. I am currently learning more about dApp development and the technical implementation of NEO's platform with the intent to become a consistent contributor. It would be super exciting to attend the DevCon!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @hamdiallam
