### ISSUE TITLE
I want to go to NEO DevCon! My email: blockchainmcbain@gmail.com

### ISSUE THREAD

**Issue by blockchainmcbain** [neo-project/neo.org#84]
I found NEO con in my research to update my project: https://github.com/blockchainmcbain/Free-DAPP-Bootcamp

I'm Hoping to build a repo full of lessons and resources as a one stop guide to becoming a DAPP developer. I would love to come to the event to learn and meet people.

**Comment by chenzhitong** [comment]
Sorry, you joined GitHub 3 days ago, I'm not sure you're a developer. @blockchainmcbain
