### ISSUE TITLE
I want to go to NEO DevCon! My email: xxx

### ISSUE THREAD

**Issue by felix2feng** [neo-project/neo.org#85]
Hey! My name is Felix and I'm working on a project called [{Set} protocol](https://setprotocol.com). We're working on collateralized baskets of tokens on smart contracting blockchains. {Set} allows any user to take a number of different tokens and synthesize them into a basket. As more people create tokens on top of NEO, I believe there will be a strong need for protocol-level token abstractions - which {Set} is ready to solve. Although we've started with Ethereum, we want to build {Set} on NEO as well.

Here's my github link:
https://github.com/setprotocol

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @felix2feng
