### ISSUE TITLE
I want to go NEO DevCon! My email: dzshubin@live.com

### ISSUE THREAD

**Issue by dzshubin** [neo-project/neo.org#86]
I'm a student from peking university  and I'm interested in NEO. I've paid close attention to it. I'm good at develop smart contract. I really wanna  participate in DevCon.

**Comment by chenzhitong** [comment]
I find you have closed this issue. Do you want to go NEO DevCon now? @dzshubin

**Comment by dzshubin** [comment]
I'm sorry. I'm preparing for the NEO developer competition and I wanna meet more developer at the NEO DecCon, But it's too far, I thought the meeting would hold at beijing.

**Comment by dzshubin** [comment]
@chenzhitong
