### ISSUE TITLE
I want to go to NEO DevCon! My email: artiom@tutanota.de

### ISSUE THREAD

**Issue by block-shaman** [neo-project/neo.org#87]
I am entrepreneur and part-time software developer. I am big fan of NEO ecosystem and community. I have participated in CoZ Competition #1 and my dapp entry was a valid entry. I have also encouraged alot of other people about NEO, investors and at least 2 more developers. So I would be really really happy to come to the conference! Let me know please because I have to book tickets from Australia in advance.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @block-shaman
