### ISSUE TITLE
floated button

### ISSUE THREAD

**Issue by BorisBurbon** [neo-project/neo.org#879]
floated button https://prnt.sc/yt47qf
Do it better this way
1) remove unnecessary properties https://prnt.sc/yt4ucu https://prnt.sc/yt4vq3
2) Add just one property to the parent https://prnt.sc/yt52ht
judging from this code, it is clear that your developer does not fully understand how "vertical-align: middle" works;

**Comment by nrunje** [comment]
That makes complete sense. Whoever has admin properties grant write this and grant a pull request.

**Comment by chenzhitong** [comment]
fixed https://github.com/neo-project/neo.org/pull/876/commits/a73d6d43bf38b2a44116843f139715a8ea5cc1ef
thanks.

**Comment by BorisBurbon** [comment]
thanks
