### ISSUE TITLE
I want to go NEO DevCon! My email: petko.karamotchev@industria.tech

### ISSUE THREAD

**Issue by karamotchev** [neo-project/neo.org#88]
I have not uploaded any code on GitHub, however the team I am managing is working big time with regional for CEE banks and international banking and non-banking financial institutions.

We have several use cases for NEO and clients waiting for us to decide are going to work with NEO, Ethereum (the Enterprise Alliance) or Hyperledger Fabric.

**Comment by chenzhitong** [comment]
Sorry, the free tickets are only for developers who have contributed to the GitHub. @karamotchev

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @karamotchev
