### ISSUE TITLE
Broken link to Java NEP-17 contract example

### ISSUE THREAD

**Issue by mialbu** [neo-project/neo.org#884]
On the developer page on [neo.org](https://neo.org/dev#examples) in the examples, the link to the Java NEP-17 contract example is broken and should be directed to : [https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/FungibleToken.java](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/FungibleToken.java)

**Comment by chenzhitong** [comment]
fixed https://github.com/neo-project/neo.org/pull/885
