### ISSUE TITLE
some changes to neo.org

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo.org#886]
I would like that some things to get fixed/change in the current neo.org website. Below you can find a list.

- AxLabs logo should be changed on the communities page (https://neo.org/contributors#communities).
  - You can get the AxLabs logo, here: https://1drv.ms/u/s!Al_mHqih3JTiibJkpZ-GoQP5I6TQkQ?e=0No7CV
  - Maybe you will need to resize/treat the logo a bit to make it compatible to the page -- let me know if you need some help.
  - From now on, please use AxLabs logo instead of neow3j. 😄 

- Change some things in the Java code example on the neo.org page.
  - The "Documentation" link should point to: https://neow3j.io
  - The "Templates" link should point to: https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/
  - The code should be the NEP-17 from this file: https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/FungibleToken.java
  - PLEASE, instead of sevel imports, use just two:
  ```java
  import static io.neow3j.devpack.StringLiteralHelper.addressToScriptHash;
  import io.neow3j.devpack.*;
  ```

**Comment by chenzhitong** [comment]
fixed

**Comment by gsmachado** [comment]
Great! Thanks!
