### ISSUE TITLE
I want to go NEO DevCon! My email: everestuar@gmail.com

### ISSUE THREAD

**Issue by everestuar** [neo-project/neo.org#89]
Hello Neo!

I am a developer  and database admin. I started in the world of blockchain thanks to Neo. With some friends, we have formed a dev team called MayaDev to implement solutions based on this blockchain.

I really think Neo is a groundbreaking technology and I would love to go to DevCon!

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about? @everestuar

**Comment by everestuar** [comment]
Hi, sorry, to be honest we are starting the project and right now we are in
the Pland and Desing Phase. But I have experience developing in Java,
Visual C#, PHP, Qt, Perl and others, also some experience in Big Data, Data
Mining and AWS projects. Some of my teammates in MayaDev are @susguzman
<https://github.com/susguzman> and @ericknavarro
<https://github.com/ericknavarro>.

I hope I can apply, Neo is the future!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-05 1:42 GMT-06:00 陈志同 <notifications@github.com>:

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox.  @everestuar

**Comment by everestuar** [comment]
Thank you so much Neo!! I'm really looking forward to the DevCon. Great things ahead!!

**Comment by chenzhitong** [comment]
Sorry, your information does not prove that you are a real developer, but due to audit errors, will promotional code sent to you. Now the promotional code has been voided. @everestuar

**Comment by everestuar** [comment]
Ahhh :-(

I already have reservation made at Europa Hostel near the place of the event. There's really zero chance? I've been involved in several projects but without using git repositories. Besides several certifications in Oracle Database if that maybe could help. 

I hope you could reconsidered because I really want to go!!

Best regards!

**Comment by everestuar** [comment]
Sorry, one more thing, prove of certifications: https://www.youracclaim.com/users/ever-lux
