### ISSUE TITLE
I want to go NEO DevCon! My email: ecrnd25@gmail.com

### ISSUE THREAD

**Issue by ericknavarro** [neo-project/neo.org#90]
I am a developer, data engineer and Neo lover. I work and live in Guatemala.

Me and my friends have created a development team named MayaDev to participate in the first Neo Dev Competition. We are so excited to know more about Neo and become Neo Developers.

I believe Neo is the future.

I would love to go to DevCon!

https://www.linkedin.com/in/erick-navarro-0a2611108

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about? @ericknavarro

**Comment by ericknavarro** [comment]
Hi, sorry, to be honest we are starting the project and right now we are in
the plan and desing phase. But I have experience developing in Java,
Visual C#, PHP, Qt, Perl and others, PL/SQL, T-SQL, Pentaho, also some experience in Big Data, Data
Mining and AWS projects. Some of my teammates in MayaDev are @susguzman
<https://github.com/susguzman> and @everestuar
<https://github.com/everestuar>.

I hope I can apply!

Neo is the future!

**Comment by chenzhitong** [comment]
The words you said were copy other people's? @ericknavarro

**Comment by ericknavarro** [comment]
My words are similar to @everestuar because we are part of the same team and we are in the same situation.

**Comment by chenzhitong** [comment]
Sorry, I can't give free tickets to you and everestuar, but due to the audit error, sent him free tickets.
