### ISSUE TITLE
Make release the default branch or use master for releases

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo.org#901]
When I go to https://github.com/neo-project/neo.org/ I see something old, unmaintained and not related to the current state of neo.org. While in fact all the hot stuff is there, just in the `release` branch. I don't quite understand why it's like that, either we need to make it the default one (but then why keeping unmaintained `master`?) or just merge it into `master` and let people navigate more easily (I know it's not the most popular repository, but still).

**Comment by chenzhitong** [comment]
I agree, but I don't have permission.
