### ISSUE TITLE
AxLabs is not appearing on the website (Communities section)

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo.org#904]
When I go to https://neo.org/contributors#communities, AxLabs is not listed. 😢 

I can see that AxLabs is indeed in the [source code](https://github.com/neo-project/neo.org/blob/master/NeoWeb/Views/Contributors/_CommunitiesPartial.cshtml#L21), but I don't know why it's not loading. Any clues?

**Comment by chenzhitong** [comment]
Sorry, it's fixed.
