### ISSUE TITLE
I want to go NEO DevCon! My email: kkj6781@gmail.com

### ISSUE THREAD

**Issue by kkj6781** [neo-project/neo.org#91]
I studied Industrial Engineering and Mathematics in college. Having a strong focus in Mathematics and Theoretical Computer Science, I naturally took some Number Theory and cryptography classes. These experiences led me to think more about the future of cryptocurrency early on. 
Outside of school, I have an experience as a research intern at the Columbia Business School's Decision, Risk, and Operations Division, where I helped writing a simulation to emulate a real-life queuing system. Currently, I am working as a financial consultant and full stack developer, where I utilize my skills in Python, Angular, React, Node, MongoDB, AWS, etc. In a few months, I will be launching a (non-blockchain related) technology startup that I have been preparing since 2017. My friend and I have also been designing a blockchain related project that will use smart contracts as its base. Unfortunately, I cannot share the github link since it is proprietary; however, I am willing to talk more about the idea in person. I actively follow current events regarding blockchain, and I would like to contribute to this community.

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about? @kkj6781

**Comment by kkj6781** [comment]
All the projects are work-related, and thus are set to be private. I can discuss about it in high-level with you if you would like, using any medium of your preference. 

If your goal is to see how I write my code, then I may be able to upload some sample codes. Please let me know if that was your intention.

**Comment by chenzhitong** [comment]
Just give me something to prove you're a developer. @kkj6781

**Comment by kkj6781** [comment]
Hi Zhitong,

I tried my best to prove my claim without giving away too much information. I hope you understand that the projects are in the developing phase, and it would be a selfish act towards my coworkers if I reveal our work for the DevCon ticket. 

Below are some screenshots of github/gitlab commits. If there are other ways of proof that you would like to see, then please let me know and I will try my best to accommodate. I've been involved more in Busyduck (first 3 pictures) as a lead developer, and I'm just helping out here and there for the other project (last 2 pictures). The github account is the same one as the one I'm using, and the gitlab account, as shown in the screenshot, is pkim@regulatedconsultants.com. Please feel free to send me an email, and I will reply to prove that it's mine.

<img width="812" alt="busyduck1" src="https://user-images.githubusercontent.com/18505026/34643397-b1cee670-f2f1-11e7-916a-2b9d55d76d95.PNG">
<img width="762" alt="busyduck2" src="https://user-images.githubusercontent.com/18505026/34643398-b1d908f8-f2f1-11e7-9d0a-783f90e49829.PNG">
<img width="751" alt="busyduck3" src="https://user-images.githubusercontent.com/18505026/34643399-b1e3ad26-f2f1-11e7-894d-ad6e90927925.PNG">
<img width="864" alt="pngui" src="https://user-images.githubusercontent.com/18505026/34643401-b1ed9886-f2f1-11e7-9b83-a7d2296b5f6a.png">
<img width="864" alt="pnserver" src="https://user-images.githubusercontent.com/18505026/34643402-b1f8fac8-f2f1-11e7-9190-9da7779180aa.png">

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @kkj6781

**Comment by kkj6781** [comment]
Thank you, Zhitong. I got the email.
