### ISSUE TITLE
I want to go to NEO DevCon! My email: jwon2005@gmail.com

### ISSUE THREAD

**Issue by jwon2005** [neo-project/neo.org#92]
I am a graduate student at Columbia University studying Machine Learning and Cryptography, and I have development experiences on C, C++, and Python. 

I've been very excited to learn about the blockchain technology and I would very much appreciate the opportunity to attend the DevCon to learn more about NEO and network with other developers and industry experts. Although I do not have much experience in blockchain programming, I firmly believe that I have the technical background and motivation to become a new blockchain developer. I would like to use the opportunity to expand my knowledge and skill-set and to simultaneously help contribute to the NEO platform and the community.

I really appreciate your time and the opportunity!

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about? @jwon2005

**Comment by jwon2005** [comment]
I work in the aerospace/defense industry and I cannot share my projects due to EAR/ITAR regulations (Please see my profile on LinkedIn: https://www.linkedin.com/in/jaewon-lee-0437237b/), but I have uploaded some of the Machine Learning codes I wrote for a hand-written digit classification project this past Fall 2017 semester at my grad school.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @jwon2005
