### ISSUE TITLE
I REALLY want to go NEO DevCon! My email: jjjeter111@gmail.com

### ISSUE THREAD

**Issue by jjjeter111** [neo-project/neo.org#93]
Hi there!

I've been a developer for the past year and just started developing blockchain applications for Ethereum and NEO. NEO's my main focus now as I'm starting to understand the many advantages it has compared to other blockchains. 

Ontology is another project I'm very excited to learn more about. Can't wait to leverage Ontology's Identification Protocol into the automotive repair/maintenance project I'm working o

Lastly I've been investing in the crypto space for over 3 years. I have a large network here in SV and would love to meet more folks building for the NEO ecosystem. 

Best,
JJJ

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about? @jjjeter111
