### ISSUE TITLE
I want to go NEO DevCon! My email: hernan.wilkinson@10pines.com

### ISSUE THREAD

**Issue by hernanwilkinson** [neo-project/neo.org#97]
Hi!
 I've been developing software since I was 14 years old, that is 32 years programming! I have experience in Assembler, C, C++, Smalltalk, Python, C#, Go and many other languages. I teach Object Oriented programming at the University of Buenos Aires, I have given many talks at different conferences (OOSPLA, ESUG, Smalltalks, Agile, etc), founded a software development company (10Pines) and a foundation to promote Smalltalk in Argentina (FAST). 
 I started to read and invest on cryptocurrencies two months ago and I really want to manage and understand even more this technology, how to write apps that uses Blockchain, see the new business opportunities it opens, etc.
 I'm from Argentina and I'll be staying in SF that week, so it would be great for me to attend to the conference and bring back to my country and company the opportunity this technology offers.

 Thanks!

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @hernanwilkinson
