### ISSUE TITLE
I want to go to NEO DevCon! My email: tingwai.to@gmail.com

### ISSUE THREAD

**Issue by tingwai-to** [neo-project/neo.org#98]
Hi, I am a developer writing a smart contract on NEO for group purchasing (imagine Groupon on NEO), I plan to submit this to the 2nd CoZ competition. I currently work at a quantum computing startup with past experience in high performance computing research, and am excited to see how I can leverage this into the NEO ecosystem.

My latest project is a crypto trading bot ([link](https://github.com/tingwai-to/trading-bot)) that collects real-time prices from crypto exchanges and places buy/sell trades. It also includes a backtesting module to test trading algorithms against the historical data collected.

I am active on the NEO Discord under the handle Sh_ft and I would love to get to meet the team and everyone at the conference.

https://www.linkedin.com/in/tingwaito

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @tingwai-to
