### ISSUE TITLE
I want to go NEO DevCon! My email: ezra.weinstein@sealoftrust.io

### ISSUE THREAD

**Issue by ezgadgets** [neo-project/neo.org#99]
Greetings to the NEO team,

I've been in the software development world for over 3 decades with experience in various languages and platforms dating back to the DOS days.  But I pride myself in always staying up to date with the latest technologies.  I have been involved in various ventures in the retail, distribution and delivery services.  

Myself and a small team have decided to explore launching a project that leverages the incredible NEO ecosystem.  I invested in NEO several months ago and have been generating GAS ever since.  I am a huge believer in NEO and excited to work on a project that is based in China.  I have been studying Chinese along with my son who just competed in the International Kung Fu tournament in Emeishan China last month. 

Our project is unique has a real world application and most importantly can be easily explained to NON crypto people (which is the majority of the world) and solves a very simple problem.

I absolutely would love to meet everyone in San Francisco and learn everything I can about NEO so I can help build an amazing platform and as a result help grow the NEO Ecosystem.

Thanks in advance for your consideration.

Ezra

**Comment by chenzhitong** [comment]
Don't you have any repositories on your github? Where can I see the project you're talking about? @ezgadgets

**Comment by ezgadgets** [comment]
@chenzhitong We have not started coding yet. Right now we are in concept phase and assembling the full team.  We are still working on the white paper.  Our web site is not up yet either, but we plan to start moving very rapidly.  

One fo the reasons I want to go to the Devcon is to educate myself on the platform and hopefully also connect with some programmers that have some experience with NEO.

**Comment by chenzhitong** [comment]
Okay, you can buy tickets for DevCon. The free tickets are only for developers who have contributed to the GitHub. @ezgadgets

**Comment by ezgadgets** [comment]
Thanks @chenzhitong ,but this is not fair. You awarded ticket to several developers who clearly have not contributed anything.  As an example look at: petko.karamotchev@industria.tech.  He even says and I quote:

"I have not uploaded any code on GitHub, however the team I am managing is working big time with regional for CEE banks and international banking and non-banking financial institutions."

Many other examples that I can show you.  So why would you deny me a ticket when we are looking to provide contribution of code just like everyone else?

I would appreciate if you would please reconsider your decision.  This conference is going to be very expensive to attend.  The hotel, the flight, all very expensive.

**Comment by chenzhitong** [comment]
I didn't give that guy a free ticket.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/6295602/34600107-c7e8bce0-f230-11e7-9b42-310cad316cb0.png">

I'll discuss with my colleagues if I should give you a free ticket.

**Comment by ezgadgets** [comment]
I apologize @chenzhitong, I read that wrong.  I hope to see you in San Francisco.  Thanks for your consideration.

**Comment by chenzhitong** [comment]
Can you give me some other links or photos that will prove you are a developer? @ezgadgets

**Comment by ezgadgets** [comment]
@chenzhitong this is a current project I am working on which is in ASP.NET Core. This is an MVC project that I just started, so it's quite basic but it will give you an idea of my work.

https://www.dropbox.com/sh/5jxp8s5mjrlqhnb/AAA66NaA1MAIDw2CamN5RSdNa?dl=0

Some of my other projects:
www.coreware.com
www.interactbuilder.com

You can email:  eweinstein@authentek.io,  ezra@interactstudios.com and ezra.weinstein@coreware.com and I will respond to each one of those emails to prove my involvement in all of these projects.

**Comment by chenzhitong** [comment]
Very good, the Promotional Code has been sent to your mailbox, please check your mailbox. @ezgadgets

**Comment by ezgadgets** [comment]
@chenzhitong 谢谢 🙏🏼..
